import type { Drug, Enzyme, EnzymeRole, ItemKind, PdFlag, Strength, SubstrateSensitivity } from "./types";

function sub(
  enzyme: Enzyme,
  sensitivity: SubstrateSensitivity,
  pathway: "clearance" | "activation" = "clearance",
  nti = false,
): EnzymeRole {
  return { enzyme, kind: "substrate", sensitivity, pathway, nti };
}

function inh(enzyme: Enzyme, strength: Strength): EnzymeRole {
  return { enzyme, kind: "inhibitor", strength };
}

function ind(enzyme: Enzyme, strength: Strength): EnzymeRole {
  return { enzyme, kind: "inducer", strength };
}

function d(
  id: string,
  name: string,
  brands: string[],
  cls: string,
  enzymes: EnzymeRole[],
  pd: PdFlag[],
  toxicityHint: string,
  extra?: { aliases?: string[]; note?: string; kind?: ItemKind },
): Drug {
  return {
    id,
    name,
    brands,
    cls,
    aliases: extra?.aliases ?? [],
    enzymes,
    pd,
    toxicityHint,
    note: extra?.note,
    kind: extra?.kind ?? "drug",
  };
}

const raw: Drug[] = [
  // —— Macrolides / azoles / antivirals ————————————————
  d("clarithromycin", "Clarithromycin", ["Biaxin"], "Macrolide antibiotic",
    [sub("CYP3A4", "major"), inh("CYP3A4", "strong"), inh("P-gp", "moderate")],
    ["qt-possible"], "QT prolongation, CYP3A4 perpetrator toxicity"),
  d("erythromycin", "Erythromycin", ["Ery-Tab"], "Macrolide antibiotic",
    [sub("CYP3A4", "major"), inh("CYP3A4", "moderate"), inh("P-gp", "moderate")],
    ["qt-possible"], "QT prolongation"),
  d("azithromycin", "Azithromycin", ["Zithromax", "Z-Pak"], "Macrolide antibiotic",
    [], ["qt-possible"], "QT prolongation",
    { note: "Minimal CYP3A4 inhibition unlike other macrolides." }),
  d("ciprofloxacin", "Ciprofloxacin", ["Cipro"], "Fluoroquinolone",
    [inh("CYP1A2", "strong"), inh("CYP3A4", "weak")],
    ["qt-possible", "seizure-lowering"], "QT, CNS stimulation, 1A2 victim toxicity"),
  d("levofloxacin", "Levofloxacin", ["Levaquin"], "Fluoroquinolone",
    [], ["qt-possible", "seizure-lowering"], "QT prolongation"),
  d("moxifloxacin", "Moxifloxacin", ["Avelox"], "Fluoroquinolone",
    [], ["qt-known"], "QT prolongation"),
  d("metronidazole", "Metronidazole", ["Flagyl"], "Nitroimidazole",
    [inh("CYP2C9", "weak")], ["seizure-lowering"], "Disulfiram-like reaction, neuropathy",
    { note: "2C9 inhibition is modest and debated; still flagged with warfarin." }),
  d("fluconazole", "Fluconazole", ["Diflucan"], "Azole antifungal",
    [sub("CYP3A4", "minor"), inh("CYP2C9", "strong"), inh("CYP2C19", "strong"), inh("CYP3A4", "moderate")],
    ["qt-possible"], "QT, elevated victim-drug levels"),
  d("ketoconazole", "Ketoconazole", ["Nizoral"], "Azole antifungal",
    [inh("CYP3A4", "strong"), inh("P-gp", "strong"), inh("CYP2C19", "moderate")],
    ["qt-possible", "hepatotoxic"], "Hepatotoxicity, endocrine effects, victim-drug toxicity"),
  d("itraconazole", "Itraconazole", ["Sporanox"], "Azole antifungal",
    [sub("CYP3A4", "major"), inh("CYP3A4", "strong"), inh("P-gp", "strong")],
    ["hepatotoxic"], "Heart failure exacerbation, victim-drug toxicity"),
  d("voriconazole", "Voriconazole", ["Vfend"], "Azole antifungal",
    [sub("CYP2C19", "major"), sub("CYP3A4", "major"), inh("CYP3A4", "strong"), inh("CYP2C9", "moderate"), inh("CYP2C19", "moderate")],
    ["qt-possible", "hepatotoxic"], "Visual disturbance, hepatotoxicity, victim-drug toxicity"),
  d("rifampin", "Rifampin", ["Rifadin"], "Rifamycin",
    [ind("CYP3A4", "strong"), ind("CYP2C9", "strong"), ind("CYP2C19", "strong"), ind("CYP2B6", "strong"), ind("CYP1A2", "moderate"), ind("CYP2C8", "moderate"), ind("P-gp", "strong")],
    ["hepatotoxic"], "Loss of victim-drug efficacy, hepatotoxicity",
    { aliases: ["rifampicin"] }),
  d("linezolid", "Linezolid", ["Zyvox"], "Oxazolidinone",
    [], ["serotonergic", "maoi"], "Serotonin syndrome, myelosuppression",
    { note: "Reversible nonselective MAO inhibition." }),
  d("tmp-smx", "Trimethoprim–sulfamethoxazole", ["Bactrim", "Septra"], "Sulfonamide antibiotic",
    [inh("CYP2C9", "moderate"), inh("CYP2C8", "moderate")],
    ["k-sparing", "nephrotoxic"], "Hyperkalemia, marrow suppression, INR rise",
    { aliases: ["bactrim", "cotrimoxazole", "sulfamethoxazole"] }),
  d("isoniazid", "Isoniazid", ["Nydrazid"], "Antimycobacterial",
    [inh("CYP2C19", "moderate"), inh("CYP3A4", "weak"), inh("CYP2D6", "weak"), inh("CYP2E1", "weak")],
    ["hepatotoxic", "seizure-lowering"], "Hepatitis, neuropathy",
    {
      aliases: ["inh"],
      note: "Latent TB is common on OTP boards. Weak 3A4 inhibition can nudge methadone; the louder stories are INH hepatitis next to alcohol, and rifampin (the other TB drug) dumping methadone and HCV DAAs.",
    }),
  d("ritonavir", "Ritonavir", ["Norvir"], "HIV protease inhibitor / booster",
    [sub("CYP3A4", "major"), inh("CYP3A4", "strong"), inh("CYP2D6", "moderate"), inh("P-gp", "strong"), ind("CYP1A2", "moderate"), ind("CYP2C9", "weak")],
    [], "Victim-drug toxicity via 3A4/P-gp"),
  d("cobicistat", "Cobicistat", ["Tybost"], "PK booster",
    [inh("CYP3A4", "strong"), inh("CYP2D6", "weak"), inh("P-gp", "strong")],
    [], "Victim-drug toxicity via 3A4",
    {
      aliases: ["tybost", "pk booster"],
      note: "The modern ritonavir-like booster in Genvoya, Prezcobix, Evotaz. Strong 3A4/P-gp inhibition raises buprenorphine and many 3A4 victims. Unlike ritonavir it does not induce 1A2/2C9.",
    }),

  // —— Cardiovascular ———————————————————————————————
  d("warfarin", "Warfarin", ["Coumadin", "Jantoven"], "Vitamin K antagonist",
    [sub("CYP2C9", "sensitive", "clearance", true), sub("CYP3A4", "minor"), sub("CYP1A2", "minor")],
    ["anticoagulant"], "Bleeding / high INR",
    { note: "S-warfarin (more potent) is a sensitive CYP2C9 substrate; R-warfarin uses 1A2/3A4." }),
  d("apixaban", "Apixaban", ["Eliquis"], "Direct oral anticoagulant",
    [sub("CYP3A4", "major"), sub("P-gp", "major")],
    ["anticoagulant"], "Bleeding or loss of anticoagulation"),
  d("rivaroxaban", "Rivaroxaban", ["Xarelto"], "Direct oral anticoagulant",
    [sub("CYP3A4", "major"), sub("P-gp", "major")],
    ["anticoagulant"], "Bleeding or loss of anticoagulation"),
  d("dabigatran", "Dabigatran", ["Pradaxa"], "Direct thrombin inhibitor",
    [sub("P-gp", "sensitive")],
    ["anticoagulant"], "Bleeding or loss of anticoagulation"),
  d("clopidogrel", "Clopidogrel", ["Plavix"], "P2Y12 inhibitor",
    [sub("CYP2C19", "sensitive", "activation"), sub("CYP3A4", "minor", "activation"), inh("CYP2C8", "moderate")],
    ["antiplatelet"], "Loss of antiplatelet effect or bleeding",
    { note: "Prodrug. Bioactivation is CYP2C19-dependent; omeprazole/esomeprazole blunt it." }),
  d("aspirin", "Aspirin", ["Bayer", "Ecotrin"], "Antiplatelet / NSAID",
    [], ["antiplatelet", "nsaid", "nephrotoxic"], "Bleeding, GI ulcer, renal injury"),
  d("atorvastatin", "Atorvastatin", ["Lipitor"], "Statin",
    [sub("CYP3A4", "major")],
    ["statin", "hepatotoxic"], "Myopathy / rhabdomyolysis"),
  d("simvastatin", "Simvastatin", ["Zocor"], "Statin",
    [sub("CYP3A4", "sensitive")],
    ["statin", "hepatotoxic"], "Myopathy / rhabdomyolysis",
    { note: "Sensitive 3A4 substrate. Strong 3A4 inhibitors are contraindicated." }),
  d("lovastatin", "Lovastatin", ["Mevacor"], "Statin",
    [sub("CYP3A4", "sensitive")],
    ["statin", "hepatotoxic"], "Myopathy / rhabdomyolysis"),
  d("rosuvastatin", "Rosuvastatin", ["Crestor"], "Statin",
    [sub("CYP2C9", "minor")],
    ["statin", "hepatotoxic"], "Myopathy / rhabdomyolysis",
    { note: "Limited CYP clearance; OATP1B1 interactions dominate." }),
  d("pravastatin", "Pravastatin", ["Pravachol"], "Statin",
    [],
    ["statin"], "Myopathy",
    { note: "Not a CYP3A4 substrate — often the switch when 3A4 is blocked." }),
  d("gemfibrozil", "Gemfibrozil", ["Lopid"], "Fibrate",
    [inh("CYP2C8", "strong"), inh("CYP2C9", "moderate")],
    ["fibrate"], "Myopathy with statins, hypoglycemia with repaglinide"),
  d("amlodipine", "Amlodipine", ["Norvasc"], "Dihydropyridine CCB",
    [sub("CYP3A4", "major")],
    [], "Hypotension, edema"),
  d("diltiazem", "Diltiazem", ["Cardizem", "Tiazac"], "Non-DHP CCB",
    [sub("CYP3A4", "major"), inh("CYP3A4", "moderate"), inh("P-gp", "moderate")],
    ["ndhp-ccb", "bradycardic"], "Bradycardia, AV block, hypotension"),
  d("verapamil", "Verapamil", ["Calan", "Isoptin"], "Non-DHP CCB",
    [sub("CYP3A4", "major"), inh("CYP3A4", "moderate"), inh("P-gp", "strong")],
    ["ndhp-ccb", "bradycardic"], "Bradycardia, AV block, hypotension"),
  d("metoprolol", "Metoprolol", ["Lopressor", "Toprol-XL"], "Beta blocker",
    [sub("CYP2D6", "major")],
    ["beta-blocker", "bradycardic"], "Bradycardia, heart block, hypotension"),
  d("carvedilol", "Carvedilol", ["Coreg"], "Beta / alpha blocker",
    [sub("CYP2D6", "major"), sub("CYP2C9", "minor")],
    ["beta-blocker", "alpha-blocker", "bradycardic"], "Bradycardia, hypotension"),
  d("propranolol", "Propranolol", ["Inderal"], "Beta blocker",
    [sub("CYP2D6", "major"), sub("CYP1A2", "major")],
    ["beta-blocker", "bradycardic"], "Bradycardia, bronchospasm"),
  d("amiodarone", "Amiodarone", ["Pacerone", "Cordarone"], "Class III antiarrhythmic",
    [sub("CYP3A4", "major"), inh("CYP3A4", "moderate"), inh("CYP2C9", "moderate"), inh("CYP2D6", "weak"), inh("CYP1A2", "moderate"), inh("P-gp", "moderate")],
    ["qt-known", "bradycardic", "hepatotoxic"], "TdP, bradycardia, thyroid/liver/lung toxicity",
    { note: "Inhibition accumulates over weeks; interactions persist after stopping." }),
  d("sotalol", "Sotalol", ["Betapace"], "Class III antiarrhythmic",
    [], ["qt-known", "beta-blocker", "bradycardic"], "TdP, bradycardia"),
  d("digoxin", "Digoxin", ["Lanoxin"], "Cardiac glycoside",
    [sub("P-gp", "sensitive", "clearance", true)],
    ["bradycardic"], "Digoxin toxicity (nausea, arrhythmia, visual change)",
    { note: "Narrow index. P-gp inhibitors (amiodarone, verapamil, clarithromycin) raise levels." }),
  d("lisinopril", "Lisinopril", ["Prinivil", "Zestril"], "ACE inhibitor",
    [], ["acei-arb", "nephrotoxic"], "Hyperkalemia, acute kidney injury, angioedema"),
  d("losartan", "Losartan", ["Cozaar"], "ARB",
    [sub("CYP2C9", "major", "activation"), sub("CYP3A4", "minor")],
    ["acei-arb", "nephrotoxic"], "Hyperkalemia, acute kidney injury"),
  d("spironolactone", "Spironolactone", ["Aldactone"], "Mineralocorticoid antagonist",
    [], ["k-sparing"], "Hyperkalemia, gynecomastia"),
  d("furosemide", "Furosemide", ["Lasix"], "Loop diuretic",
    [], ["loop-thiazide", "nephrotoxic"], "Volume depletion, AKI, electrolyte loss"),
  d("hctz", "Hydrochlorothiazide", ["Microzide"], "Thiazide diuretic",
    [], ["loop-thiazide"], "Hyponatremia, hypokalemia, gout",
    { aliases: ["hydrochlorothiazide"] }),
  d("tamsulosin", "Tamsulosin", ["Flomax"], "Alpha-1 blocker",
    [sub("CYP3A4", "major"), sub("CYP2D6", "major")],
    ["alpha-blocker"], "Orthostatic hypotension"),

  // —— Psychiatry ——————————————————————————————————
  d("sertraline", "Sertraline", ["Zoloft"], "SSRI",
    [sub("CYP2C19", "major"), sub("CYP3A4", "minor"), inh("CYP2D6", "weak")],
    ["serotonergic", "ssri-snri"], "Serotonin syndrome, bleeding, hyponatremia"),
  d("fluoxetine", "Fluoxetine", ["Prozac"], "SSRI",
    [sub("CYP2D6", "major"), inh("CYP2D6", "strong"), inh("CYP2C19", "moderate"), inh("CYP3A4", "weak")],
    ["serotonergic", "ssri-snri", "seizure-lowering"], "Serotonin syndrome, bleeding; long-lived inhibition",
    { note: "Norfluoxetine prolongs 2D6 inhibition for weeks after stopping." }),
  d("paroxetine", "Paroxetine", ["Paxil"], "SSRI",
    [sub("CYP2D6", "major"), inh("CYP2D6", "strong")],
    ["serotonergic", "ssri-snri", "anticholinergic"], "Serotonin syndrome, discontinuation syndrome"),
  d("fluvoxamine", "Fluvoxamine", ["Luvox"], "SSRI",
    [sub("CYP2D6", "minor"), inh("CYP1A2", "strong"), inh("CYP2C19", "strong"), inh("CYP3A4", "moderate")],
    ["serotonergic", "ssri-snri"], "Serotonin syndrome; marked 1A2/2C19 perpetrator"),
  d("citalopram", "Citalopram", ["Celexa"], "SSRI",
    [sub("CYP2C19", "major"), sub("CYP3A4", "major"), sub("CYP2D6", "minor")],
    ["serotonergic", "ssri-snri", "qt-known"], "QT prolongation, serotonin syndrome"),
  d("escitalopram", "Escitalopram", ["Lexapro"], "SSRI",
    [sub("CYP2C19", "major"), sub("CYP3A4", "major")],
    ["serotonergic", "ssri-snri", "qt-possible"], "QT prolongation, serotonin syndrome"),
  d("venlafaxine", "Venlafaxine", ["Effexor"], "SNRI",
    [sub("CYP2D6", "major"), sub("CYP3A4", "minor")],
    ["serotonergic", "ssri-snri"], "Serotonin syndrome, hypertension"),
  d("duloxetine", "Duloxetine", ["Cymbalta"], "SNRI",
    [sub("CYP1A2", "major"), sub("CYP2D6", "major"), inh("CYP2D6", "moderate")],
    ["serotonergic", "ssri-snri", "hepatotoxic"], "Serotonin syndrome, hepatotoxicity"),
  d("bupropion", "Bupropion", ["Wellbutrin", "Zyban"], "NDRI antidepressant",
    [sub("CYP2B6", "major"), inh("CYP2D6", "strong")],
    ["seizure-lowering"], "Seizures, 2D6 victim-drug toxicity"),
  d("mirtazapine", "Mirtazapine", ["Remeron"], "NaSSA antidepressant",
    [sub("CYP3A4", "major"), sub("CYP2D6", "minor"), sub("CYP1A2", "minor")],
    ["serotonergic", "cns-depressant"], "Sedation, serotonin syndrome (lower risk)"),
  d("trazodone", "Trazodone", ["Desyrel"], "SARI antidepressant",
    [sub("CYP3A4", "major")],
    ["serotonergic", "cns-depressant", "qt-possible"], "Sedation, priapism, serotonin syndrome"),
  d("amitriptyline", "Amitriptyline", ["Elavil"], "Tricyclic antidepressant",
    [sub("CYP2D6", "major"), sub("CYP2C19", "major"), sub("CYP3A4", "minor")],
    ["serotonergic", "cns-depressant", "anticholinergic", "qt-possible", "seizure-lowering"],
    "Anticholinergic toxicity, arrhythmia, seizures"),
  d("nortriptyline", "Nortriptyline", ["Pamelor"], "Tricyclic antidepressant",
    [sub("CYP2D6", "sensitive", "clearance", true)],
    ["serotonergic", "cns-depressant", "anticholinergic", "qt-possible"],
    "TCA toxicity, arrhythmia"),
  d("lithium", "Lithium", ["Lithobid"], "Mood stabilizer",
    [], ["serotonergic", "seizure-lowering", "nephrotoxic"], "Lithium toxicity (narrow index)",
    { note: "Renally cleared, not CYP. NSAIDs, ACE inhibitors, and thiazides raise levels." }),
  d("quetiapine", "Quetiapine", ["Seroquel"], "Atypical antipsychotic",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant", "qt-possible", "anticholinergic"], "Sedation, QT, hypotension"),
  d("olanzapine", "Olanzapine", ["Zyprexa"], "Atypical antipsychotic",
    [sub("CYP1A2", "major")],
    ["cns-depressant", "anticholinergic"], "Sedation, metabolic syndrome",
    { note: "Smoking induces 1A2 and can drop levels; cessation raises them." }),
  d("risperidone", "Risperidone", ["Risperdal"], "Atypical antipsychotic",
    [sub("CYP2D6", "major"), sub("CYP3A4", "minor")],
    ["cns-depressant", "qt-possible"], "EPS, hyperprolactinemia, QT"),
  d("aripiprazole", "Aripiprazole", ["Abilify"], "Atypical antipsychotic",
    [sub("CYP2D6", "major"), sub("CYP3A4", "major")],
    [], "Akathisia, impulse-control effects"),
  d("clozapine", "Clozapine", ["Clozaril"], "Atypical antipsychotic",
    [sub("CYP1A2", "sensitive", "clearance", true), sub("CYP3A4", "minor"), sub("CYP2C19", "minor")],
    ["cns-depressant", "anticholinergic", "seizure-lowering", "qt-possible"],
    "Agranulocytosis, seizures, myocarditis, constipation",
    { note: "Sensitive 1A2 substrate. Fluvoxamine and ciprofloxacin can spike levels." }),
  d("haloperidol", "Haloperidol", ["Haldol"], "Typical antipsychotic",
    [sub("CYP3A4", "major"), sub("CYP2D6", "major"), inh("CYP2D6", "moderate")],
    ["cns-depressant", "qt-known", "seizure-lowering"], "EPS, TdP, NMS"),
  d("ziprasidone", "Ziprasidone", ["Geodon"], "Atypical antipsychotic",
    [sub("CYP3A4", "minor")],
    ["cns-depressant", "qt-known"], "TdP"),
  d("alprazolam", "Alprazolam", ["Xanax"], "Benzodiazepine",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant", "benzo-zdrug"], "Sedation, respiratory depression, falls"),
  d("diazepam", "Diazepam", ["Valium"], "Benzodiazepine",
    [sub("CYP3A4", "major"), sub("CYP2C19", "major")],
    ["cns-depressant", "benzo-zdrug"], "Sedation, prolonged accumulation"),
  d("clonazepam", "Clonazepam", ["Klonopin"], "Benzodiazepine",
    [sub("CYP3A4", "major")],
    ["cns-depressant", "benzo-zdrug"], "Sedation, respiratory depression"),
  d("lorazepam", "Lorazepam", ["Ativan"], "Benzodiazepine",
    [],
    ["cns-depressant", "benzo-zdrug"], "Sedation, respiratory depression",
    { note: "UGT-glucuronidated, not a CYP substrate — often preferred when CYPs are blocked." }),
  d("midazolam", "Midazolam", ["Versed"], "Benzodiazepine",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant", "benzo-zdrug"], "Profound sedation, respiratory depression"),
  d("zolpidem", "Zolpidem", ["Ambien"], "Z-hypnotic",
    [sub("CYP3A4", "major")],
    ["cns-depressant", "benzo-zdrug"], "Complex sleep behavior, falls"),
  d("buspirone", "Buspirone", ["BuSpar"], "Anxiolytic",
    [sub("CYP3A4", "sensitive")],
    ["serotonergic"], "Serotonin syndrome (with other serotonergics), dizziness"),
  d("phenelzine", "Phenelzine", ["Nardil"], "Irreversible MAOI",
    [inh("CYP2C19", "moderate")],
    ["maoi", "serotonergic"], "Hypertensive crisis, serotonin syndrome",
    { note: "Irreversible MAO-A/B inhibitor. Serotonergic drugs and tyramine are contraindicated." }),
  d("selegiline", "Selegiline", ["Emsam", "Eldepryl"], "MAO-B inhibitor",
    [sub("CYP2B6", "major"), sub("CYP2C19", "minor")],
    ["maoi", "serotonergic"], "Serotonin syndrome, hypertensive crisis at higher doses"),

  // —— Pain / neuro —————————————————————————————————
  d("codeine", "Codeine", [], "Opioid analgesic (prodrug)",
    [sub("CYP2D6", "sensitive", "activation"), sub("CYP3A4", "minor")],
    ["opioid", "cns-depressant"], "Loss of analgesia or morphine toxicity (UM phenotype)",
    { note: "Prodrug. CYP2D6 O-demethylation produces morphine; inhibitors blunt analgesia." }),
  d("tramadol", "Tramadol", ["Ultram"], "Opioid / SNRI analgesic",
    [sub("CYP2D6", "major", "activation"), sub("CYP3A4", "major")],
    ["opioid", "cns-depressant", "serotonergic", "seizure-lowering"],
    "Seizures, serotonin syndrome, respiratory depression"),
  d("oxycodone", "Oxycodone", ["OxyContin", "Percocet", "Roxicodone", "Endocet"], "Opioid analgesic",
    [sub("CYP3A4", "major"), sub("CYP2D6", "minor")],
    ["opioid", "cns-depressant"], "Respiratory depression, sedation",
    {
      aliases: ["percs", "perc", "perc 30", "roxi", "oxy"],
      note: "Percocet is oxycodone plus acetaminophen — put APAP on the desk for the 2E1/alcohol story. Street 'perc 30s' stamped M30 are often pressed fentanyl, not this row. Search dirty 30.",
    }),
  d("hydrocodone", "Hydrocodone", ["Norco", "Vicodin"], "Opioid analgesic",
    [sub("CYP3A4", "major"), sub("CYP2D6", "minor", "activation")],
    ["opioid", "cns-depressant"], "Respiratory depression, sedation"),
  d("morphine", "Morphine", ["MS Contin"], "Opioid analgesic",
    [sub("P-gp", "minor")],
    ["opioid", "cns-depressant"], "Respiratory depression, sedation",
    { note: "UGT2B7, not CYP. PD synergies still apply." }),
  d("fentanyl", "Fentanyl", ["Duragesic", "Sublimaze"], "Opioid analgesic",
    [sub("CYP3A4", "sensitive")],
    ["opioid", "cns-depressant", "serotonergic"], "Respiratory depression"),
  d("methadone", "Methadone", ["Dolophine", "Methadose"], "Opioid agonist",
    [sub("CYP3A4", "major"), sub("CYP2B6", "major"), sub("CYP2C19", "minor"), sub("CYP1A2", "minor")],
    ["opioid", "cns-depressant", "qt-known", "serotonergic"], "TdP, respiratory depression",
    {
      aliases: ["methadose", "diskets"],
      note: "Long t½ — q24h accumulates. 3A4/2B6 inducers (rifampin, carbamazepine, efavirenz) look like a stolen dose. Inhibitors and other QT drugs (citalopram, quetiapine, ondansetron) raise TdP risk. Boxed warning with benzos and gabapentinoids.",
    }),
  d("gabapentin", "Gabapentin", ["Neurontin"], "Gabapentinoid",
    [], ["cns-depressant"], "Sedation, respiratory depression with opioids"),
  d("pregabalin", "Pregabalin", ["Lyrica"], "Gabapentinoid",
    [], ["cns-depressant"], "Sedation, respiratory depression with opioids"),
  d("carbamazepine", "Carbamazepine", ["Tegretol"], "Anticonvulsant",
    [sub("CYP3A4", "major"), ind("CYP3A4", "strong"), ind("CYP2C9", "moderate"), ind("CYP2C19", "moderate"), ind("CYP1A2", "moderate"), ind("P-gp", "moderate")],
    ["cns-depressant", "anticholinergic", "seizure-lowering"], "Loss of victim-drug efficacy, hyponatremia, SJS",
    { note: "Autoinducer. Strong 3A4 inducer after ~2–3 weeks." }),
  d("phenytoin", "Phenytoin", ["Dilantin"], "Anticonvulsant",
    [sub("CYP2C9", "sensitive", "clearance", true), sub("CYP2C19", "major"), ind("CYP3A4", "strong"), ind("CYP2C19", "moderate"), ind("P-gp", "moderate")],
    ["cns-depressant", "hepatotoxic"], "Phenytoin toxicity or loss of co-drug efficacy",
    { note: "Narrow index, nonlinear kinetics." }),
  d("valproate", "Valproate", ["Depakote", "Depakene"], "Anticonvulsant",
    [inh("CYP2C9", "weak")],
    ["cns-depressant", "hepatotoxic", "seizure-lowering"], "Hyperammonemia, hepatotoxicity, teratogenicity",
    { aliases: ["valproic acid", "divalproex"] }),
  d("lamotrigine", "Lamotrigine", ["Lamictal"], "Anticonvulsant",
    [], ["cns-depressant"], "SJS/TEN (with valproate), dizziness",
    { note: "UGT1A4, not CYP. Valproate doubles levels; inducers drop them." }),
  d("levetiracetam", "Levetiracetam", ["Keppra"], "Anticonvulsant",
    [], ["cns-depressant"], "Mood change, sedation",
    { note: "Renally cleared. Almost no CYP interactions." }),
  d("tizanidine", "Tizanidine", ["Zanaflex"], "Central muscle relaxant",
    [sub("CYP1A2", "sensitive", "clearance", true)],
    ["cns-depressant", "bradycardic"], "Profound hypotension, bradycardia, sedation",
    { note: "Sensitive 1A2 substrate. Ciprofloxacin and fluvoxamine are contraindicated." }),
  d("cyclobenzaprine", "Cyclobenzaprine", ["Flexeril"], "Muscle relaxant",
    [sub("CYP3A4", "major"), sub("CYP1A2", "major"), sub("CYP2D6", "minor")],
    ["cns-depressant", "anticholinergic", "serotonergic"], "Sedation, serotonin syndrome"),
  d("donepezil", "Donepezil", ["Aricept"], "AChE inhibitor",
    [sub("CYP2D6", "major"), sub("CYP3A4", "major")],
    ["bradycardic"], "Bradycardia, syncope, GI upset"),

  // —— GI / endocrine / immuno / other ———————————————
  d("omeprazole", "Omeprazole", ["Prilosec"], "PPI",
    [sub("CYP2C19", "major"), inh("CYP2C19", "moderate"), inh("CYP3A4", "weak")],
    [], "Reduced clopidogrel activation, B12/Mg loss"),
  d("esomeprazole", "Esomeprazole", ["Nexium"], "PPI",
    [sub("CYP2C19", "major"), inh("CYP2C19", "moderate")],
    [], "Reduced clopidogrel activation"),
  d("pantoprazole", "Pantoprazole", ["Protonix"], "PPI",
    [sub("CYP2C19", "minor")],
    [], "Hypomagnesemia",
    { note: "Weaker 2C19 inhibition — often preferred with clopidogrel." }),
  d("metformin", "Metformin", ["Glucophage"], "Biguanide",
    [], ["hypoglycemic"], "Lactic acidosis (rare), GI upset",
    { note: "OCT/MATE, not CYP." }),
  d("glipizide", "Glipizide", ["Glucotrol"], "Sulfonylurea",
    [sub("CYP2C9", "major")],
    ["hypoglycemic", "insulin-secretagogue"], "Hypoglycemia"),
  d("glyburide", "Glyburide", ["Diabeta", "Micronase"], "Sulfonylurea",
    [sub("CYP2C9", "major"), sub("CYP3A4", "minor")],
    ["hypoglycemic", "insulin-secretagogue"], "Hypoglycemia"),
  d("repaglinide", "Repaglinide", ["Prandin"], "Meglitinide",
    [sub("CYP2C8", "sensitive"), sub("CYP3A4", "major")],
    ["hypoglycemic", "insulin-secretagogue"], "Severe hypoglycemia",
    { note: "Gemfibrozil is contraindicated (CYP2C8 + OATP)." }),
  d("insulin-glargine", "Insulin glargine", ["Lantus", "Basaglar", "Toujeo"], "Long-acting insulin",
    [], ["hypoglycemic"], "Hypoglycemia"),
  d("levothyroxine", "Levothyroxine", ["Synthroid", "Levoxyl"], "Thyroid hormone",
    [], [], "Iatrogenic hyper/hypothyroidism",
    { note: "Absorption interactions (iron, calcium, PPIs) dominate over CYP." }),
  d("prednisone", "Prednisone", ["Deltasone"], "Corticosteroid",
    [sub("CYP3A4", "minor")],
    [], "Hyperglycemia, immunosuppression"),
  d("tacrolimus", "Tacrolimus", ["Prograf"], "Calcineurin inhibitor",
    [sub("CYP3A4", "sensitive", "clearance", true), sub("P-gp", "major")],
    ["immunosuppressant", "nephrotoxic", "seizure-lowering"], "Nephrotoxicity, neurotoxicity, infection",
    { note: "Narrow index. Strong 3A4 inhibitors can multiply AUC." }),
  d("cyclosporine", "Cyclosporine", ["Neoral", "Sandimmune", "Gengraf"], "Calcineurin inhibitor",
    [sub("CYP3A4", "sensitive", "clearance", true), sub("P-gp", "major"), inh("CYP3A4", "moderate"), inh("P-gp", "moderate")],
    ["immunosuppressant", "nephrotoxic"], "Nephrotoxicity, infection"),
  d("methotrexate", "Methotrexate", ["Trexall", "Rheumatrex"], "Antimetabolite",
    [], ["nephrotoxic", "hepatotoxic"], "Marrow suppression, mucositis, AKI",
    { note: "NSAIDs and TMP-SMX raise toxicity via renal/transporter effects." }),
  d("colchicine", "Colchicine", ["Colcrys", "Mitigare"], "Antigout",
    [sub("CYP3A4", "sensitive", "clearance", true), sub("P-gp", "sensitive")],
    [], "Myelosuppression, myopathy, GI toxicity",
    { note: "Contraindicated with strong 3A4/P-gp inhibitors in renal/hepatic impairment." }),
  d("allopurinol", "Allopurinol", ["Zyloprim"], "Xanthine oxidase inhibitor",
    [], [], "SJS/TEN (HLA-B*5801), marrow suppression with azathioprine"),
  d("sildenafil", "Sildenafil", ["Viagra", "Revatio"], "PDE5 inhibitor",
    [sub("CYP3A4", "major")],
    ["pde5"], "Severe hypotension with nitrates"),
  d("tadalafil", "Tadalafil", ["Cialis", "Adcirca"], "PDE5 inhibitor",
    [sub("CYP3A4", "major")],
    ["pde5"], "Severe hypotension with nitrates"),
  d("nitroglycerin", "Nitroglycerin", ["Nitrostat", "Nitro-Dur"], "Nitrate",
    [], ["nitrate"], "Catastrophic hypotension with PDE5 inhibitors"),
  d("ondansetron", "Ondansetron", ["Zofran"], "5-HT3 antagonist",
    [sub("CYP3A4", "major"), sub("CYP1A2", "minor"), sub("CYP2D6", "minor")],
    ["qt-known", "serotonergic"], "QT prolongation"),
  d("diphenhydramine", "Diphenhydramine", ["Benadryl"], "First-generation antihistamine",
    [sub("CYP2D6", "minor"), inh("CYP2D6", "weak")],
    ["cns-depressant", "anticholinergic"], "Sedation, delirium, urinary retention"),
  d("acetaminophen", "Acetaminophen", ["Tylenol", "Paracetamol"], "Analgesic / antipyretic",
    [sub("CYP2E1", "major", "activation"), sub("CYP1A2", "minor"), sub("CYP3A4", "minor")],
    ["hepatotoxic"], "Hepatotoxicity in overdose or with 2E1 induction (chronic alcohol)",
    {
      aliases: ["paracetamol", "apap"],
      note: "CYP2E1 activation to NAPQI. Chronic drinking induces 2E1 and depletes glutathione — the classic delayed-hepatotoxicity pattern.",
    }),
  d("ibuprofen", "Ibuprofen", ["Advil", "Motrin"], "NSAID",
    [sub("CYP2C9", "major")],
    ["nsaid", "nephrotoxic"], "GI bleed, AKI, attenuated antiplatelet effect of aspirin"),
  d("naproxen", "Naproxen", ["Aleve", "Naprosyn"], "NSAID",
    [sub("CYP2C9", "minor"), sub("CYP1A2", "minor")],
    ["nsaid", "nephrotoxic"], "GI bleed, AKI"),
  d("celecoxib", "Celecoxib", ["Celebrex"], "COX-2 inhibitor",
    [sub("CYP2C9", "major"), inh("CYP2D6", "weak")],
    ["nsaid", "nephrotoxic"], "CV risk, AKI, attenuated but present bleeding risk"),
  d("theophylline", "Theophylline", ["Theo-24", "Uniphyl"], "Methylxanthine",
    [sub("CYP1A2", "sensitive", "clearance", true)],
    ["seizure-lowering"], "Tachyarrhythmia, seizures",
    { note: "Narrow index. Ciprofloxacin and fluvoxamine can double levels." }),
  d("tamoxifen", "Tamoxifen", ["Nolvadex", "Soltamox"], "SERM",
    [sub("CYP2D6", "sensitive", "activation"), sub("CYP3A4", "major"), sub("CYP2C9", "minor")],
    [], "Loss of endoxifen (efficacy) if 2D6 is blocked",
    { note: "Prodrug. Strong 2D6 inhibitors (paroxetine, fluoxetine, bupropion) are avoided." }),
  d("ethinyl-estradiol", "Ethinyl estradiol (OCP)", ["Yaz", "Ortho Tri-Cyclen", "Loestrin"], "Estrogen contraceptive",
    [sub("CYP3A4", "major")],
    [], "Contraceptive failure with inducers",
    { aliases: ["oral contraceptive", "birth control", "ocp"] }),
  d("grapefruit", "Grapefruit juice", [], "Furanocoumarin (intestinal CYP3A4)",
    [inh("CYP3A4", "strong"), inh("P-gp", "moderate")],
    [], "Raised oral 3A4-victim exposure for 24–72 h",
    {
      kind: "food",
      aliases: ["grapefruit", "gfj", "pomelo", "seville orange", "bergamottin"],
      note: "Mechanism-based intestinal CYP3A4 knockout. Hepatic 3A4 is largely spared — IV ketamine barely moves; oral ketamine, buspirone, and quetiapine do.",
    }),
  d("caffeine", "Caffeine", [], "Methylxanthine",
    [sub("CYP1A2", "sensitive")],
    [], "Jitteriness, insomnia, tachycardia"),
  d("lurasidone", "Lurasidone", ["Latuda"], "Atypical antipsychotic",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant"], "Sedation, akathisia",
    { note: "Contraindicated with strong CYP3A4 inhibitors and inducers." }),

  // —— Dissociatives / NMDA ————————————————————————
  d("ketamine", "Ketamine", ["Ketalar"], "NMDA dissociative anesthetic",
    [sub("CYP2B6", "major"), sub("CYP3A4", "major"), sub("CYP2C9", "minor")],
    ["dissociative", "cns-depressant", "seizure-lowering"],
    "Respiratory depression, emergence reactions, blood-pressure swings, cystitis with chronic exposure",
    {
      aliases: ["ketalar", "racemic ketamine"],
      note: "Norketamine via CYP2B6 (major) and CYP3A4. Strong 3A4 inhibitors raise exposure; GABA-ergic drugs add airway risk and can blunt antidepressant response.",
    }),
  d("esketamine", "Esketamine", ["Spravato"], "NMDA dissociative (S-ketamine)",
    [sub("CYP2B6", "major"), sub("CYP3A4", "major"), sub("CYP2C9", "minor")],
    ["dissociative", "cns-depressant", "seizure-lowering"],
    "Sedation, dissociation, hypertension, respiratory depression with CNS depressants",
    {
      aliases: ["spravato"],
      note: "S-enantiomer of ketamine. Same 2B6/3A4 map. Label warns against other CNS depressants including benzodiazepines and alcohol.",
    }),
  d("dextromethorphan", "Dextromethorphan", ["Delsym", "Robitussin DM"], "NMDA antitussive / dissociative",
    [sub("CYP2D6", "sensitive"), sub("CYP3A4", "minor")],
    ["dissociative", "serotonergic", "cns-depressant", "seizure-lowering"],
    "Serotonin syndrome, dissociation, sedation",
    {
      aliases: ["dxm"],
      note: "Sensitive CYP2D6 substrate. 2D6 poor metabolizers or strong inhibitors (paroxetine, fluoxetine, bupropion) raise exposure sharply. Serotonergic at therapeutic and supra-therapeutic doses.",
    }),
  d("memantine", "Memantine", ["Namenda"], "NMDA antagonist",
    [],
    ["dissociative"],
    "Confusion, dizziness",
    { note: "Renally cleared (OCT2), not a CYP substrate. PD overlap with other NMDA drugs is modest." }),

  // —— Entactogens / stimulants ——————————————————————
  d("mdma", "MDMA", [], "Entactogen / stimulant",
    [sub("CYP2D6", "major"), inh("CYP2D6", "moderate"), sub("CYP1A2", "minor"), sub("CYP3A4", "minor")],
    ["serotonergic", "stimulant", "seizure-lowering"],
    "Hyperthermia, serotonin syndrome, hyponatremia, hypertensive crisis with MAOIs",
    {
      aliases: ["midomafetamine", "3,4-methylenedioxymethamphetamine"],
      note: "CYP2D6 demethylenation plus mechanism-based 2D6 inhibition after the first pass. Strong 2D6 inhibitors blunt the effect and raise parent exposure. MAOIs are contraindicated.",
    }),
  d("amphetamine", "Amphetamine", ["Adderall", "Evekeo"], "Amphetamine stimulant",
    [sub("CYP2D6", "minor")],
    ["stimulant", "seizure-lowering"],
    "Hypertension, tachycardia, psychosis, MAOI hypertensive crisis",
    { aliases: ["adderall", "dextroamphetamine"] }),
  d("lisdexamfetamine", "Lisdexamfetamine", ["Vyvanse"], "Amphetamine prodrug",
    [],
    ["stimulant", "seizure-lowering"],
    "Hypertension, tachycardia, MAOI hypertensive crisis",
    { note: "Hydrolyzed to d-amphetamine (not CYP). Interactions are PD with MAOIs and other stimulants." }),
  d("methylphenidate", "Methylphenidate", ["Ritalin", "Concerta", "Daytrana"], "NDRI stimulant",
    [inh("CYP2D6", "weak")],
    ["stimulant"],
    "Hypertension, tachycardia, MAOI hypertensive crisis",
    { aliases: ["concerta", "ritalin"], note: "CES1, not a major CYP substrate." }),
  d("methamphetamine", "Methamphetamine", ["Desoxyn"], "Amphetamine stimulant",
    [sub("CYP2D6", "major")],
    ["stimulant", "seizure-lowering"],
    "Hypertensive crisis, hyperthermia, cardiotoxicity",
    { aliases: ["desoxyn", "meth", "crystal", "ice", "shard", "crystal meth"] }),
  d("cocaine", "Cocaine", [], "Local anesthetic / stimulant",
    [sub("CYP3A4", "minor")],
    ["stimulant", "qt-possible", "seizure-lowering", "hepatotoxic"],
    "Arrhythmia, seizure, hyperthermia, cocaethylene with ethanol",
    {
      aliases: ["crack", "coke", "blow", "snow", "powder"],
      note: "Mostly CES1 hydrolysis. CYP3A4 makes norcocaine. Ethanol forms cocaethylene — longer-lived and more cardiotoxic. Smoked crack skips first-pass; the PD map (speedball, MAOI, QT) does not. Pair with an opioid for the speedball finding.",
    }),
  d("heroin", "Heroin", [], "Diacetylmorphine",
    [sub("P-gp", "minor")],
    ["opioid", "cns-depressant"],
    "Respiratory depression, pulmonary edema",
    {
      aliases: ["diamorphine", "dope", "smack", "tar", "china white", "brown"],
      note: "Rapidly deacetylated to 6-MAM then morphine. Not a CYP victim. Speedball with cocaine is PD — the stimulant masks apnea. Same μ map as morphine once it converts.",
    }),
  d("modafinil", "Modafinil", ["Provigil"], "Wake-promoting agent",
    [sub("CYP3A4", "major"), inh("CYP2C19", "moderate"), ind("CYP3A4", "moderate")],
    ["stimulant"],
    "Loss of 3A4-victim efficacy (OCPs), 2C19 victim toxicity",
    { note: "Moderate 3A4 inducer and 2C19 inhibitor. Can fail oral contraceptives." }),
  d("armodafinil", "Armodafinil", ["Nuvigil"], "Wake-promoting agent",
    [sub("CYP3A4", "major"), inh("CYP2C19", "moderate"), ind("CYP3A4", "moderate")],
    ["stimulant"],
    "Loss of 3A4-victim efficacy, 2C19 victim toxicity"),
  d("atomoxetine", "Atomoxetine", ["Strattera"], "NRI (ADHD)",
    [sub("CYP2D6", "sensitive", "clearance", true)],
    ["seizure-lowering"],
    "Hypertension, suicidality warning, 2D6 victim toxicity",
    { note: "Sensitive CYP2D6 substrate. Strong 2D6 inhibitors require dose reduction." }),
  d("nicotine", "Nicotine", ["Nicorette", "Nicoderm"], "Nicotine agonist",
    [sub("CYP2B6", "minor"), ind("CYP1A2", "moderate")],
    ["stimulant"],
    "Tachycardia; smoking-induced 1A2 drops clozapine/olanzapine/theophylline",
    { note: "Combustion PAHs, not nicotine itself, drive most 1A2 induction. Cessation can spike 1A2 victims." }),

  // —— Classic psychedelics ————————————————————————
  d("psilocybin", "Psilocybin", [], "Tryptamine psychedelic",
    [],
    ["serotonergic", "psychedelic", "seizure-lowering"],
    "Serotonin syndrome with MAOIs; seizure risk with lithium",
    {
      aliases: ["psilocin"],
      note: "Dephosphorylated to psilocin; then MAO-A and UGT1A10 — not a CYP substrate. Lithium combinations have been linked to seizures.",
    }),
  d("lsd", "LSD", [], "Ergoline psychedelic",
    [],
    ["serotonergic", "psychedelic", "seizure-lowering"],
    "Serotonin syndrome with MAOIs; seizure risk with lithium",
    {
      aliases: ["lysergide", "lysergic acid diethylamide"],
      note: "Negligible CYP clearance. PD collisions dominate: MAOIs, other serotonergics, lithium.",
    }),
  d("dmt", "DMT", [], "Tryptamine psychedelic",
    [],
    ["serotonergic", "psychedelic"],
    "Hypertensive crisis / serotonin syndrome with pharmaceutical MAOIs",
    {
      aliases: ["n,n-dmt", "dimethyltryptamine"],
      note: "MAO-A in gut destroys oral DMT. Pharmaceutical MAOIs plus DMT are not the same as a supervised ayahuasca setting — pressor and serotonin risk is high.",
    }),
  d("mescaline", "Mescaline", [], "Phenethylamine psychedelic",
    [],
    ["serotonergic", "psychedelic", "seizure-lowering"],
    "Serotonin syndrome with MAOIs",
    { note: "MAO and some CYP2D6 contribution. PD with MAOIs and lithium matters more than CYP." }),

  // —— Cannabinoids ———————————————————————————————
  d("dronabinol", "Dronabinol (THC)", ["Marinol", "Syndros"], "Cannabinoid (THC)",
    [sub("CYP2C9", "major"), sub("CYP3A4", "major")],
    ["cannabinoid", "cns-depressant"],
    "Sedation, tachycardia, 2C9/3A4 victim toxicity",
    { aliases: ["thc", "delta-9-thc", "cannabis"] }),
  d("cannabidiol", "Cannabidiol", ["Epidiolex"], "Cannabinoid (CBD)",
    [sub("CYP2C19", "major"), sub("CYP3A4", "major"), inh("CYP2C19", "strong"), inh("CYP3A4", "moderate"), inh("CYP2C9", "moderate"), inh("CYP2D6", "weak")],
    ["cannabinoid", "cns-depressant", "hepatotoxic"],
    "Somnolence, transaminase rise, victim-drug toxicity (clobazam, diazepam, warfarin)",
    {
      aliases: ["cbd", "epidiolex"],
      note: "Strong CYP2C19 inhibitor — a major perpetrator for diazepam, clobazam, and citalopram.",
    }),

  // —— Alcohol / GABA / MAT —————————————————————————
  d("ethanol", "Ethanol", [], "Alcohol",
    [sub("CYP2E1", "major"), ind("CYP2E1", "moderate")],
    ["alcohol", "cns-depressant", "hepatotoxic", "seizure-lowering"],
    "Respiratory depression with other CNS drugs, hepatotoxicity, cocaethylene with cocaine",
    {
      aliases: ["alcohol", "etoh"],
      note: "Chronic use induces CYP2E1 (and, via lifestyle, other pathways). Acute use is a CNS depressant. Never stack with GHB, opioids, or benzodiazepines.",
    }),
  d("sodium-oxybate", "Sodium oxybate", ["Xyrem", "Lumryz"], "GHB (GABA-B)",
    [],
    ["ghb", "cns-depressant"],
    "Profound respiratory depression, coma",
    {
      aliases: ["ghb", "xyrem", "gamma hydroxybutyrate"],
      note: "Contraindicated with alcohol and other CNS depressants. Not a CYP substrate.",
    }),
  d("phenibut", "Phenibut", [], "GABA-B analogue",
    [],
    ["cns-depressant"],
    "Sedation, withdrawal seizures when stacked then stopped",
    { note: "Not a CYP substrate. PD with alcohol, benzos, GHB, and opioids." }),
  d("baclofen", "Baclofen", ["Lioresal"], "GABA-B agonist",
    [],
    ["cns-depressant"],
    "Sedation, respiratory depression with other CNS drugs"),
  d("eszopiclone", "Eszopiclone", ["Lunesta"], "Z-hypnotic",
    [sub("CYP3A4", "major")],
    ["cns-depressant", "benzo-zdrug"],
    "Sedation, complex sleep behavior"),
  d("ramelteon", "Ramelteon", ["Rozerem"], "Melatonin-receptor hypnotic",
    [sub("CYP1A2", "sensitive")],
    ["cns-depressant"],
    "Sedation; fluvoxamine is contraindicated",
    { note: "Sensitive CYP1A2 substrate. Fluvoxamine (strong 1A2 inhibitor) is labeled contraindicated." }),
  d("suvorexant", "Suvorexant", ["Belsomra"], "Orexin antagonist",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant"],
    "Sedation, next-day impairment",
    { note: "Sensitive 3A4 substrate. Strong 3A4 inhibitors are not recommended." }),
  d("melatonin", "Melatonin", [], "Pineal hormone",
    [sub("CYP1A2", "sensitive")],
    ["cns-depressant"],
    "Sedation; 1A2 inhibitors raise exposure"),
  d("buprenorphine", "Buprenorphine", ["Suboxone", "Subutex", "Butrans", "Sublocade", "Zubsolv", "Brixadi"], "Partial opioid agonist",
    [sub("CYP3A4", "major"), sub("CYP2C8", "minor")],
    ["opioid", "cns-depressant", "partial-opioid"],
    "Respiratory depression with benzos/alcohol; precipitated withdrawal with full agonists",
    {
      aliases: ["suboxone", "subutex", "zubsolv", "bunavail", "belbuca", "buprenex", "brixadi"],
      note: "High-affinity partial μ-agonist. On a fentanyl or methadone load it precipitates withdrawal — the classic failed induction. Stable bup then a full agonist (7-OH, fentanyl) blocks the high. 3A4 inhibitors (ritonavir, cobicistat, azoles) raise parent. Street benzos and gabapentinoids still hit the airway. Naloxone in Suboxone is poorly absorbed under the tongue; it is not a second opioid on this desk unless injected.",
    }),
  d("naltrexone", "Naltrexone", ["ReVia", "Vivitrol", "Contrave"], "Opioid antagonist",
    [],
    ["opioid-antagonist"],
    "Precipitated opioid withdrawal; blocks opioid analgesia",
    {
      aliases: ["vivitrol", "revia"],
      note: "Not a CYP substrate. IM naltrexone occupies μ for weeks. Leftover fentanyl or a 'just this once' agonist is precipitated withdrawal, not a slip that didn't work. Also used for alcohol use disorder next to acamprosate.",
    }),
  d("naloxone", "Naloxone", ["Narcan", "Kloxxado"], "Opioid antagonist",
    [],
    ["opioid-antagonist"],
    "Precipitated opioid withdrawal",
    { aliases: ["narcan"] }),
  d("kratom", "Kratom (mitragynine)", [], "Atypical opioid / stimulant",
    [sub("CYP3A4", "major"), inh("CYP2D6", "weak")],
    ["opioid", "cns-depressant", "serotonergic"],
    "Respiratory depression with other CNS drugs; 3A4 victim toxicity",
    {
      aliases: ["mitragynine", "7-hydroxymitragynine"],
      note: "Mitragynine is a CYP3A4 substrate. Combined with other opioids, benzos, or alcohol the respiratory risk is additive.",
    }),
  d("disulfiram", "Disulfiram", ["Antabuse"], "Aldehyde dehydrogenase inhibitor",
    [inh("CYP2E1", "strong"), inh("CYP1A2", "weak")],
    ["hepatotoxic", "seizure-lowering"],
    "Acetaldehyde reaction with ethanol; hepatotoxicity",
    { aliases: ["antabuse"] }),
  d("acamprosate", "Acamprosate", ["Campral"], "NMDA / GABA modulator",
    [],
    [],
    "Diarrhea, renal accumulation",
    { note: "Renally cleared. Almost no CYP interactions." }),
  d("varenicline", "Varenicline", ["Chantix"], "Partial nicotinic agonist",
    [],
    ["seizure-lowering"],
    "Nausea, neuropsychiatric warning",
    { aliases: ["chantix"], note: "Renally cleared. No CYP map." }),
  d("clomipramine", "Clomipramine", ["Anafranil"], "Tricyclic antidepressant",
    [sub("CYP2D6", "major"), sub("CYP2C19", "major"), sub("CYP3A4", "minor")],
    ["serotonergic", "cns-depressant", "anticholinergic", "qt-possible", "seizure-lowering"],
    "TCA toxicity, serotonin syndrome, seizure"),
  d("vortioxetine", "Vortioxetine", ["Trintellix"], "Multimodal antidepressant",
    [sub("CYP2D6", "major")],
    ["serotonergic", "ssri-snri"],
    "Serotonin syndrome, nausea"),
  d("tranylcypromine", "Tranylcypromine", ["Parnate"], "Irreversible MAOI",
    [],
    ["maoi", "serotonergic"],
    "Hypertensive crisis, serotonin syndrome",
    { note: "Irreversible MAO-A/B inhibitor. Stimulants, entactogens, and serotonergics are contraindicated." }),
  d("topiramate", "Topiramate", ["Topamax"], "Anticonvulsant",
    [ind("CYP3A4", "weak")],
    ["cns-depressant", "seizure-lowering"],
    "Cognitive slowing, metabolic acidosis, reduced OCP efficacy at high dose"),
  d("moclobemide", "Moclobemide", ["Manerix"], "Reversible MAOI (RIMA)",
    [sub("CYP2C19", "major"), inh("CYP2D6", "weak"), inh("CYP1A2", "weak")],
    ["maoi", "serotonergic"],
    "Serotonin syndrome, pressor with stimulants (lower than irreversible MAOIs)",
    { note: "Reversible MAO-A inhibitor. Still contraindicated with MDMA, other serotonergics, and stimulants, with a shorter washout than phenelzine." }),
  d("clobazam", "Clobazam", ["Onfi", "Sympazan"], "Benzodiazepine",
    [sub("CYP2C19", "sensitive"), sub("CYP3A4", "major")],
    ["cns-depressant", "benzo-zdrug"],
    "Sedation, respiratory depression; 2C19 PM or CBD can spike N-desmethylclobazam",
    { note: "Sensitive CYP2C19 substrate. Cannabidiol (Epidiolex) is a classic perpetrator." }),
  d("pcp", "Phencyclidine", [], "NMDA dissociative",
    [sub("CYP3A4", "major")],
    ["dissociative", "cns-depressant", "seizure-lowering"],
    "Prolonged psychosis, seizure, hyperthermia, airway risk with other CNS drugs",
    { aliases: ["phencyclidine"], note: "CYP3A4 to trans-PCPOH. Same NMDA + GABA stacking as ketamine." }),
  d("twocb", "2C-B", [], "Phenethylamine psychedelic",
    [sub("CYP2D6", "minor")],
    ["serotonergic", "psychedelic", "seizure-lowering"],
    "Serotonin syndrome with MAOIs; vasoconstriction",
    { aliases: ["2c-b", "2cb", "4-bromo-2,5-dimethoxyphenethylamine"] }),
  d("kava", "Kava", [], "Kavalactone sedative",
    [inh("CYP2E1", "moderate"), inh("CYP1A2", "weak"), inh("CYP2C9", "weak"), inh("CYP2C19", "weak"), inh("CYP3A4", "weak")],
    ["cns-depressant", "hepatotoxic"],
    "Hepatotoxicity, additive sedation with alcohol/benzos",
    { aliases: ["kava kava", "piper methysticum"] }),
  d("quinidine", "Quinidine", ["Quinidex"], "Class Ia antiarrhythmic",
    [sub("CYP3A4", "major"), inh("CYP2D6", "strong"), inh("P-gp", "strong")],
    ["qt-known"],
    "TdP, cinchonism, 2D6 victim toxicity",
    { note: "Strong CYP2D6 inhibitor. Paired with dextromethorphan as Nuedexta — a textbook 2D6 trap." }),
  d("ibogaine", "Ibogaine", [], "Oneirogen / NMDA–kappa agonist",
    [sub("CYP2D6", "major"), sub("CYP3A4", "minor")],
    ["dissociative", "qt-known", "cns-depressant", "seizure-lowering"],
    "Prolonged QT, ataxia, death in unsupervised use — especially with methadone or other QT drugs",
    {
      aliases: ["iboga", "noribogaine"],
      note: "CYP2D6 to noribogaine. Strong 2D6 inhibitors and QT drugs are a documented fatality pattern. Not a medical treatment map.",
    }),
  d("harmaline", "Harmaline", [], "Beta-carboline MAOI",
    [inh("CYP2D6", "moderate")],
    ["maoi", "serotonergic"],
    "Hypertensive crisis and serotonin syndrome with tyramine, stimulants, or entactogens",
    {
      aliases: ["harmine", "ayahuasca", "banisteriopsis"],
      note: "The MAOI in ayahuasca. Pharmaceutical MAOIs plus DMT/MDMA remain contraindicated outside a supervised research setting.",
    }),
  d("five-meo-dmt", "5-MeO-DMT", [], "Tryptamine psychedelic",
    [],
    ["serotonergic", "psychedelic"],
    "Intense serotonergic load; MAOI combinations have been lethal",
    {
      aliases: ["5-meo-dmt", "5meo"],
      note: "MAO-A clearance. Do not combine with harmala alkaloids or pharmaceutical MAOIs.",
    }),
  d("nitrous-oxide", "Nitrous oxide", [], "Inhaled dissociative",
    [],
    ["dissociative", "cns-depressant"],
    "Hypoxia with other CNS depressants; B12 inactivation with chronic exposure",
    { aliases: ["n2o", "nitrous"], note: "Not a CYP substrate. PD with opioids, benzos, alcohol, and other NMDA drugs." }),
  d("tyramine-foods", "Tyramine foods", [], "Aged / fermented meal",
    [],
    ["tyramine"],
    "Hypertensive crisis with MAOIs",
    {
      kind: "food",
      aliases: ["tyramine", "aged cheese", "salami", "tap beer", "soy sauce", "sauerkraut"],
      note: "Aged cheese, cured meats, tap beer, soy, and fava beans. Irreversible MAOIs plus a tyramine load can spike blood pressure within minutes.",
    }),
  d("st-johns-wort", "St. John's wort", [], "Hypericum (3A4 inducer)",
    [ind("CYP3A4", "strong"), ind("CYP2C19", "moderate"), ind("P-gp", "strong"), ind("CYP2C9", "weak")],
    ["serotonergic"],
    "Loss of 3A4-victim efficacy; serotonin syndrome with antidepressants",
    {
      kind: "herb",
      aliases: ["hypericum", "sjw", "st johns wort"],
      note: "Induces CYP3A4 and P-gp about like rifampin-lite. Also serotonergic — stacked SSRIs/MDMA are a problem on both axes.",
    }),
  d("high-fat-meal", "High-fat meal", [], "Dietary absorption booster",
    [],
    ["fat-meal"],
    "Higher oral cannabinoid (and some lipophilic) AUC",
    {
      kind: "food",
      aliases: ["fatty meal", "high fat", "with food", "fed state"],
      note: "A 50–60% fat meal can several-fold increase oral THC and CBD exposure. Take that as a PK fact, not a dosing instruction.",
    }),
  d("low-salt", "Low-salt / dehydration", [], "Renal lithium trap",
    [],
    ["sodium-restriction", "nephrotoxic"],
    "Lithium retention and toxicity",
    {
      kind: "food",
      aliases: ["low sodium", "dehydration", "salt restriction", "sauna"],
      note: "Lithium tracks sodium. Crash diets, heavy sweating, or a sudden low-salt stretch raise levels without a dose change.",
    }),
  d("high-salt", "High-salt meal", [], "Renal lithium dump",
    [],
    ["sodium-load"],
    "Drop in lithium level / loss of effect",
    {
      kind: "food",
      aliases: ["high sodium", "salty meal"],
      note: "A sudden salt load increases lithium clearance. Less dangerous than restriction, but mood can slip.",
    }),
  d("alkalinizer", "Urinary alkalinizer", [], "Bicarbonate / antacid load",
    [],
    ["urinary-alkaline"],
    "Slowed amphetamine excretion, longer stimulant effect",
    {
      kind: "food",
      aliases: ["baking soda", "sodium bicarbonate", "tums", "alkaline urine"],
      note: "Alkaline urine reabsorbs amphetamine. Antacids and bicarbonate stretch duration and peak — a classic stimulant PK trick, and a toxicity risk.",
    }),
  d("acidic-juice", "Acidic juice / vitamin C", [], "Urinary acidifier",
    [],
    ["urinary-acid"],
    "Faster amphetamine clearance, shorter duration",
    {
      kind: "food",
      aliases: ["vitamin c", "ascorbic acid", "orange juice", "cranberry"],
      note: "Acid urine speeds amphetamine excretion. Opposite of bicarbonate. Not a 3A4 story — grapefruit is the furanocoumarin, orange juice is mostly pH.",
    }),
  d("charred-meat", "Charred / smoked meat", [], "PAH CYP1A2 inducer",
    [ind("CYP1A2", "moderate")],
    [],
    "Lower 1A2-victim levels (clozapine, olanzapine, caffeine)",
    {
      kind: "food",
      aliases: ["charcoal grilled", "barbecued", "smoked meat", "pah food"],
      note: "Same PAH induction as tobacco smoke, weaker. Cruciferous vegetables do a milder version of this.",
    }),
  d("five-htp", "5-HTP / L-tryptophan", [], "Serotonin precursor",
    [],
    ["serotonergic", "tryptophan"],
    "Serotonin syndrome with MAOIs, SSRIs, MDMA, DXM",
    {
      kind: "herb",
      aliases: ["5-htp", "5htp", "tryptophan", "l-tryptophan"],
      note: "Feeds 5-HT synthesis. Stacked with an SSRI or MAOI this is a serotonergic load, not a gentle sleep aid.",
    }),
  d("goldenseal", "Goldenseal (berberine)", [], "CYP2D6 / 3A4 herbal inhibitor",
    [inh("CYP2D6", "moderate"), inh("CYP3A4", "moderate"), inh("CYP2C9", "weak")],
    [],
    "Raised 2D6 and 3A4 victim levels (DXM, MDMA, oral ketamine)",
    {
      kind: "herb",
      aliases: ["berberine", "hydrastis"],
      note: "One of the few OTC botanicals with a real CYP2D6/3A4 inhibition signal.",
    }),
  d("valerian", "Valerian root", [], "Herbal sedative",
    [],
    ["cns-depressant"],
    "Additive sedation with benzos, alcohol, GHB, ketamine",
    { kind: "herb", aliases: ["valerian", "valeriana"] }),
  d("tianeptine", "Tianeptine", ["Stablon", "Coaxil"], "Atypical μ-opioid antidepressant",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "Respiratory depression at high dose; withdrawal; 3A4 victim toxicity",
    {
      aliases: ["tianaa", "zaza"],
      note: "Prescribed as an antidepressant in some countries; μ-agonist at higher exposure. CYP3A4 substrate. Stacks with other CNS depressants.",
    }),
  d("xylazine", "Xylazine", [], "Veterinary α2-agonist",
    [],
    ["alpha2-agonist", "cns-depressant", "bradycardic"],
    "Profound sedation not reversed by naloxone; airway loss with opioids",
    {
      aliases: ["tranq", "tranq dope"],
      note: "Not a CYP story. Street opioid adulterant. Naloxone reverses the opioid but not the α2 sedation — airway support is the intervention.",
    }),
  d("medetomidine", "Medetomidine", ["Domitor"], "Veterinary α2-agonist",
    [],
    ["alpha2-agonist", "cns-depressant", "bradycardic"],
    "Deep sedation, bradycardia; not reversed by naloxone",
    {
      aliases: ["dexmedetomidine", "precedex", "dex"],
      note: "Appearing in the same street-opioid supply as xylazine. Same α2 airway problem.",
    }),
  d("isotonitazene", "Isotonitazene", [], "Benzimidazole opioid (nitazene)",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "High-potency μ-agonist respiratory arrest; 3A4 victim toxicity",
    { aliases: ["iso", "nitazene"] }),
  d("protonitazene", "Protonitazene", [], "Benzimidazole opioid (nitazene)",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "High-potency μ-agonist respiratory arrest",
    { aliases: ["protonitazene", "nitazene"] }),
  d("bromazolam", "Bromazolam", [], "Designer benzodiazepine",
    [sub("CYP3A4", "major")],
    ["benzo-zdrug", "cns-depressant", "seizure-lowering"],
    "Respiratory depression with opioids; withdrawal seizures",
    { aliases: ["bromaz", "dbzd"] }),
  d("etizolam", "Etizolam", ["Etilaam"], "Thienodiazepine",
    [sub("CYP3A4", "major")],
    ["benzo-zdrug", "cns-depressant", "seizure-lowering"],
    "Respiratory depression with opioids; withdrawal seizures",
    { aliases: ["etiz"] }),
  d("flualprazolam", "Flualprazolam", [], "Designer benzodiazepine",
    [sub("CYP3A4", "major")],
    ["benzo-zdrug", "cns-depressant", "seizure-lowering"],
    "High-potency benzo × opioid airway stack",
    { aliases: ["flualp"] }),
  d("gbl", "GBL", [], "GHB prodrug",
    [],
    ["ghb", "cns-depressant"],
    "Converts to GHB; labeled contraindication with other CNS depressants",
    {
      aliases: ["gamma-butyrolactone", "gamma butyrolactone"],
      note: "Lactonase converts GBL to GHB. Same apnea map as sodium oxybate plus alcohol or benzos.",
    }),
  d("bd-14", "1,4-Butanediol", [], "GHB prodrug",
    [sub("CYP2E1", "minor", "activation")],
    ["ghb", "cns-depressant"],
    "ADH/CYP2E1 activation to GHB; delayed coma with alcohol",
    {
      aliases: ["14bd", "1,4-bd", "butanediol"],
      note: "Alcohol occupies ADH and delays conversion, then dumps GHB later. Not a dosing map.",
    }),
  d("mephedrone", "Mephedrone", [], "Cathinone entactogen",
    [sub("CYP2D6", "major")],
    ["serotonergic", "stimulant"],
    "Serotonin syndrome with MAOIs; 2D6 victim toxicity",
    { aliases: ["4-mmc", "4mmc", "m-cat"] }),
  d("three-mmc", "3-MMC", [], "Cathinone stimulant",
    [sub("CYP2D6", "major")],
    ["serotonergic", "stimulant"],
    "Serotonin and pressor load with MAOIs",
    { aliases: ["3-mmc", "3mmc"] }),
  d("two-fdck", "2-Fluorodeschloroketamine", [], "Arylcyclohexylamine dissociative",
    [sub("CYP2B6", "major"), sub("CYP3A4", "major")],
    ["dissociative", "cns-depressant"],
    "NMDA airway stack; oral first-pass 3A4/2B6 like ketamine",
    {
      aliases: ["2-fdck", "2fdck", "2fdck"],
      note: "Ketamine analogue. Oral first-pass is the 3A4 trap; IV mostly skips it.",
    }),
  d("mxe", "Methoxetamine", [], "Arylcyclohexylamine dissociative",
    [sub("CYP2B6", "major"), sub("CYP3A4", "minor"), sub("CYP2C19", "minor")],
    ["dissociative", "cns-depressant", "seizure-lowering"],
    "Longer NMDA load than ketamine; stacked airway risk with GABA drugs",
    { aliases: ["methoxetamine"] }),
  d("loperamide", "Loperamide", ["Imodium"], "Peripheral μ-agonist / P-gp substrate",
    [sub("P-gp", "sensitive"), sub("CYP3A4", "major")],
    ["opioid", "qt-known", "cns-depressant"],
    "P-gp blockade lets loperamide into the CNS and heart — opioid toxicity plus QT",
    {
      aliases: ["imodium"],
      note: "P-gp and 3A4 keep therapeutic doses peripheral. Quinidine, ritonavir, or grapefruit plus high dose is a documented cardiotoxic pattern.",
    }),
  d("hydroxyzine", "Hydroxyzine", ["Atarax", "Vistaril"], "Sedating antihistamine",
    [sub("CYP3A4", "major")],
    ["cns-depressant", "anticholinergic", "qt-possible"],
    "Additive sedation and QT with other CNS / QT drugs",
    {
      aliases: ["atarax", "vistaril"],
      note: "The OTP 'not a benzo' for anxiety still prolongs QT and sedates. Next to methadone that is a TdP and airway row, not a free extra.",
    }),
  d("poppers", "Alkyl nitrites (poppers)", [], "Volatile nitrite vasodilator",
    [],
    ["nitrate"],
    "Profound hypotension / MI with PDE5 inhibitors",
    {
      aliases: ["amyl nitrite", "isobutyl nitrite", "popper"],
      note: "Same nitrate × PDE5 map as nitroglycerin. Not a CYP substrate.",
    }),
  d("carfentanil", "Carfentanil", [], "Ultra-potent veterinary opioid",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "Respiratory arrest at microgram exposure; 3A4 victim",
    { aliases: ["carfent"] }),

  // —— Extra NMDA / RC / street ————————————————————
  d("dck", "Deschloroketamine", [], "Arylcyclohexylamine dissociative",
    [sub("CYP2B6", "major"), sub("CYP3A4", "major")],
    ["dissociative", "cns-depressant"],
    "NMDA airway stack; oral first-pass like ketamine",
    {
      aliases: ["deschloroketamine", "2'-oxo-pcm"],
      note: "Ketamine analogue without the chlorine. Oral 3A4/2B6 first-pass is the trap; IV mostly skips it.",
    }),
  d("three-meo-pcp", "3-MeO-PCP", [], "Arylcyclohexylamine dissociative",
    [sub("CYP3A4", "major"), sub("CYP2B6", "minor")],
    ["dissociative", "cns-depressant", "seizure-lowering"],
    "Longer NMDA load than ketamine; mania, seizure, airway risk with GABA drugs",
    {
      aliases: ["3-meo-pcp", "3meopcp"],
      note: "Longer and hotter than ketamine. Same NMDA × benzo/alcohol airway map, plus a mania/seizure signal at high exposure.",
    }),
  d("four-aco-dmt", "4-AcO-DMT", [], "Tryptamine psychedelic (psilocin prodrug)",
    [],
    ["serotonergic", "psychedelic", "seizure-lowering"],
    "Serotonin syndrome with MAOIs; seizure risk with lithium",
    {
      aliases: ["4-aco-dmt", "4aco", "psilacetin", "o-acetylpsilocin"],
      note: "Deacetylated to psilocin — same MAO-A/UGT map as mushrooms, not a CYP substrate. Lithium still applies.",
    }),
  d("twentyfive-i", "25I-NBOMe", [], "NBOMe psychedelic",
    [],
    ["serotonergic", "psychedelic", "seizure-lowering", "qt-possible"],
    "Vasoconstriction, seizures, fatalities; MAOI and lithium still apply",
    {
      aliases: ["25i-nbome", "25i", "n-bomb", "nbome"],
      note: "Not a CYP story. Street blotter sold as LSD. Vasoconstriction and seizures dominate; serotonergic PD with MAOIs and lithium still fires.",
    }),
  d("mda", "MDA", [], "Entactogen / stimulant",
    [sub("CYP2D6", "major"), inh("CYP2D6", "weak"), sub("CYP3A4", "minor")],
    ["serotonergic", "stimulant", "seizure-lowering"],
    "Hyperthermia, serotonin syndrome, MAOI hypertensive crisis",
    {
      aliases: ["3,4-methylenedioxyamphetamine", "sass", "sassafras"],
      note: "MDMA's demethylenated cousin and a metabolite of MDMA. Same 2D6 + MAOI map, slightly more stimulant.",
    }),
  d("methylone", "Methylone", [], "Cathinone entactogen",
    [sub("CYP2D6", "major")],
    ["serotonergic", "stimulant"],
    "Serotonin syndrome with MAOIs; 2D6 victim toxicity",
    { aliases: ["bk-mdma", "m1", "3,4-methylenedioxymethcathinone"] }),
  d("clonazolam", "Clonazolam", [], "Designer benzodiazepine",
    [sub("CYP3A4", "major")],
    ["benzo-zdrug", "cns-depressant", "seizure-lowering"],
    "High-potency benzo × opioid airway stack; blackout and withdrawal seizures",
    { aliases: ["clam", "clonz"] }),
  d("flubromazolam", "Flubromazolam", [], "Designer benzodiazepine",
    [sub("CYP3A4", "major")],
    ["benzo-zdrug", "cns-depressant", "seizure-lowering"],
    "Very long high-potency benzo; opioid airway stack, withdrawal seizures",
    { aliases: ["flubrom", "fbzm"] }),
  d("a-pvp", "α-PVP", [], "Cathinone stimulant (pyrovalerone)",
    [sub("CYP2D6", "minor"), sub("CYP2C19", "minor")],
    ["stimulant", "seizure-lowering"],
    "Severe sympathomimetic toxicity; MAOI hypertensive crisis",
    {
      aliases: ["alpha-pvp", "flakka", "gravel"],
      note: "DAT/NET blocker more than a 5-HT releaser. Pressor with MAOIs still applies.",
    }),
  d("metonitazene", "Metonitazene", [], "Benzimidazole opioid (nitazene)",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "High-potency μ-agonist respiratory arrest; 3A4 victim toxicity",
    { aliases: ["meto", "nitazene"] }),
  d("salvinorin", "Salvinorin A", [], "Kappa-opioid oneirogen",
    [],
    ["dissociative", "cns-depressant"],
    "Brief intense dissociation; additive CNS depression",
    {
      aliases: ["salvia", "salvia divinorum", "salvinorin-a"],
      note: "Kappa agonist, not a CYP substrate and not a mu opioid — naltrexone will not reverse it. PD with other CNS drugs is still sedation.",
    }),
  d("scopolamine", "Scopolamine", ["Transderm Scop"], "Antimuscarinic tropane",
    [],
    ["anticholinergic", "cns-depressant", "seizure-lowering"],
    "Delirium, urinary retention, stacked anticholinergic burden",
    {
      aliases: ["hyoscine", "datura", "devil's trumpet", "jimsonweed"],
      note: "Datura/Brugmansia tropane. Not a CYP story. Stacks with diphenhydramine, hydroxyzine, TCAs — delirium, not a recreational map.",
    }),

  // —— Clinical classics the desk was missing ——————
  d("cimetidine", "Cimetidine", ["Tagamet"], "H2 blocker / CYP perpetrator",
    [inh("CYP1A2", "moderate"), inh("CYP2D6", "moderate"), inh("CYP3A4", "moderate"), inh("CYP2C9", "weak"), inh("P-gp", "moderate")],
    [],
    "Raised victim-drug levels (theophylline, tizanidine, warfarin, oral ketamine)",
    {
      aliases: ["tagamet"],
      note: "The original OTC cytochrome bully. Famotidine does not do this — if you need an H2 blocker next to a 1A2/3A4 victim, switch.",
    }),
  d("meperidine", "Meperidine", ["Demerol"], "Opioid analgesic",
    [sub("CYP3A4", "major"), sub("CYP2B6", "major")],
    ["opioid", "cns-depressant", "serotonergic", "seizure-lowering"],
    "Serotonin syndrome with MAOIs; seizures from normeperidine",
    {
      aliases: ["demerol", "pethidine"],
      note: "Labeled contraindicated with MAOIs. CYP3A4/2B6 to neurotoxic normeperidine, which seizes in renal impairment and with 3A4 blockade.",
    }),
  d("phenobarbital", "Phenobarbital", ["Luminal"], "Barbiturate anticonvulsant",
    [sub("CYP2C19", "major"), ind("CYP3A4", "strong"), ind("CYP2C9", "strong"), ind("CYP2C19", "moderate"), ind("CYP1A2", "moderate"), ind("P-gp", "moderate")],
    ["cns-depressant", "seizure-lowering"],
    "Loss of victim-drug efficacy (OCPs, DOACs, ketamine); stacked sedation",
    {
      aliases: ["phenobarbitone"],
      note: "Strong pan-CYP inducer after 1–2 weeks, like carbamazepine. Barbiturate PD with alcohol/opioids is additive apnea.",
    }),
  d("efavirenz", "Efavirenz", ["Sustiva", "Atripla"], "NNRTI antiretroviral",
    [sub("CYP2B6", "sensitive"), ind("CYP3A4", "moderate"), ind("CYP2B6", "moderate")],
    ["qt-possible", "cns-depressant", "seizure-lowering"],
    "Loss of 3A4/2B6 victims (methadone, ketamine); 2B6 PM neurotoxicity",
    {
      aliases: ["sustiva"],
      note: "Sensitive CYP2B6 substrate and a 3A4/2B6 inducer. Classic methadone-withdrawal precipitant. 2B6 PMs get more CNS toxicity.",
    }),
  d("triazolam", "Triazolam", ["Halcion"], "Benzodiazepine",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant", "benzo-zdrug"],
    "Profound sedation with strong 3A4 inhibitors",
    { note: "Sensitive intestinal/hepatic 3A4 substrate. Ritonavir, azoles, and grapefruit are labeled problems." }),
  d("pimozide", "Pimozide", ["Orap"], "Typical antipsychotic",
    [sub("CYP3A4", "sensitive"), sub("CYP1A2", "minor")],
    ["qt-known", "cns-depressant"],
    "TdP — contraindicated with strong 3A4 inhibitors",
    { note: "Narrow-index QT drug. Strong 3A4 inhibitors (clarithromycin, azoles, ritonavir) are labeled contraindicated." }),
  d("thioridazine", "Thioridazine", ["Mellaril"], "Typical antipsychotic",
    [sub("CYP2D6", "sensitive", "clearance", true), inh("CYP2D6", "moderate")],
    ["qt-known", "cns-depressant", "anticholinergic"],
    "TdP — contraindicated with strong 2D6 inhibitors and in 2D6 PMs",
    { note: "Boxed QT warning. Paroxetine, fluoxetine, bupropion, and 2D6 poor metabolizers are a labeled problem." }),
  d("tapentadol", "Tapentadol", ["Nucynta"], "Opioid / NRI analgesic",
    [],
    ["opioid", "cns-depressant", "serotonergic", "seizure-lowering"],
    "Respiratory depression; serotonin syndrome; seizures",
    {
      aliases: ["nucynta"],
      note: "UGT2B7, not CYP. Parent is a μ-agonist plus norepinephrine reuptake blocker — MAOIs and other serotonergics still stack.",
    }),
  d("hydromorphone", "Hydromorphone", ["Dilaudid", "Exalgo"], "Opioid analgesic",
    [],
    ["opioid", "cns-depressant"],
    "Respiratory depression, sedation",
    {
      aliases: ["dilaudid"],
      note: "UGT2B7 to H3G, not CYP. PD with benzos, alcohol, GHB, and xylazine still applies.",
    }),
  d("carisoprodol", "Carisoprodol", ["Soma"], "Carbamate muscle relaxant",
    [sub("CYP2C19", "sensitive", "activation")],
    ["cns-depressant", "seizure-lowering"],
    "Sedation, respiratory depression, meprobamate accumulation in 2C19 PMs",
    {
      aliases: ["soma"],
      note: "Prodrug. CYP2C19 to meprobamate (a barbiturate-like sedative). 2C19 PMs and CBD/fluconazole stack parent plus metabolite.",
    }),
  d("clonidine", "Clonidine", ["Catapres", "Kapvay"], "Central α2-agonist",
    [],
    ["alpha2-agonist", "cns-depressant", "bradycardic"],
    "Sedation and bradycardia; stacked airway risk with opioids",
    {
      aliases: ["catapres"],
      note: "Same α2 family as xylazine, at clinical doses. Naloxone does not reverse the α2 sedation. Rebound hypertension on abrupt stop. Still used for opioid withdrawal when lofexidine is not on the shelf.",
    }),
  d("lofexidine", "Lofexidine", ["Lucemyra"], "α2-agonist (opioid withdrawal)",
    [sub("CYP2D6", "major")],
    ["alpha2-agonist", "cns-depressant", "bradycardic"],
    "Bradycardia, hypotension; sedation naloxone will not reverse",
    {
      aliases: ["lucemyra"],
      note: "FDA-approved for opioid withdrawal. Same α2 family as clonidine and xylazine — naloxone will not reverse it. CYP2D6 substrate; paroxetine and fluoxetine raise exposure and bradycardia.",
    }),
  d("flecainide", "Flecainide", ["Tambocor"], "Class Ic antiarrhythmic",
    [sub("CYP2D6", "major")],
    ["qt-possible"],
    "Arrhythmia, 2D6 victim toxicity",
    { note: "CYP2D6 substrate with a narrow-ish index. Strong 2D6 inhibitors raise levels and QRS/QT risk." }),
  d("oxazepam", "Oxazepam", ["Serax"], "Benzodiazepine",
    [],
    ["cns-depressant", "benzo-zdrug"],
    "Sedation, respiratory depression",
    { note: "UGT-glucuronidated, like lorazepam — often the switch when 3A4/2C19 is blocked. PD stacking still applies." }),
  d("temazepam", "Temazepam", ["Restoril"], "Benzodiazepine",
    [],
    ["cns-depressant", "benzo-zdrug"],
    "Sedation, respiratory depression",
    { note: "Mostly UGT. Cleaner CYP map than diazepam or alprazolam; not a clean PD map with opioids or alcohol." }),
  d("posaconazole", "Posaconazole", ["Noxafil"], "Azole antifungal",
    [inh("CYP3A4", "strong"), inh("P-gp", "moderate")],
    ["qt-possible", "hepatotoxic"],
    "Victim-drug toxicity via 3A4, QT",
    { note: "Strong CYP3A4 inhibitor. Oral ketamine, quetiapine, midazolam, simvastatin, and colchicine all move." }),
  d("isocarboxazid", "Isocarboxazid", ["Marplan"], "Irreversible MAOI",
    [],
    ["maoi", "serotonergic"],
    "Hypertensive crisis, serotonin syndrome",
    { note: "Irreversible MAO-A/B. Same 14-day washout as phenelzine. Tyramine, stimulants, and entactogens are contraindicated." }),
  d("oxcarbazepine", "Oxcarbazepine", ["Trileptal"], "Anticonvulsant",
    [ind("CYP3A4", "moderate"), inh("CYP2C19", "moderate")],
    ["cns-depressant"],
    "Loss of 3A4-victim efficacy (OCPs); 2C19 victim toxicity; hyponatremia",
    { aliases: ["trileptal"], note: "Weaker inducer than carbamazepine, still enough to fail oral contraceptives at higher doses." }),
  d("paliperidone", "Paliperidone", ["Invega"], "Atypical antipsychotic",
    [sub("P-gp", "minor")],
    ["cns-depressant", "qt-possible"],
    "QT, EPS, hyperprolactinemia",
    { note: "9-OH-risperidone. Mostly renal, not CYP2D6 — unlike parent risperidone. QT and PD still apply." }),
  d("desipramine", "Desipramine", ["Norpramin"], "Tricyclic antidepressant",
    [sub("CYP2D6", "sensitive", "clearance", true)],
    ["serotonergic", "cns-depressant", "anticholinergic", "qt-possible", "seizure-lowering"],
    "TCA toxicity, arrhythmia",
    { note: "Sensitive CYP2D6 substrate, narrow-ish index. Paroxetine/fluoxetine/bupropion can spike levels." }),
  d("imipramine", "Imipramine", ["Tofranil"], "Tricyclic antidepressant",
    [sub("CYP2D6", "major"), sub("CYP2C19", "major", "activation")],
    ["serotonergic", "cns-depressant", "anticholinergic", "qt-possible", "seizure-lowering"],
    "TCA toxicity, serotonin syndrome, seizure"),
  d("promethazine", "Promethazine", ["Phenergan"], "Sedating antihistamine",
    [sub("CYP2D6", "major")],
    ["cns-depressant", "anticholinergic"],
    "Additive sedation, delirium, respiratory depression with opioids",
    { aliases: ["phenergan"] }),
  d("doxylamine", "Doxylamine", ["Unisom"], "Sedating antihistamine",
    [],
    ["cns-depressant", "anticholinergic"],
    "Additive sedation and anticholinergic burden",
    { aliases: ["unisom"] }),
  d("chlorpromazine", "Chlorpromazine", ["Thorazine"], "Typical antipsychotic",
    [sub("CYP2D6", "major"), sub("CYP1A2", "major"), inh("CYP2D6", "weak")],
    ["cns-depressant", "anticholinergic", "qt-possible", "seizure-lowering"],
    "Sedation, QT, EPS, stacked anticholinergic load"),
  d("rasagiline", "Rasagiline", ["Azilect"], "MAO-B inhibitor",
    [sub("CYP1A2", "major")],
    ["maoi", "serotonergic"],
    "Serotonin syndrome; pressor with stimulants at higher exposure",
    { note: "Selective MAO-B at labeled doses; selectivity is not a free pass with MDMA, other serotonergics, or ciprofloxacin (1A2)." }),
  d("lemborexant", "Lemborexant", ["Dayvigo"], "Orexin antagonist",
    [sub("CYP3A4", "sensitive")],
    ["cns-depressant"],
    "Sedation, next-day impairment; 3A4 victim",
    { note: "Sensitive 3A4 substrate. Strong 3A4 inhibitors are not recommended." }),

  // —— More food / herb perpetrators ——————————————
  d("piperine", "Black pepper (piperine)", [], "Alkaloid absorption booster",
    [inh("CYP3A4", "moderate"), inh("P-gp", "moderate"), inh("CYP2D6", "weak")],
    [],
    "Raised oral 3A4/P-gp victim exposure",
    {
      kind: "herb",
      aliases: ["black pepper", "bioperine", "piper nigrum"],
      note: "Piperine is a real 3A4/P-gp inhibitor and a bioavailability hack. A heavy pepper extract next to oral ketamine, buspirone, or loperamide is not a seasoning footnote.",
    }),
  d("pomegranate", "Pomegranate juice", [], "Intestinal CYP3A4 inhibitor",
    [inh("CYP3A4", "moderate")],
    [],
    "Raised oral 3A4-victim exposure",
    {
      kind: "food",
      aliases: ["pomegranate", "pom juice"],
      note: "Weaker and less consistent than grapefruit, same intestinal 3A4 neighborhood. Do not treat it as a free grapefruit substitute, or as harmless.",
    }),
  d("starfruit", "Star fruit", [], "Furanocoumarin / nephrotoxin",
    [inh("CYP3A4", "moderate")],
    ["nephrotoxic", "seizure-lowering"],
    "Raised oral 3A4-victim exposure; seizures in CKD",
    {
      kind: "food",
      aliases: ["carambola", "star fruit"],
      note: "3A4 inhibition plus a neurotoxin that seizes in renal failure. Not a cocktail garnish if the GFR is low.",
    }),
  d("licorice", "Licorice root", [], "Mineralocorticoid herb",
    [],
    ["hypokalemic"],
    "Hypokalemia, edema, apparent mineralocorticoid excess — worse QT and digoxin toxicity",
    {
      kind: "herb",
      aliases: ["glycyrrhiza", "glycyrrhizin", "liquorice"],
      note: "Glycyrrhizin blocks 11β-HSD2. Potassium falls. QT drugs and digoxin get more dangerous. Deglycyrrhizinated (DGL) is a different product.",
    }),
  d("ginkgo", "Ginkgo biloba", [], "Herbal antiplatelet",
    [inh("CYP2C19", "weak")],
    ["antiplatelet"],
    "Bleeding with anticoagulants/antiplatelets; weak 2C19 inhibition",
    { kind: "herb", aliases: ["ginkgo biloba", "eb-761"] }),
  d("ginseng", "Panax ginseng", [], "Herbal adaptogen",
    [ind("CYP3A4", "weak")],
    ["hypoglycemic"],
    "Possible loss of 3A4-victim efficacy; stacked hypoglycemia",
    { kind: "herb", aliases: ["asian ginseng", "panax"] }),
  d("milk-thistle", "Milk thistle (silymarin)", [], "Herbal 2C9 / 3A4 modulator",
    [inh("CYP2C9", "weak"), inh("CYP3A4", "weak")],
    ["hepatotoxic"],
    "Modest 2C9/3A4 inhibition — warfarin and oral 3A4 victims can move",
    {
      kind: "herb",
      aliases: ["silymarin", "silybum"],
      note: "Inhibition is modest and formulation-dependent. Still worth mapping next to warfarin or oral ketamine.",
    }),
  d("cruciferous", "Cruciferous vegetables", [], "Dietary CYP1A2 inducer",
    [ind("CYP1A2", "weak")],
    [],
    "Lower 1A2-victim levels (clozapine, olanzapine, caffeine) with a heavy daily load",
    {
      kind: "food",
      aliases: ["broccoli", "brussels sprouts", "cabbage", "kale", "indole-3-carbinol"],
      note: "Same PAH/AhR neighborhood as smoke, much weaker. A kale phase is not smoking a pack, but 1A2 victims can drift.",
    }),

  // —— Clinic / MAT / street additions ——————————————
  d("dexmedetomidine", "Dexmedetomidine", ["Precedex", "Igalmi"], "Central α2-agonist (IV anesthetic adjunct)",
    [],
    ["alpha2-agonist", "cns-depressant", "bradycardic"],
    "Sedation naloxone will not reverse; bradycardia, stacked airway risk with opioids",
    {
      aliases: ["precedex", "dexmed"],
      note: "Clinical cousin of xylazine and medetomidine. Same α2 map: naloxone reverses the opioid, not the α2. Ketamine-clinic recovery stacks.",
    }),
  d("propofol", "Propofol", ["Diprivan"], "IV anesthetic",
    [sub("CYP2B6", "minor")],
    ["cns-depressant"],
    "Apnea, hypotension; stacked CNS depression with benzos, opioids, ketamine",
    {
      aliases: ["diprivan", "milk of amnesia"],
      note: "Mostly UGT. The CYP row is quiet. PD with midazolam, fentanyl, and ketamine is the airway story.",
    }),
  d("prazosin", "Prazosin", ["Minipress"], "Alpha-1 blocker",
    [],
    ["alpha-blocker"],
    "First-dose syncope; orthostasis with alcohol or PDE5 inhibitors",
    {
      aliases: ["minipress"],
      note: "PTSD-nightmare dose still drops standing blood pressure. Alcohol and sildenafil stack the orthostasis, not a CYP row.",
    }),
  d("seven-oh", "7-Hydroxymitragynine", [], "Kratom μ-agonist (7-OH)",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "Respiratory depression; 3A4 victim; benzo/alcohol/xylazine airway stack",
    {
      aliases: ["7-oh", "7oh", "7-hydroxymitragynine", "7-oh-mitragynine"],
      note: "Much hotter μ-agonist than mitragynine. Street 7-OH tablets are an opioid map, not a tea map. 3A4 inhibitors raise exposure.",
    }),
  d("nalbuphine", "Nalbuphine", ["Nubain"], "Mixed opioid agonist–antagonist",
    [],
    ["opioid", "cns-depressant", "opioid-antagonist"],
    "Respiratory depression; precipitated withdrawal in full-agonist dependence",
    {
      aliases: ["nubain"],
      note: "Kappa agonist / mu antagonist. Can precipitate withdrawal in a methadone or fentanyl-dependent patient, and still stack CNS depression.",
    }),
  d("guanfacine", "Guanfacine", ["Intuniv", "Tenex"], "Central α2-agonist",
    [sub("CYP3A4", "major")],
    ["alpha2-agonist", "cns-depressant", "bradycardic"],
    "Sedation and bradycardia; 3A4 victim; stacked airway risk with opioids",
    {
      aliases: ["intuniv", "tenex"],
      note: "ADHD α2 agonist. Strong 3A4 inhibitors raise levels. Same naloxone-will-not-reverse family as clonidine and xylazine.",
    }),
  d("primidone", "Primidone", ["Mysoline"], "Barbiturate anticonvulsant (prodrug)",
    [sub("CYP2C19", "major", "activation"), ind("CYP3A4", "strong"), ind("CYP2C9", "strong"), ind("CYP2C19", "moderate"), ind("P-gp", "moderate")],
    ["cns-depressant", "seizure-lowering"],
    "Loss of victim-drug efficacy (OCPs, DOACs, ketamine); stacked sedation",
    {
      aliases: ["mysoline"],
      note: "Activated to phenobarbital. Pan-CYP induction after days to weeks. Same OCP-failure map as carbamazepine.",
    }),
  d("etonitazene", "Etonitazene", [], "Benzimidazole opioid (nitazene)",
    [sub("CYP3A4", "major")],
    ["opioid", "cns-depressant"],
    "High-potency μ-agonist respiratory arrest; 3A4 victim toxicity",
    { aliases: ["etazene", "nitazene"] }),
  d("diclazepam", "Diclazepam", [], "Designer benzodiazepine",
    [sub("CYP3A4", "major")],
    ["benzo-zdrug", "cns-depressant", "seizure-lowering"],
    "Long-acting RC benzo; opioid airway stack, delayed withdrawal",
    {
      aliases: ["chlorodiazepam"],
      note: "Metabolizes toward delorazepam / lorazepam / lormetazepam. Long tail. Treat as a 3A4 benzo next to opioids.",
    }),
  d("vilazodone", "Vilazodone", ["Viibryd"], "SPAR antidepressant",
    [sub("CYP3A4", "major")],
    ["serotonergic", "ssri-snri"],
    "Serotonin syndrome; 3A4 victim",
    { aliases: ["viibryd"], note: "SSRI plus 5-HT1A partial agonist. Strong 3A4 inhibitors raise exposure. MAOIs remain contraindicated." }),
  d("aprepitant", "Aprepitant", ["Emend"], "NK1 antagonist (antiemetic)",
    [sub("CYP3A4", "major"), inh("CYP3A4", "moderate"), ind("CYP2C9", "weak")],
    [],
    "Raised 3A4-victim levels (oral midazolam, ketamine); modest 2C9 induction (warfarin)",
    {
      aliases: ["emend", "fosaprepitant"],
      note: "Moderate 3A4 inhibitor for a few days around a dose, then a weak 2C9 inducer. Check INR after a course next to warfarin.",
    }),
  d("famotidine", "Famotidine", ["Pepcid"], "H2 blocker",
    [],
    [],
    "Not a CYP perpetrator — the switch when cimetidine is the problem",
    {
      aliases: ["pepcid"],
      note: "Unlike cimetidine, famotidine does not meaningfully inhibit 1A2/2D6/3A4. Put both on the materia when someone asks 'which H2 is safe next to tizanidine.'",
    }),
  d("oxymorphone", "Oxymorphone", ["Opana"], "Opioid analgesic",
    [],
    ["opioid", "cns-depressant"],
    "Respiratory depression, sedation",
    {
      aliases: ["opana"],
      note: "Mostly UGT, not CYP. PD with benzos, alcohol, GHB, and α2-agonists still applies. Alcohol dumps ER oxymorphone.",
    }),
  d("dirty-30", "Dirty 30 (pressed M30)", [], "Street pressed opioid",
    [sub("CYP3A4", "sensitive")],
    ["opioid", "cns-depressant"],
    "Respiratory arrest; contents are not oxycodone",
    {
      aliases: [
        "dirty 30",
        "dirty 30s",
        "dirty thirty",
        "dirty thirties",
        "pressed 30",
        "pressed 30s",
        "blues",
        "m30",
        "m 30",
        "fake perc 30",
        "pressed perc",
        "pressed oxy",
      ],
      note: "Street tablets stamped M30 are typically illicit fentanyl ± xylazine or a nitazene, not pharmaceutical oxycodone. This row is the tablet as sold. Pair xylazine for the α2 stack naloxone will not reverse. Percocet / percs is the real oxycodone + APAP combo.",
    }),
  d("epclusa", "Sofosbuvir / velpatasvir", ["Epclusa"], "HCV DAA",
    [sub("P-gp", "major"), inh("P-gp", "moderate"), sub("CYP3A4", "minor")],
    ["hepatotoxic"],
    "Loss of DAA exposure with strong inducers — not a methadone dump",
    {
      aliases: ["epclusa", "sofosbuvir", "velpatasvir", "sof/vel"],
      note: "Pan-genotypic HCV treatment common on MAT desks. Strong inducers (rifampin, carbamazepine, St. John's wort) are labeled contraindicated — the DAA fails. Methadone exposure usually does not dump. Contrast rifampin next to methadone, which does.",
    }),
];

export const DRUGS: Drug[] = raw;
export const DRUG_BY_ID: Record<string, Drug> = Object.fromEntries(raw.map((x) => [x.id, x]));

const PSYCH_CLS =
  /SSRI|SNRI|MAOI|antipsychotic|antidepressant|Benzodiazepine|Opioid|Gabapentinoid|Mood stabilizer|NMDA|Dissociative|Psychedelic|Entactogen|Stimulant|Cannabinoid|Alcohol|GHB|Z-hypnotic|Anxiolytic|ADHD|NRI|Nicotine|Methylxanthine|Tricyclic|NaSSA|SARI|NDRI|hypnotic|orexin|Melatonin|kratom|GABA|MAT|Wake-promoting|Pineal|Partial opioid|Opioid antagonist|Atypical opioid|aldehyde|NMDA \/ GABA|nicotinic|Anticonvulsant|Central muscle|AChE|α2-agonist|Nitazene|Designer benzodiazepine|Thienodiazepine|Cathinone|Arylcyclohexylamine|GHB prodrug|Alkyl nitrite|Antidiarrheal|Sedating antihistamine|Veterinary|Barbiturate|NNRTI|NBOMe|Salvinorin|Tropane|H2 blocker|Carbamate|oneirogen|pyrovalerone|NRI analgesic|IV anesthetic|NK1|SPAR|mixed opioid|7-OH|Diacetylmorphine|Street pressed|Local anesthetic/i;

export function isPsych(drug: Drug): boolean {
  if (PSYCH_CLS.test(drug.cls)) return true;
  return drug.pd.some((p) =>
    [
      "serotonergic",
      "dissociative",
      "psychedelic",
      "stimulant",
      "cannabinoid",
      "alcohol",
      "ghb",
      "cns-depressant",
      "opioid",
      "maoi",
      "ssri-snri",
      "benzo-zdrug",
      "opioid-antagonist",
    ].includes(p),
  );
}

export function isFood(drug: Drug): boolean {
  return drug.kind === "food" || drug.kind === "herb";
}

function psychRank(drug: Drug): number {
  if (drug.pd.includes("dissociative")) return 0;
  if (drug.pd.includes("psychedelic") || drug.id === "mdma") return 1;
  if (drug.pd.includes("stimulant") || drug.pd.includes("cannabinoid") || drug.pd.includes("alcohol") || drug.pd.includes("ghb"))
    return 2;
  if (isFood(drug)) return 4;
  return 3;
}

export function searchDrugs(query: string, excludeIds: string[] = []): Drug[] {
  const q = query.trim().toLowerCase();
  const excluded = new Set(excludeIds);
  if (!q) {
    const psych = DRUGS.filter((d) => !excluded.has(d.id) && isPsych(d) && !isFood(d))
      .sort((a, b) => psychRank(a) - psychRank(b) || a.name.localeCompare(b.name))
      .slice(0, 12);
    const foods = DRUGS.filter((d) => !excluded.has(d.id) && isFood(d)).slice(0, 6);
    return [...psych, ...foods];
  }
  const foodQuery =
    q === "food" ||
    q === "foods" ||
    q === "diet" ||
    q === "meal" ||
    q === "herb" ||
    q === "herbs";
  const psychQuery =
    q === "psych" ||
    q.includes("psychoact") ||
    q.includes("dissociat") ||
    q.includes("psychedel") ||
    q === "stimulant" ||
    q === "stimulants";
  if (foodQuery) {
    return DRUGS.filter((d) => !excluded.has(d.id) && isFood(d)).slice(0, 16);
  }
  if (psychQuery) {
    return DRUGS.filter((d) => !excluded.has(d.id) && isPsych(d)).slice(0, 16);
  }
  if (q === "street" || q === "rc" || q === "research") {
    return DRUGS.filter(
      (d) =>
        !excluded.has(d.id) &&
        /nitazene|Designer|Cathinone|Arylcyclohexylamine|NBOMe|oneirogen|pyrovalerone|xylazine|kratom|tianeptine|GHB prodrug|popper|ibogaine|2C-|MXE|FDCK|cocaine|heroin|Dirty|pressed opioid|Local anesthetic|Diacetylmorphine/i.test(
          d.cls + d.name,
        ),
    ).slice(0, 16);
  }
  if (q === "mat" || q === "otp" || q === "oud" || q === "obots" || q === "obot") {
    const matIds = new Set([
      "buprenorphine",
      "methadone",
      "naltrexone",
      "naloxone",
      "lofexidine",
      "clonidine",
      "acamprosate",
      "disulfiram",
      "gabapentin",
      "pregabalin",
      "xylazine",
      "epclusa",
      "seven-oh",
      "tianeptine",
      "hydroxyzine",
      "ondansetron",
    ]);
    return DRUGS.filter(
      (d) =>
        !excluded.has(d.id) &&
        (matIds.has(d.id) ||
          /Partial opioid|Opioid antagonist|HCV DAA|α2-agonist \(opioid/i.test(d.cls)),
    ).slice(0, 16);
  }
  const scored: { drug: Drug; score: number }[] = [];
  for (const drug of DRUGS) {
    if (excluded.has(drug.id)) continue;
    const name = drug.name.toLowerCase();
    const brands = drug.brands.map((b) => b.toLowerCase());
    const aliases = drug.aliases.map((a) => a.toLowerCase());
    const cls = drug.cls.toLowerCase();
    const enzymeHit = drug.enzymes.some((e) =>
      e.enzyme.toLowerCase().includes(q.replace(/\s+/g, "")),
    );
    let score = 0;
    if (name === q || brands.includes(q) || aliases.includes(q)) score = 100;
    else if (name.startsWith(q)) score = 80;
    else if (brands.some((b) => b.startsWith(q)) || aliases.some((a) => a.startsWith(q))) score = 70;
    else if (name.includes(q)) score = 60;
    else if (brands.some((b) => b.includes(q)) || aliases.some((a) => a.includes(q))) score = 50;
    else if (cls.includes(q)) score = 35;
    else if (enzymeHit) score = 25;
    else if (eKindQuery(drug, q)) score = 20;
    if (score > 0) scored.push({ drug, score });
  }
  scored.sort((a, b) => b.score - a.score || a.drug.name.localeCompare(b.drug.name));
  return scored.slice(0, 16).map((s) => s.drug);
}

function eKindQuery(drug: Drug, q: string): boolean {
  if (q.includes("inhibit")) return drug.enzymes.some((e) => e.kind === "inhibitor");
  if (q.includes("induc")) return drug.enzymes.some((e) => e.kind === "inducer");
  if (q.includes("prodrug") || q.includes("activat"))
    return drug.enzymes.some((e) => e.kind === "substrate" && e.pathway === "activation");
  return false;
}

export const FAMILIES = [
  { id: "all", label: "All" },
  { id: "nmda", label: "NMDA" },
  { id: "psychedelic", label: "Psychedelic" },
  { id: "stimulant", label: "Stimulant" },
  { id: "gaba", label: "GABA" },
  { id: "opioid", label: "Opioid" },
  { id: "psych", label: "Psych" },
  { id: "cardio", label: "Cardio" },
  { id: "id", label: "Perp / ID" },
  { id: "food", label: "Food / herb" },
  { id: "other", label: "Other" },
] as const;

export type FamilyId = (typeof FAMILIES)[number]["id"];

export function familyOf(drug: Drug): Exclude<FamilyId, "all"> {
  if (drug.kind === "food" || drug.kind === "herb") return "food";
  if (drug.pd.includes("dissociative")) return "nmda";
  if (drug.pd.includes("psychedelic")) return "psychedelic";
  if (drug.pd.includes("stimulant") || drug.id === "mdma") return "stimulant";
  if (
    drug.pd.includes("opioid") ||
    drug.pd.includes("opioid-antagonist") ||
    drug.pd.includes("alpha2-agonist")
  )
    return "opioid";
  if (drug.pd.includes("alcohol") || drug.pd.includes("ghb") || drug.pd.includes("benzo-zdrug"))
    return "gaba";
  if (
    drug.pd.includes("ssri-snri") ||
    drug.pd.includes("maoi") ||
    /antipsychotic|antidepressant|Mood|Tricyclic|NaSSA|SARI|NDRI|Anxiolytic/i.test(drug.cls)
  )
    return "psych";
  if (
    /Macrolide|Azole|Fluoroquinolone|HIV|Rifamycin|NNRTI|antiviral|H2 blocker|PK booster|Oxazolidinone|Sulfonamide|Antimycobacterial|HCV|DAA/i.test(
      drug.cls,
    )
  )
    return "id";
  if (
    drug.pd.includes("anticoagulant") ||
    drug.pd.includes("statin") ||
    drug.pd.includes("beta-blocker") ||
    drug.pd.includes("ndhp-ccb") ||
    /Statin|CCB|Beta|ARB|ACE|antiarrhythmic|DOAC|Vitamin K|Cardiac|diuretic|Alpha-1|Fibrate|PDE5|Nitrate/i.test(
      drug.cls,
    )
  )
    return "cardio";
  return "other";
}
