import { sampleNeedsPro, type SampleRegimen } from "./samples";

export type RoundSetting = "clinic" | "mat" | "street" | "ward" | "kitchen";

export interface Round extends SampleRegimen {
  setting: RoundSetting;
  stem: string;
  ask: string;
  teach: string;
}

export const ROUND_SETTINGS: { id: RoundSetting | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "clinic", label: "Clinic" },
  { id: "ward", label: "Ward" },
  { id: "mat", label: "MAT" },
  { id: "street", label: "Street" },
  { id: "kitchen", label: "Kitchen" },
];

export function roundNeedsPro(r: Round) {
  return sampleNeedsPro(r);
}

export const ROUNDS: Round[] = [
  {
    id: "r-oral-ketamine",
    title: "The oral ketamine trap",
    setting: "clinic",
    stem: "A ketamine clinic switches a patient from IM to a compounded oral lozenge. The patient also takes clarithromycin for a lingering cough. Two hours later they are far more dissociated than any IM session.",
    ask: "Why did the same milligram look so different by mouth?",
    teach: "Oral ketamine is a sensitive CYP3A4 first-pass victim. Clarithromycin is a strong 3A4 inhibitor. IV/IM mostly skip gut 3A4; the lozenge does not. Put the pair on the desk, flip to oral, and read the concentration sketch — overlay IV. Teal should climb toward the ghost IV line.",
    drugIds: ["ketamine", "clarithromycin"],
    lane: "nmda",
    ketamineRoute: "oral",
    blurb: "First-pass 3A4",
  },
  {
    id: "r-grapefruit",
    title: "Breakfast and a lozenge",
    setting: "kitchen",
    stem: "Same oral ketamine, no macrolide. The patient had a tall grapefruit juice with breakfast. The session runs long and hot.",
    ask: "Is grapefruit a 3A4 story in the liver, or in the gut?",
    teach: "Furanocoumarins knock out intestinal CYP3A4. IV ketamine barely moves. Oral ketamine, buspirone, and simvastatin do. The desk should treat grapefruit as a perpetrator, not a food footnote.",
    drugIds: ["grapefruit", "ketamine"],
    lane: "food",
    ketamineRoute: "oral",
    blurb: "Intestinal 3A4 knockout",
  },
  {
    id: "r-dxm-pm",
    title: "The cough syrup that lingered",
    setting: "ward",
    stem: "A 2D6 poor metabolizer takes extra-strength dextromethorphan. No SSRI on the list. They are still dissociated at hour six, with clonus.",
    ask: "Where is the perpetrator if there is no second drug?",
    teach: "A 2D6 PM is the perpetrator. Parent DXM (serotonergic) is not converted to dextrorphan (more NMDA). Flip CYP2D6 to poor — the finding should appear without adding a second molecule. Then tap q8h on the curve: t½ stretches to ~12 h and Rac climbs.",
    drugIds: ["dextromethorphan"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "PM" },
    blurb: "Phenotype as perpetrator",
  },
  {
    id: "r-xylazine",
    title: "Naloxone did not wake them",
    setting: "street",
    stem: "Overdose on a fentanyl fold. Two naloxone doses restore some respiratory effort. The person stays sedated, bradycardic, and will not sit up. The fold later tests xylazine-positive.",
    ask: "What did naloxone reverse, and what did it not?",
    teach: "Naloxone displaces the μ-agonist. Xylazine is an α2-agonist — sedation and airway loss are independent of the opioid receptor. Extra naloxone will not reverse an α2. Support ventilation.",
    drugIds: ["xylazine", "fentanyl"],
    lane: "street",
    blurb: "α2 sedation naloxone will not reverse",
  },
  {
    id: "r-mdma-ssri",
    title: "The SSRI that stole the roll",
    setting: "clinic",
    stem: "A patient on paroxetine takes MDMA. The entactogen is muted. Later they are agitated, sweaty, and hyperreflexic.",
    ask: "Is this a 2D6 story, a serotonin story, or both?",
    teach: "Both. Paroxetine is a strong 2D6 inhibitor (MDMA is a 2D6 victim) and an SSRI. You get stacked parent MDMA plus serotonergic PD. The desk should fire PK and PD on the same pair.",
    drugIds: ["mdma", "paroxetine"],
    lane: "entactogen",
    blurb: "2D6 blockade plus serotonin",
  },
  {
    id: "r-codeine-um",
    title: "The cough syrup that became morphine",
    setting: "ward",
    stem: "A CYP2D6 ultrarapid metabolizer is given codeine after a dental extraction. Respiratory depression follows a labeled dose.",
    ask: "What has to be true of a prodrug for a UM to be the danger, not the PM?",
    teach: "Codeine analgesia is morphine. 2D6 activation — a UM makes too much, a PM makes almost none. Contrast DXM, where the PM stacks parent. Flip 2D6 to UM on codeine and read the finding.",
    drugIds: ["codeine"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "UM" },
    blurb: "Ultrarapid prodrug activation",
  },
  {
    id: "r-clozapine-smoke",
    title: "The quit that poisoned them",
    setting: "ward",
    stem: "A patient on a stable clozapine dose stops smoking in hospital. Four days later they are drooling, tachycardic, and the level has doubled.",
    ask: "What was inducing 1A2, and what happens when it leaves?",
    teach: "Tobacco PAHs induce CYP1A2. Nicotine patches do not. Stopping smoke removes the inducer — clozapine (and olanzapine, theophylline) rebound. The host smoke toggle is the perpetrator.",
    drugIds: ["clozapine"],
    lane: "smoke",
    smoking: true,
    blurb: "1A2 induction, then rebound",
  },
  {
    id: "r-naltrexone",
    title: "The Vivitrol surprise",
    setting: "mat",
    stem: "A patient gets IM naltrexone, then takes oxycodone for a sprain three days later. No analgesia. They feel sick.",
    ask: "What does an antagonist do to a full agonist already on the receptor — and to one that arrives later?",
    teach: "Naltrexone occupies μ. Late agonist is blocked (no analgesia). If the patient was dependent, displacement is precipitated withdrawal. This is PD, not CYP.",
    drugIds: ["naltrexone", "oxycodone"],
    lane: "mat",
    blurb: "Antagonist × agonist",
  },
  {
    id: "r-tyramine",
    title: "The cheese plate",
    setting: "kitchen",
    stem: "A patient on phenelzine eats aged cheddar and tap beer at a wedding. Twenty minutes later: pounding headache, stiff neck, blood pressure in the stroke range.",
    ask: "Which enzyme in the gut was supposed to destroy the tyramine?",
    teach: "MAO-A in gut and liver. An irreversible MAOI lets dietary tyramine into the circulation. The desk maps tyramine foods as a perpetrator, not a recipe.",
    drugIds: ["tyramine-foods", "phenelzine"],
    lane: "food",
    blurb: "MAO-A and the cheese effect",
  },
  {
    id: "r-loperamide",
    title: "The Imodium that reached the brain",
    setting: "street",
    stem: "Someone chasing opioid effects takes high-dose loperamide with quinidine. They get a high — and a long QT.",
    ask: "What two gates keep loperamide peripheral at labeled doses?",
    teach: "P-gp efflux and CYP3A4. Knock either (quinidine, ritonavir, grapefruit at extremes) and Imodium becomes a central μ-agonist with QT. The map is transporter plus CYP, not 'just an antidiarrheal.'",
    drugIds: ["loperamide", "quinidine"],
    lane: "street",
    blurb: "P-gp knockout",
  },
  {
    id: "r-cimetidine",
    title: "The wrong H2 blocker",
    setting: "ward",
    stem: "Tizanidine is added for spasm. The patient has been taking OTC cimetidine for heartburn. They get hypotensive and somnolent. Famotidine would not have done this.",
    ask: "Which H2 blocker is a cytochrome bully, and which is not?",
    teach: "Cimetidine inhibits 1A2, 2D6, 3A4, P-gp. Tizanidine is a sensitive 1A2 substrate. Famotidine is the switch — put both H2 blockers on the materia and compare the enzyme rows.",
    drugIds: ["cimetidine", "tizanidine"],
    lane: "clinic",
    blurb: "OTC 1A2 bully",
  },
  {
    id: "r-warfarin-2c9",
    title: "The INR with no new drug",
    setting: "ward",
    stem: "A new warfarin start in a CYP2C9 poor metabolizer. No fluconazole, no amiodarone. The INR overshoots on a textbook dose.",
    ask: "When is the host the perpetrator?",
    teach: "S-warfarin is a sensitive 2C9 substrate. A 2C9 PM looks like a strong inhibitor of that isoform. Flip 2C9 to poor with warfarin alone.",
    drugIds: ["warfarin"],
    lane: "phenotype",
    phenotypes: { CYP2C9: "PM" },
    blurb: "2C9 PM as inhibitor",
  },
  {
    id: "r-cbd-clobazam",
    title: "Epidiolex and the sleepy benzo",
    setting: "clinic",
    stem: "A child on clobazam starts pharmaceutical CBD. Somnolence climbs. N-desmethylclobazam has stacked.",
    ask: "Which isoform is CBD bullying, and is clobazam the parent or the metabolite problem?",
    teach: "CBD is a strong CYP2C19 inhibitor. Clobazam's active metabolite is a 2C19 victim. This is a labeled pair — the desk should show 2C19 inhibition of a sensitive benzo.",
    drugIds: ["cannabidiol", "clobazam"],
    lane: "gaba",
    blurb: "2C19 metabolite stack",
  },
  {
    id: "r-poppers",
    title: "The labeled collapse",
    setting: "street",
    stem: "Sildenafil, then alkyl nitrites. Blood pressure vanishes. This is the same map as nitroglycerin.",
    ask: "Why does a 'recreational' nitrite share a contraindication with a chest-pain spray?",
    teach: "Both are nitrates. PDE5 inhibitors potentiate NO-cGMP vasodilation. Poppers are not a CYP story. The PD flag is nitrate × PDE5 — contraindicated, wait 24–48 h.",
    drugIds: ["poppers", "sildenafil"],
    lane: "street",
    blurb: "Nitrate × PDE5",
  },
  {
    id: "r-lithium-mushroom",
    title: "Lithium and the mushrooms",
    setting: "clinic",
    stem: "A stable lithium patient takes psilocybin. Seizures. Not a CYP collision.",
    ask: "If there is no shared enzyme, what is the desk scoring?",
    teach: "Pharmacodynamics. Lithium plus a serotonergic psychedelic has a documented seizure/psychotoxicity signal. The desk is allowed to fire PD with empty enzyme rows.",
    drugIds: ["lithium", "psilocybin"],
    lane: "entactogen",
    blurb: "PD without a CYP",
  },
  {
    id: "r-efavirenz",
    title: "The methadone that vanished",
    setting: "mat",
    stem: "A patient on stable methadone starts efavirenz. A week later they are in opioid withdrawal with a 'therapeutic' methadone dose.",
    ask: "Induction or inhibition — and which isoforms?",
    teach: "Efavirenz induces CYP3A4 and CYP2B6. Methadone lives on both. Inducers drop exposure; the clinical picture is withdrawal, not sedation. Contrast a 3A4 inhibitor, which raises QT risk.",
    drugIds: ["efavirenz", "methadone"],
    lane: "mat",
    blurb: "2B6/3A4 induction",
  },
  {
    id: "r-meperidine",
    title: "The labeled MAOI pair",
    setting: "ward",
    stem: "Post-op meperidine is given to a patient still within two weeks of stopping phenelzine. Agitation, fever, seizures.",
    ask: "Why is this pair on every exam, and what metabolite seizes?",
    teach: "Meperidine is serotonergic and labeled contraindicated with MAOIs. Normeperidine (3A4/2B6) is the seizure metabolite. Open the washout clock — irreversible MAOIs need 14 days.",
    drugIds: ["meperidine", "phenelzine"],
    lane: "clinic",
    blurb: "MAOI contraindication",
  },
  {
    id: "r-dexmed",
    title: "Precedex next to fentanyl",
    setting: "clinic",
    stem: "A ketamine clinic uses dexmedetomidine for recovery, with a residual fentanyl. The patient is more sedated than the opioid dose predicts. Naloxone barely changes it.",
    ask: "Which family is dexmedetomidine in, and what does that share with xylazine?",
    teach: "Clinical α2-agonist — same family as xylazine and clonidine. Naloxone reverses the opioid, not the α2. The desk should fire the α2 × opioid finding.",
    drugIds: ["dexmedetomidine", "fentanyl"],
    lane: "clinic",
    blurb: "Clinical α2 × opioid",
  },
  {
    id: "r-seven-oh",
    title: "The kratom that was not kratom",
    setting: "street",
    stem: "A '7-OH' tablet sold next to kratom. Respiratory depression with a benzo. Mitragynine at tea doses does not look like this.",
    ask: "What is 7-hydroxymitragynine doing at the μ receptor that parent mitragynine mostly is not?",
    teach: "7-OH is a much hotter μ-agonist than mitragynine. Treat it as an opioid next to benzos, alcohol, and xylazine — not as a leaf.",
    drugIds: ["seven-oh", "alprazolam"],
    lane: "street",
    blurb: "7-OH is the μ-agonist",
  },
  {
    id: "r-primidone",
    title: "The OCP that failed",
    setting: "ward",
    stem: "A patient on primidone for tremor becomes pregnant on a combined oral contraceptive that had been reliable for years.",
    ask: "What does primidone become, and what do barbiturates do to 3A4?",
    teach: "Primidone is activated to phenobarbital, a pan-CYP inducer. Ethinyl estradiol is a 3A4 victim. Induction is loss of contraceptive efficacy — same map as carbamazepine and rifampin.",
    drugIds: ["primidone", "ethinyl-estradiol"],
    lane: "clinic",
    blurb: "Barbiturate induction",
  },
  {
    id: "r-tacrolimus-gf",
    title: "The transplant and the grapefruit",
    setting: "kitchen",
    stem: "A stable tacrolimus patient drinks grapefruit juice for a week. Troughs jump. No new prescription.",
    ask: "Is this hepatic 3A4, or the gut?",
    teach: "Grapefruit knocks out intestinal CYP3A4 and mostly spares the liver. Tacrolimus is a narrow-index oral 3A4 victim. Put the pair on the desk — AUCR should rise from F, not from a longer t½. Overlay is quiet because this is not a ketamine route story; the curve itself is the lesson.",
    drugIds: ["tacrolimus", "grapefruit"],
    lane: "food",
    blurb: "NTI gut 3A4",
  },
  {
    id: "r-ibogaine-methadone",
    title: "The flood and the QT",
    setting: "street",
    stem: "Unsupervised ibogaine next to methadone. Prolonged QTc, then arrest. Both are 2D6/3A4 stories with a QT flag.",
    ask: "What does the concentration sketch add that the collision card does not?",
    teach: "Ibogaine is a 2D6 victim to noribogaine. Methadone is 2B6/3A4 with a long t½. Stacked QT plus stacked parent. Put them on the desk, then tap q24h — methadone Rac is ~2× even without a perpetrator.",
    drugIds: ["ibogaine", "methadone"],
    lane: "nmda",
    blurb: "2D6 + QT stack",
  },
  {
    id: "r-dirty-30",
    title: "The pill that was not oxycodone",
    setting: "street",
    stem: "Someone takes a blue M30 they bought as a perc 30. Two naloxone doses bring some breaths back. They stay down, bradycardic, and will not sit up. The fold later tests fentanyl and xylazine — not oxycodone.",
    ask: "What is a dirty 30, and why did naloxone only do half the job?",
    teach: "Street tablets stamped M30 are typically illicit fentanyl ± xylazine, not pharmaceutical oxycodone. Search dirty 30 — the row is the tablet as sold. Put xylazine next to it. Naloxone reverses the μ-agonist; the α2 airway loss stays. Percocet on the desk is the real oxycodone + APAP combo — a different collision (2E1 / alcohol), not this one.",
    drugIds: ["dirty-30", "xylazine"],
    lane: "street",
    blurb: "Pressed M30 ≠ perc 30",
  },
  {
    id: "r-cocaethylene",
    title: "The mixer that lasts longer",
    setting: "street",
    stem: "Cocaine, then drinks. Hours later they seize with a wide-complex rhythm. Parent cocaine should have been gone.",
    ask: "What did ethanol do to cocaine that a concentration sketch of parent drug will not show?",
    teach: "Alcohol hijacks CES1 hydrolysis and transesterifies cocaine to cocaethylene — longer t½, more arrhythmia and seizure than parent. Put cocaine + ethanol on the desk. The finding is PD, not a 3A4 row. Open the metabolite tree: benzoylecgonine is the inactive urine marker; cocaethylene is the toxic species.",
    drugIds: ["cocaine", "ethanol"],
    lane: "street",
    blurb: "Cocaethylene",
  },
  {
    id: "r-speedball",
    title: "Awake, then not",
    setting: "street",
    stem: "Cocaine and a fentanyl fold. They are talking, hypertensive, pupils a mix. Twenty minutes later they are apneic. Bystanders say they 'looked fine.'",
    ask: "Why did the stimulant not protect the airway?",
    teach: "Speedball: the stimulant masks sedation while the opioid still depresses respiration. Apnea lands when cocaine wears off. Put cocaine + fentanyl on the desk — that pair used to fire nothing; it should now fire the speedball finding. Methamphetamine plus an opioid is the goofball cousin.",
    drugIds: ["cocaine", "fentanyl"],
    lane: "street",
    blurb: "Speedball masking",
  },
  {
    id: "r-bup-precip",
    title: "The Suboxone that made them sicker",
    setting: "mat",
    stem: "Office-based start. Last use was a fentanyl fold that morning. Two milligrams of buprenorphine and they are yawning, puking, and begging to leave. Staff says the dose was too low.",
    ask: "Is this too little buprenorphine — or the wrong occupancy?",
    teach: "Buprenorphine is a high-affinity partial agonist. On a fentanyl load it displaces the full agonist and precipitates withdrawal. The desk should fire precipitated withdrawal, not stacked μ milligrams. Search suboxone — that row is the partial agonist. This is not a dosing protocol.",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
    blurb: "Failed induction",
  },
  {
    id: "r-methadone-seroquel",
    title: "Seroquel for sleep on the OTP",
    setting: "mat",
    stem: "Stable methadone. A covering prescriber adds quetiapine 100 mg at night for insomnia. Two weeks later: palpitations, a long QTc, no new illicit use.",
    ask: "If the methadone dose did not change, what stacked?",
    teach: "Methadone is a known-QT opioid. Quetiapine is a 3A4-sensitive QT drug often used off-label for sleep in MAT. Put them on the desk — you want the QT finding, and the 3A4 competitive/perpetrator row if the covering drug is a 3A4 victim. Hydroxyzine and citalopram are the same trap.",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
    blurb: "OTP QT stack",
  },
  {
    id: "r-methadone-cbz",
    title: "The mood stabilizer that stole the dose",
    setting: "mat",
    stem: "A methadone patient starts carbamazepine for mood. Ten days later they are in withdrawal with an unchanged methadone milligram.",
    ask: "Inhibition or induction — and which isoforms does methadone live on?",
    teach: "Carbamazepine is a strong 3A4 inducer (and more). Methadone is 3A4 plus 2B6. Inducers look like a stolen take-home, not like sedation. Same map as rifampin and efavirenz. Contrast fluconazole, which raises parent and QT risk.",
    drugIds: ["methadone", "carbamazepine"],
    lane: "mat",
    blurb: "3A4 induction withdrawal",
  },
  {
    id: "r-gaba-otp",
    title: "Neurontin is not a free extra",
    setting: "mat",
    stem: "Methadone 80 mg. Gabapentin 600 mg three times a day 'for nerves,' plus a leftover alprazolam. The patient is hard to arouse at dosing. Urine is negative for fentanyl.",
    ask: "Which of those three is the opioid, and which two still count on the airway?",
    teach: "Gabapentinoids add respiratory depression next to methadone. They are not a CYP story and they are not harmless because they were written for neuropathy. Put methadone + gabapentin on the desk — the gabapentinoid × opioid finding should fire. Then add alprazolam: the MAT airway triad is the three-drug stack. FDA has a warning; the desk should too.",
    drugIds: ["methadone", "gabapentin"],
    lane: "mat",
    blurb: "Gabapentinoid on OTP",
  },
];
