import { sampleNeedsPro, type SampleRegimen } from "./samples";

export type RoundSetting = "clinic" | "mat" | "street" | "ward" | "kitchen";

export interface Round extends SampleRegimen {
  setting: RoundSetting;
  stem: string;
  ask: string;
  teach: string;
}

export const ROUND_SETTINGS: { id: RoundSetting | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "clinic", label: "Clinic" },
  { id: "ward", label: "Ward" },
  { id: "mat", label: "MAT" },
  { id: "street", label: "Street" },
  { id: "kitchen", label: "Kitchen" },
];

export function roundNeedsPro(r: Round) {
  return sampleNeedsPro(r);
}

export const ROUNDS: Round[] = [
  {
    id: "r-oral-ketamine",
    title: "The oral ketamine trap",
    setting: "clinic",
    stem: "A ketamine clinic switches a patient from IM to a compounded oral lozenge. The patient also takes clarithromycin for a lingering cough. Two hours later they are far more dissociated than any IM session.",
    ask: "Why did the same milligram look so different by mouth?",
    teach: "Oral ketamine is a sensitive CYP3A4 first-pass victim. Clarithromycin is a strong 3A4 inhibitor. IV/IM mostly skip gut 3A4; the lozenge does not. Put the pair on the desk, flip to oral, and read the concentration sketch — overlay IV. Teal should climb toward the ghost IV line.",
    drugIds: ["ketamine", "clarithromycin"],
    lane: "nmda",
    ketamineRoute: "oral",
    blurb: "First-pass 3A4",
  },
  {
    id: "r-grapefruit",
    title: "Breakfast and a lozenge",
    setting: "kitchen",
    stem: "Same oral ketamine, no macrolide. The patient had a tall grapefruit juice with breakfast. The session runs long and hot.",
    ask: "Is grapefruit a 3A4 story in the liver, or in the gut?",
    teach: "Furanocoumarins knock out intestinal CYP3A4. IV ketamine barely moves. Oral ketamine, buspirone, and simvastatin do. The desk should treat grapefruit as a perpetrator, not a food footnote.",
    drugIds: ["grapefruit", "ketamine"],
    lane: "food",
    ketamineRoute: "oral",
    blurb: "Intestinal 3A4 knockout",
  },
  {
    id: "r-dxm-pm",
    title: "The cough syrup that lingered",
    setting: "ward",
    stem: "A 2D6 poor metabolizer takes extra-strength dextromethorphan. No SSRI on the list. They are still dissociated at hour six, with clonus.",
    ask: "Where is the perpetrator if there is no second drug?",
    teach: "A 2D6 PM is the perpetrator. Parent DXM (serotonergic) is not converted to dextrorphan (more NMDA). Flip CYP2D6 to poor — the finding should appear without adding a second molecule. Then tap q8h on the curve: t½ stretches to ~12 h and Rac climbs.",
    drugIds: ["dextromethorphan"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "PM" },
    blurb: "Phenotype as perpetrator",
  },
  {
    id: "r-xylazine",
    title: "Naloxone did not wake them",
    setting: "street",
    stem: "Overdose on a fentanyl fold. Two naloxone doses restore some respiratory effort. The person stays sedated, bradycardic, and will not sit up. The fold later tests xylazine-positive.",
    ask: "What did naloxone reverse, and what did it not?",
    teach: "Naloxone displaces the μ-agonist. Xylazine is an α2-agonist — sedation and airway loss are independent of the opioid receptor. Extra naloxone will not reverse an α2. Support ventilation.",
    drugIds: ["xylazine", "fentanyl"],
    lane: "street",
    blurb: "α2 sedation naloxone will not reverse",
  },
  {
    id: "r-mdma-ssri",
    title: "The SSRI that stole the roll",
    setting: "clinic",
    stem: "A patient on paroxetine takes MDMA. The entactogen is muted. Later they are agitated, sweaty, and hyperreflexic.",
    ask: "Is this a 2D6 story, a serotonin story, or both?",
    teach: "Both. Paroxetine is a strong 2D6 inhibitor (MDMA is a 2D6 victim) and an SSRI. You get stacked parent MDMA plus serotonergic PD. The desk should fire PK and PD on the same pair.",
    drugIds: ["mdma", "paroxetine"],
    lane: "entactogen",
    blurb: "2D6 blockade plus serotonin",
  },
  {
    id: "r-codeine-um",
    title: "The cough syrup that became morphine",
    setting: "ward",
    stem: "A CYP2D6 ultrarapid metabolizer is given codeine after a dental extraction. Respiratory depression follows a labeled dose.",
    ask: "What has to be true of a prodrug for a UM to be the danger, not the PM?",
    teach: "Codeine analgesia is morphine. 2D6 activation — a UM makes too much, a PM makes almost none. Contrast DXM, where the PM stacks parent. Flip 2D6 to UM on codeine and read the finding.",
    drugIds: ["codeine"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "UM" },
    blurb: "Ultrarapid prodrug activation",
  },
  {
    id: "r-clozapine-smoke",
    title: "The quit that poisoned them",
    setting: "ward",
    stem: "A patient on a stable clozapine dose stops smoking in hospital. Four days later they are drooling, tachycardic, and the level has doubled.",
    ask: "What was inducing 1A2, and what happens when it leaves?",
    teach: "Tobacco PAHs induce CYP1A2. Nicotine patches do not. Stopping smoke removes the inducer — clozapine (and olanzapine, theophylline) rebound. The host smoke toggle is the perpetrator.",
    drugIds: ["clozapine"],
    lane: "smoke",
    smoking: true,
    blurb: "1A2 induction, then rebound",
  },
  {
    id: "r-naltrexone",
    title: "The Vivitrol surprise",
    setting: "mat",
    stem: "A patient gets IM naltrexone, then takes oxycodone for a sprain three days later. No analgesia. They feel sick.",
    ask: "What does an antagonist do to a full agonist already on the receptor — and to one that arrives later?",
    teach: "Naltrexone occupies μ. Late agonist is blocked (no analgesia). If the patient was dependent, displacement is precipitated withdrawal. This is PD, not CYP.",
    drugIds: ["naltrexone", "oxycodone"],
    lane: "mat",
    blurb: "Antagonist × agonist",
  },
  {
    id: "r-tyramine",
    title: "The cheese plate",
    setting: "kitchen",
    stem: "A patient on phenelzine eats aged cheddar and tap beer at a wedding. Twenty minutes later: pounding headache, stiff neck, blood pressure in the stroke range.",
    ask: "Which enzyme in the gut was supposed to destroy the tyramine?",
    teach: "MAO-A in gut and liver. An irreversible MAOI lets dietary tyramine into the circulation. The desk maps tyramine foods as a perpetrator, not a recipe.",
    drugIds: ["tyramine-foods", "phenelzine"],
    lane: "food",
    blurb: "MAO-A and the cheese effect",
  },
  {
    id: "r-loperamide",
    title: "The Imodium that reached the brain",
    setting: "street",
    stem: "Someone chasing opioid effects takes high-dose loperamide with quinidine. They get a high — and a long QT.",
    ask: "What two gates keep loperamide peripheral at labeled doses?",
    teach: "P-gp efflux and CYP3A4. Knock either (quinidine, ritonavir, grapefruit at extremes) and Imodium becomes a central μ-agonist with QT. The map is transporter plus CYP, not 'just an antidiarrheal.'",
    drugIds: ["loperamide", "quinidine"],
    lane: "street",
    blurb: "P-gp knockout",
  },
  {
    id: "r-cimetidine",
    title: "The wrong H2 blocker",
    setting: "ward",
    stem: "Tizanidine is added for spasm. The patient has been taking OTC cimetidine for heartburn. They get hypotensive and somnolent. Famotidine would not have done this.",
    ask: "Which H2 blocker is a cytochrome bully, and which is not?",
    teach: "Cimetidine inhibits 1A2, 2D6, 3A4, P-gp. Tizanidine is a sensitive 1A2 substrate. Famotidine is the switch — put both H2 blockers on the materia and compare the enzyme rows.",
    drugIds: ["cimetidine", "tizanidine"],
    lane: "clinic",
    blurb: "OTC 1A2 bully",
  },
  {
    id: "r-warfarin-2c9",
    title: "The INR with no new drug",
    setting: "ward",
    stem: "A new warfarin start in a CYP2C9 poor metabolizer. No fluconazole, no amiodarone. The INR overshoots on a textbook dose.",
    ask: "When is the host the perpetrator?",
    teach: "S-warfarin is a sensitive 2C9 substrate. A 2C9 PM looks like a strong inhibitor of that isoform. Flip 2C9 to poor with warfarin alone.",
    drugIds: ["warfarin"],
    lane: "phenotype",
    phenotypes: { CYP2C9: "PM" },
    blurb: "2C9 PM as inhibitor",
  },
  {
    id: "r-cbd-clobazam",
    title: "Epidiolex and the sleepy benzo",
    setting: "clinic",
    stem: "A child on clobazam starts pharmaceutical CBD. Somnolence climbs. N-desmethylclobazam has stacked.",
    ask: "Which isoform is CBD bullying, and is clobazam the parent or the metabolite problem?",
    teach: "CBD is a strong CYP2C19 inhibitor. Clobazam's active metabolite is a 2C19 victim. This is a labeled pair — the desk should show 2C19 inhibition of a sensitive benzo.",
    drugIds: ["cannabidiol", "clobazam"],
    lane: "gaba",
    blurb: "2C19 metabolite stack",
  },
  {
    id: "r-poppers",
    title: "The labeled collapse",
    setting: "street",
    stem: "Sildenafil, then alkyl nitrites. Blood pressure vanishes. This is the same map as nitroglycerin.",
    ask: "Why does a 'recreational' nitrite share a contraindication with a chest-pain spray?",
    teach: "Both are nitrates. PDE5 inhibitors potentiate NO-cGMP vasodilation. Poppers are not a CYP story. The PD flag is nitrate × PDE5 — contraindicated, wait 24–48 h.",
    drugIds: ["poppers", "sildenafil"],
    lane: "street",
    blurb: "Nitrate × PDE5",
  },
  {
    id: "r-lithium-mushroom",
    title: "Lithium and the mushrooms",
    setting: "clinic",
    stem: "A stable lithium patient takes psilocybin. Seizures. Not a CYP collision.",
    ask: "If there is no shared enzyme, what is the desk scoring?",
    teach: "Pharmacodynamics. Lithium plus a serotonergic psychedelic has a documented seizure/psychotoxicity signal. The desk is allowed to fire PD with empty enzyme rows.",
    drugIds: ["lithium", "psilocybin"],
    lane: "entactogen",
    blurb: "PD without a CYP",
  },
  {
    id: "r-efavirenz",
    title: "The methadone that vanished",
    setting: "mat",
    stem: "A patient on stable methadone starts efavirenz. A week later they are in opioid withdrawal with a 'therapeutic' methadone dose.",
    ask: "Induction or inhibition — and which isoforms?",
    teach: "Efavirenz induces CYP3A4 and CYP2B6. Methadone lives on both. Inducers drop exposure; the clinical picture is withdrawal, not sedation. Contrast a 3A4 inhibitor, which raises QT risk.",
    drugIds: ["efavirenz", "methadone"],
    lane: "mat",
    blurb: "2B6/3A4 induction",
  },
  {
    id: "r-meperidine",
    title: "The labeled MAOI pair",
    setting: "ward",
    stem: "Post-op meperidine is given to a patient still within two weeks of stopping phenelzine. Agitation, fever, seizures.",
    ask: "Why is this pair on every exam, and what metabolite seizes?",
    teach: "Meperidine is serotonergic and labeled contraindicated with MAOIs. Normeperidine (3A4/2B6) is the seizure metabolite. Open the washout clock — irreversible MAOIs need 14 days.",
    drugIds: ["meperidine", "phenelzine"],
    lane: "clinic",
    blurb: "MAOI contraindication",
  },
  {
    id: "r-dexmed",
    title: "Precedex next to fentanyl",
    setting: "clinic",
    stem: "A ketamine clinic uses dexmedetomidine for recovery, with a residual fentanyl. The patient is more sedated than the opioid dose predicts. Naloxone barely changes it.",
    ask: "Which family is dexmedetomidine in, and what does that share with xylazine?",
    teach: "Clinical α2-agonist — same family as xylazine and clonidine. Naloxone reverses the opioid, not the α2. The desk should fire the α2 × opioid finding.",
    drugIds: ["dexmedetomidine", "fentanyl"],
    lane: "clinic",
    blurb: "Clinical α2 × opioid",
  },
  {
    id: "r-seven-oh",
    title: "The kratom that was not kratom",
    setting: "street",
    stem: "A '7-OH' tablet sold next to kratom. Respiratory depression with a benzo. Mitragynine at tea doses does not look like this.",
    ask: "What is 7-hydroxymitragynine doing at the μ receptor that parent mitragynine mostly is not?",
    teach: "7-OH is a much hotter μ-agonist than mitragynine. Treat it as an opioid next to benzos, alcohol, and xylazine — not as a leaf.",
    drugIds: ["seven-oh", "alprazolam"],
    lane: "street",
    blurb: "7-OH is the μ-agonist",
  },
  {
    id: "r-primidone",
    title: "The OCP that failed",
    setting: "ward",
    stem: "A patient on primidone for tremor becomes pregnant on a combined oral contraceptive that had been reliable for years.",
    ask: "What does primidone become, and what do barbiturates do to 3A4?",
    teach: "Primidone is activated to phenobarbital, a pan-CYP inducer. Ethinyl estradiol is a 3A4 victim. Induction is loss of contraceptive efficacy — same map as carbamazepine and rifampin.",
    drugIds: ["primidone", "ethinyl-estradiol"],
    lane: "clinic",
    blurb: "Barbiturate induction",
  },
  {
    id: "r-tacrolimus-gf",
    title: "The transplant and the grapefruit",
    setting: "kitchen",
    stem: "A stable tacrolimus patient drinks grapefruit juice for a week. Troughs jump. No new prescription.",
    ask: "Is this hepatic 3A4, or the gut?",
    teach: "Grapefruit knocks out intestinal CYP3A4 and mostly spares the liver. Tacrolimus is a narrow-index oral 3A4 victim. Put the pair on the desk — AUCR should rise from F, not from a longer t½. Overlay is quiet because this is not a ketamine route story; the curve itself is the lesson.",
    drugIds: ["tacrolimus", "grapefruit"],
    lane: "food",
    blurb: "NTI gut 3A4",
  },
  {
    id: "r-dairy-cipro",
    title: "The yogurt and the course",
    setting: "kitchen",
    stem: "A UTI on ciprofloxacin. The patient takes every dose with breakfast yogurt. Day three, still dysuric. Cultures persist.",
    ask: "Is this CYP1A2, or did the dose never arrive?",
    teach: "Cipro is a 1A2 inhibitor — that row is for tizanidine and clozapine. Dairy is gut chelation. Calcium in milk and yogurt binds the fluoroquinolone. Put milk + Cipro on the desk. Tetracycline is the older, worse version of the same trap.",
    drugIds: ["dairy", "ciprofloxacin"],
    lane: "food",
    blurb: "Dietary calcium chelation",
  },
  {
    id: "r-kale-inr",
    title: "The smoothie that dumped INR",
    setting: "kitchen",
    stem: "Stable warfarin. A New Year kale-smoothie phase. INR falls from 2.4 to 1.3. No new prescription, no St. John's wort.",
    ask: "Is this 2C9, or the cofactor?",
    teach: "Warfarin blocks vitamin K recycling. Leafy greens supply phylloquinone and INR falls — the antidote in a blender. Put leafy greens + warfarin on the desk. The K gummy is a different row. Not CYP2C9.",
    drugIds: ["leafy-greens", "warfarin"],
    lane: "food",
    blurb: "Dietary vitamin K",
  },
  {
    id: "r-allegra-juice",
    title: "The juice that stole Allegra",
    setting: "kitchen",
    stem: "Fexofenadine every morning with a tall apple juice. Allergies are worse, not better. No 3A4 inhibitor on the list.",
    ask: "If it is not CYP, which transporter is the perpetrator?",
    teach: "OATP2B1/1A2. Fruit juice cuts fexofenadine absorption — loss of effect, not a CYP rise. Grapefruit also knocks out gut 3A4 for other drugs; apple and orange juice do not. Put apple juice + Allegra on the desk. The P-gp arrow would have been the wrong direction.",
    drugIds: ["oatp-juice", "fexofenadine"],
    lane: "food",
    blurb: "OATP, not CYP",
  },
  {
    id: "r-coffee-t4",
    title: "Espresso with Synthroid",
    setting: "kitchen",
    stem: "Levothyroxine at 0600 with a double espresso. TSH climbs. The patient swears they never miss a dose.",
    ask: "Is this 3A4, or did the tablet never dissolve into plasma?",
    teach: "Polyphenols bind T4 in the gut (Benvenga). Caffeine-as-1A2-substrate is a different bottle on this shelf. Put coffee + levothyroxine on the desk. Wait 30–60 minutes. Soy formula is the cousin row.",
    drugIds: ["coffee", "levothyroxine"],
    lane: "food",
    blurb: "Tannin binding",
  },
  {
    id: "r-protein-ldopa",
    title: "The steak that stole 'on' time",
    setting: "kitchen",
    stem: "Parkinson's on Sinemet. Motor fluctuations cluster after protein-heavy lunches. No new inhibitor.",
    ask: "Which transporter is competing, and where?",
    teach: "LAT1. Large-neutral amino acids compete with levodopa in the gut and at the blood-brain barrier. Put a protein meal + levodopa on the desk. Iron chelation is a different mineral row. Not CYP.",
    drugIds: ["protein-meal", "levodopa"],
    lane: "food",
    blurb: "LAT1 competition",
  },
  {
    id: "r-felodipine",
    title: "The Lancet juice",
    setting: "kitchen",
    stem: "Felodipine for hypertension. A week of breakfast grapefruit. Ankles swell, pressure runs low. No new prescription.",
    ask: "Why is felodipine the teaching CCB, and would IV felodipine have moved?",
    teach: "Bailey 1991 — the paper that put grapefruit on the map. Felodipine is a sensitive intestinal 3A4 first-pass victim. F rises; t½ barely does. Overlay the idea of IV: hepatic 3A4 is largely spared. Put grapefruit + felodipine on the desk.",
    drugIds: ["grapefruit", "felodipine"],
    lane: "food",
    blurb: "The original juice victim",
  },
  {
    id: "r-ng-dilantin",
    title: "The feed that unbound Dilantin",
    setting: "ward",
    stem: "Intubated, phenytoin by NG, continuous Jevity. Levels crash. Seizures return. 2C9 looks untouched.",
    ask: "Where did the dose go if the enzyme did not change?",
    teach: "Bauer 1982. Continuous tube feeds bind phenytoin in the lumen. Hold the feed, flush, separate. Put enteral feed + phenytoin on the desk. Not CYP2C9. Warfarin and Synthroid lose the dose the same way.",
    drugIds: ["enteral-feed", "phenytoin"],
    lane: "food",
    blurb: "Tube-feed binding",
  },
  {
    id: "r-ibogaine-methadone",
    title: "The flood and the QT",
    setting: "street",
    stem: "Unsupervised ibogaine next to methadone. Prolonged QTc, then arrest. Both are 2D6/3A4 stories with a QT flag.",
    ask: "What does the concentration sketch add that the collision card does not?",
    teach: "Ibogaine is a 2D6 victim to noribogaine. Methadone is 2B6/3A4 with a long t½. Stacked QT plus stacked parent. Put them on the desk, then tap q24h — methadone Rac is ~2× even without a perpetrator.",
    drugIds: ["ibogaine", "methadone"],
    lane: "nmda",
    blurb: "2D6 + QT stack",
  },
  {
    id: "r-dirty-30",
    title: "The pill that was not oxycodone",
    setting: "street",
    stem: "Someone takes a blue M30 they bought as a perc 30. Two naloxone doses bring some breaths back. They stay down, bradycardic, and will not sit up. The fold later tests fentanyl and xylazine — not oxycodone.",
    ask: "What is a dirty 30, and why did naloxone only do half the job?",
    teach: "Street tablets stamped M30 are typically illicit fentanyl ± xylazine, not pharmaceutical oxycodone. Search dirty 30 — the row is the tablet as sold. Put xylazine next to it. Naloxone reverses the μ-agonist; the α2 airway loss stays. Percocet on the desk is the real oxycodone + APAP combo — a different collision (2E1 / alcohol), not this one.",
    drugIds: ["dirty-30", "xylazine"],
    lane: "street",
    blurb: "Pressed M30 ≠ perc 30",
  },
  {
    id: "r-cocaethylene",
    title: "The mixer that lasts longer",
    setting: "street",
    stem: "Cocaine, then drinks. Hours later they seize with a wide-complex rhythm. Parent cocaine should have been gone.",
    ask: "What did ethanol do to cocaine that a concentration sketch of parent drug will not show?",
    teach: "Alcohol hijacks CES1 hydrolysis and transesterifies cocaine to cocaethylene — longer t½, more arrhythmia and seizure than parent. Put cocaine + ethanol on the desk. The finding is PD, not a 3A4 row. Open the metabolite tree: benzoylecgonine is the inactive urine marker; cocaethylene is the toxic species.",
    drugIds: ["cocaine", "ethanol"],
    lane: "street",
    blurb: "Cocaethylene",
  },
  {
    id: "r-speedball",
    title: "Awake, then not",
    setting: "street",
    stem: "Cocaine and a fentanyl fold. They are talking, hypertensive, pupils a mix. Twenty minutes later they are apneic. Bystanders say they 'looked fine.'",
    ask: "Why did the stimulant not protect the airway?",
    teach: "Speedball: the stimulant masks sedation while the opioid still depresses respiration. Apnea lands when cocaine wears off. Put cocaine + fentanyl on the desk — that pair used to fire nothing; it should now fire the speedball finding. Methamphetamine plus an opioid is the goofball cousin.",
    drugIds: ["cocaine", "fentanyl"],
    lane: "street",
    blurb: "Speedball masking",
  },
  {
    id: "r-bup-precip",
    title: "The Suboxone that made them sicker",
    setting: "mat",
    stem: "Office-based start. Last use was a fentanyl fold that morning. Two milligrams of buprenorphine and they are yawning, puking, and begging to leave. Staff says the dose was too low.",
    ask: "Is this too little buprenorphine — or the wrong occupancy?",
    teach: "Buprenorphine is a high-affinity partial agonist. On a fentanyl load it displaces the full agonist and precipitates withdrawal. The desk should fire precipitated withdrawal, not stacked μ milligrams. Search suboxone — that row is the partial agonist. This is not a dosing protocol.",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
    blurb: "Failed induction",
  },
  {
    id: "r-methadone-seroquel",
    title: "Seroquel for sleep on the OTP",
    setting: "mat",
    stem: "Stable methadone. A covering prescriber adds quetiapine 100 mg at night for insomnia. Two weeks later: palpitations, a long QTc, no new illicit use.",
    ask: "If the methadone dose did not change, what stacked?",
    teach: "Methadone is a known-QT opioid. Quetiapine is a 3A4-sensitive QT drug often used off-label for sleep in MAT. Put them on the desk — you want the QT finding, and the 3A4 competitive/perpetrator row if the covering drug is a 3A4 victim. Hydroxyzine and citalopram are the same trap.",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
    blurb: "OTP QT stack",
  },
  {
    id: "r-methadone-cbz",
    title: "The mood stabilizer that stole the dose",
    setting: "mat",
    stem: "A methadone patient starts carbamazepine for mood. Ten days later they are in withdrawal with an unchanged methadone milligram.",
    ask: "Inhibition or induction — and which isoforms does methadone live on?",
    teach: "Carbamazepine is a strong 3A4 inducer (and more). Methadone is 3A4 plus 2B6. Inducers look like a stolen take-home, not like sedation. Same map as rifampin and efavirenz. Contrast fluconazole, which raises parent and QT risk.",
    drugIds: ["methadone", "carbamazepine"],
    lane: "mat",
    blurb: "3A4 induction withdrawal",
  },
  {
    id: "r-gaba-otp",
    title: "Neurontin is not a free extra",
    setting: "mat",
    stem: "Methadone 80 mg. Gabapentin 600 mg three times a day 'for nerves,' plus a leftover alprazolam. The patient is hard to arouse at dosing. Urine is negative for fentanyl.",
    ask: "Which of those three is the opioid, and which two still count on the airway?",
    teach: "Gabapentinoids add respiratory depression next to methadone. They are not a CYP story and they are not harmless because they were written for neuropathy. Put methadone + gabapentin on the desk — the gabapentinoid × opioid finding should fire. Then add alprazolam: the MAT airway triad is the three-drug stack. FDA has a warning; the desk should too.",
    drugIds: ["methadone", "gabapentin"],
    lane: "mat",
    blurb: "Gabapentinoid on OTP",
  },
  {
    id: "r-vivitrol-fent",
    title: "The shot and the leftover fold",
    setting: "mat",
    stem: "IM naltrexone on Friday. Saturday they use a fentanyl fold 'just once.' No high. Then they are sick — yawning, puking, goosebumps — and staff says the shot failed.",
    ask: "Did Vivitrol fail, or did it do exactly what occupancy does?",
    teach: "Naltrexone occupies μ for weeks. Leftover fentanyl is precipitated withdrawal and blocked analgesia, not a slip that didn't work. Put naltrexone + fentanyl on the desk. The finding is PD, not CYP. Same map as a 'just this once' oxycodone after the shot.",
    drugIds: ["naltrexone", "fentanyl"],
    lane: "mat",
    blurb: "Vivitrol leftover",
  },
  {
    id: "r-methadone-fluconazole",
    title: "The yeast cream that was a pill",
    setting: "mat",
    stem: "Stable methadone 80 mg. A dentist writes fluconazole for thrush. Two days later they nod at the window and the ECG is longer. No new illicit use.",
    ask: "Inhibition or induction — and why is the QT in the story?",
    teach: "Fluconazole is a moderate 3A4 inhibitor (and a QT drug). Methadone lives on 3A4/2B6 and is a known-QT opioid. Inhibitors raise parent and TdP risk — the opposite of rifampin, which looks like a stolen dose. Put the pair on the desk; you want PK plus QT.",
    drugIds: ["methadone", "fluconazole"],
    lane: "mat",
    blurb: "Azole on OTP",
  },
  {
    id: "r-bup-sevenoh",
    title: "The smoke-shop Suboxone",
    setting: "mat",
    stem: "Stable on a Suboxone film. They buy 7-OH tablets at the smoke shop 'because it's kratom.' Either they feel nothing, or they get sick. Urine is negative for fentanyl.",
    ask: "Is 7-OH a tea, or a μ-agonist next to a partial?",
    teach: "7-Hydroxymitragynine is a hot μ-agonist, not a leaf. Next to buprenorphine the desk should fire occupancy conflict (precipitated withdrawal / blocked high), not stacked milligrams of two prescriptions. Search 7-oh. This is not a dosing protocol.",
    drugIds: ["buprenorphine", "seven-oh"],
    lane: "mat",
    blurb: "7-OH on a film",
  },
  {
    id: "r-hcv-otp",
    title: "The hep C that did not steal the dose",
    setting: "mat",
    stem: "Methadone 90 mg. They start Epclusa for HCV. A covering clinician cuts the methadone 'because of the new liver drug.' A week later they are in withdrawal. Later the same year they start rifampin for latent TB and the dose really does fail.",
    ask: "Which ID drug dumps methadone, and which one dumps the DAA?",
    teach: "Epclusa (sofosbuvir/velpatasvir) is a P-gp story. Methadone usually does not need a cut — put methadone + Epclusa on the desk and the CYP/PD rows should stay quiet. Rifampin induces 3A4/2B6 and will dump methadone; it is also labeled contraindicated with the DAA. Swap Epclusa for rifampin to see the stolen-dose map.",
    drugIds: ["methadone", "epclusa"],
    lane: "mat",
    blurb: "HCV vs TB on OTP",
  },
  {
    id: "r-methadone-fentanyl",
    title: "The take-home and the fold",
    setting: "mat",
    stem: "Stable methadone 90 mg, take-homes for the weekend. Sunday they use a fentanyl fold 'because the dose was not holding.' Monday they are hard to arouse at dosing. Urine is fentanyl-positive. Staff says they doubled their methadone.",
    ask: "Is this a stolen extra bottle, or two full agonists on one airway?",
    teach: "A methadone take-home plus illicit fentanyl is stacked μ load — one airway, not two prescriptions. Put methadone + fentanyl on the desk. Then add xylazine: naloxone reverses the opioid, not the α2. This is not a dosing protocol.",
    drugIds: ["methadone", "fentanyl"],
    lane: "mat",
    blurb: "Take-home × supply",
  },
  {
    id: "r-paxlovid-otp",
    title: "The five-day COVID course",
    setting: "mat",
    stem: "A covering clinician starts Paxlovid for COVID. The methadone patient is in withdrawal by day three. A second patient on illicit fentanyl nods harder and is hard to arouse. Same prescription.",
    ask: "Why did one fall and the other rise?",
    teach: "Paxlovid is a five-day ritonavir boost. Fentanyl is a sensitive 3A4 substrate — parent and airway climb (Olkkola: clearance −67%). Methadone often falls anyway (2B6/UGT) — watch withdrawal, not nod. Put methadone + Paxlovid, then swap methadone for fentanyl. Opposite arrows. Not a dosing protocol.",
    drugIds: ["methadone", "paxlovid"],
    lane: "mat",
    blurb: "Paxlovid mixed arrow",
  },
  {
    id: "r-luvox-otp",
    title: "The OCD pill that made them nod",
    setting: "mat",
    stem: "Stable methadone 80 mg. Psychiatry starts fluvoxamine for OCD. Two weeks later they nod at the window and the QTc is longer. No new illicit use. A month after Luvox is stopped they are in withdrawal on the same milligram.",
    ask: "Starting and stopping — which way does the parent move?",
    teach: "Fluvoxamine is a 1A2/2C19/3A4/2B6 inhibitor. Methadone parent climbs (Bertschy 1994); stopping it looks like a stolen dose. Put methadone + fluvoxamine on the desk — you want PK plus QT plus serotonin. Fluoxetine is not the same map.",
    drugIds: ["methadone", "fluvoxamine"],
    lane: "mat",
    blurb: "Luvox bump",
  },
  {
    id: "r-phenytoin-otp",
    title: "The seizure pill that stole the dose",
    setting: "mat",
    stem: "A methadone patient seizes in the lobby. The ED starts phenytoin. Four days later they are yawning, puking, and begging for a dose increase. The methadone milligram did not change.",
    ask: "Inhibition or induction — and how fast?",
    teach: "Tong 1981: phenytoin in therapeutic doses dumps methadone within days. 3A4 plus 2B6 induction looks like a stolen take-home. Same family as carbamazepine, rifampin, and efavirenz. Put methadone + phenytoin on the desk.",
    drugIds: ["methadone", "phenytoin"],
    lane: "mat",
    blurb: "Dilantin stolen dose",
  },
  {
    id: "r-medetomidine-supply",
    title: "The tranq that is not xylazine",
    setting: "mat",
    stem: "Overdose on a fentanyl fold. Two naloxone doses restore some respiratory effort. They stay down, bradycardic, pinpoint. The fold later tests medetomidine — not xylazine.",
    ask: "Does a third naloxone finish this, or is the receptor wrong?",
    teach: "Medetomidine is the newer veterinary α2 in the supply. Same map as xylazine: naloxone reverses the μ-agonist, not the α2 airway loss. Put fentanyl + medetomidine on the desk. Support ventilation. This is not a dosing protocol.",
    drugIds: ["fentanyl", "medetomidine"],
    lane: "mat",
    blurb: "α2 in the fold",
  },
  {
    id: "r-phenergan-window",
    title: "Phenergan at the window",
    setting: "mat",
    stem: "Nausea after dosing. The nurse gives promethazine. An hour later they are harder to arouse than the methadone dose predicts. The covering clinician says it is just an antiemetic.",
    ask: "Is Phenergan free next to a known-QT opioid?",
    teach: "Promethazine is a sedating antihistamine and a possible QT drug. Next to methadone it is airway plus repolarization load — not a free nausea drop. Put methadone + promethazine on the desk. Hydroxyzine is the same trap with a louder QT flag.",
    drugIds: ["methadone", "promethazine"],
    lane: "mat",
    blurb: "Window antiemetic",
  },
  {
    id: "r-luvox-not-prozac",
    title: "Not every SSRI is Luvox",
    setting: "mat",
    stem: "Psychiatry starts fluoxetine for depression on stable methadone 80 mg. A covering clinician cuts the methadone 'because SSRIs raise it, like Luvox.' Two weeks later they are in withdrawal. A different patient on fluvoxamine really did nod.",
    ask: "Which SSRI is the OTP bump, and which one is a 2D6 story?",
    teach: "Fluvoxamine (Luvox) inhibits 1A2/2C19/3A4/2B6 and raises methadone (Bertschy 1994). Fluoxetine and paroxetine are strong 2D6 inhibitors — not the same map. Put methadone + fluvoxamine, then swap for fluoxetine. The window briefing should say Prozac is not Luvox. Not a dosing protocol.",
    drugIds: ["methadone", "fluoxetine"],
    lane: "mat",
    blurb: "SSRI ≠ Luvox",
  },
  {
    id: "r-zpak-otp",
    title: "Biaxin is not a Z-Pak",
    setting: "mat",
    stem: "Walking pneumonia on methadone 90 mg. Pharmacy substitutes clarithromycin when azithromycin is short. Three days later they nod at the window and the QTc is longer.",
    ask: "Which macrolide raises parent, and which one is mostly QT?",
    teach: "Clarithromycin is a strong 3A4 inhibitor plus a QT drug — methadone parent and repolarization both climb. Azithromycin barely touches CYP3A4; it still stacks QT. Put methadone + clarithromycin, then swap for azithromycin. The window briefing should name the difference. Not a dose.",
    drugIds: ["methadone", "clarithromycin"],
    lane: "mat",
    blurb: "Macrolide at the window",
  },
  {
    id: "r-bup-paxlovid",
    title: "The film and the COVID pills",
    setting: "mat",
    stem: "Stable Suboxone. A covering clinician starts Paxlovid. Staff cuts the film 'because ritonavir dumps methadone.' Two days later they are in withdrawal. A methadone patient on the same prescription really did get sick.",
    ask: "Same booster — why did one fall and the other should not have been cut?",
    teach: "Paxlovid is a five-day ritonavir boost. Methadone often falls (2B6/UGT) — watch withdrawal. Buprenorphine is a 3A4 substrate: parent can climb ~50% (McCance-Katz) without a withdrawal map, and tolerant patients usually need no cut. Put buprenorphine + Paxlovid on the desk, then swap for methadone. Opposite arrows. Not a dosing protocol.",
    drugIds: ["buprenorphine", "paxlovid"],
    lane: "mat",
    blurb: "Bup vs methadone on Paxlovid",
  },
  {
    id: "r-tybost-otp",
    title: "Tybost is not Norvir",
    setting: "mat",
    stem: "New Genvoya. The OTP cuts methadone 'because boosters dump it, like ritonavir.' A week later they nod at the window and the QTc is longer.",
    ask: "Which booster induces 2B6, and which one only blocks 3A4?",
    teach: "Ritonavir and Paxlovid dump methadone despite 3A4 inhibition (Kharasch). Cobicistat (Tybost) is 3A4 inhibit without 2B6 induction — parent climbs. Put methadone + cobicistat on the desk, then swap for ritonavir. The window briefing should name the difference. Not a dose.",
    drugIds: ["methadone", "cobicistat"],
    lane: "mat",
    blurb: "Cobicistat vs ritonavir",
  },
  {
    id: "r-cipro-otp",
    title: "The UTI pill that made them nod",
    setting: "mat",
    stem: "Stable methadone 90 mg. Cipro for a UTI. Two days later they nod at the window, the QTc is longer, and nobody added a street fold.",
    ask: "Is Cipro a 3A4 story, a QT story, or both?",
    teach: "Both. Ciprofloxacin is a strong 1A2 inhibitor and a weak 3A4 inhibitor plus a QT drug. Herrlin 2000 is the methadone case. Put methadone + ciprofloxacin on the desk — you want PK plus QT. Separate cations from the tablet; that is a different row. Not a free UTI pill on a known-QT opioid.",
    drugIds: ["methadone", "ciprofloxacin"],
    lane: "mat",
    blurb: "Cipro on the OTP",
  },
  {
    id: "r-aza-allo",
    title: "The gout pill on a transplant thiopurine",
    setting: "clinic",
    stem: "Stable ulcerative colitis on azathioprine. A covering clinician starts allopurinol for gout. Two weeks later the WBC is 1.1 and they are febrile.",
    ask: "Is this a CYP story, or a different enzyme entirely?",
    teach: "Xanthine oxidase clears 6-mercaptopurine. Allopurinol (and febuxostat) block it. The thiopurine then behaves like a multiple of the prescribed dose — pancytopenia, not a gout footnote. Put azathioprine + allopurinol on the desk. You want a contraindicated PD finding, not a 3A4 row. Swap allopurinol for febuxostat — same enzyme. Not a dosing protocol.",
    drugIds: ["azathioprine", "allopurinol"],
    lane: "clinic",
    blurb: "XO × thiopurine",
  },
  {
    id: "r-imdur-viagra",
    title: "The daily nitrate and the weekend pill",
    setting: "clinic",
    stem: "Imdur every morning for angina. He takes sildenafil on a Saturday. EMS finds him hypotensive and pale. Nitroglycerin in the field makes it worse.",
    ask: "Which pair is the labeled contraindication — and how long is the wait?",
    teach: "Nitrates plus PDE5 inhibitors are contraindicated — refractory hypotension, not a CYP row. Put isosorbide mononitrate + sildenafil on the desk. The wait is about 24 h after sildenafil, 48 h after tadalafil. Search Imdur or Viagra. Poppers are the same nitrate flag.",
    drugIds: ["isosorbide-mononitrate", "sildenafil"],
    lane: "clinic",
    blurb: "Nitrate × PDE5",
  },
  {
    id: "r-flonase-norvir",
    title: "The spray that became Cushing",
    setting: "clinic",
    stem: "HIV, stable on ritonavir-boosted ART. Allergies, so Flonase all winter. Moon face, high sugars, a suppressed morning cortisol. Nobody changed the HIV meds.",
    ask: "How does a nasal steroid become systemic next to a booster?",
    teach: "Swallowed fluticasone is a sensitive gut CYP3A4 first-pass victim. Ritonavir knocks that gate out; bioavailability jumps and the 'spray' is now a systemic steroid. Put fluticasone + ritonavir on the desk and read the concentration sketch. Beclomethasone is the usual switch. Not a dose.",
    drugIds: ["fluticasone", "ritonavir"],
    lane: "clinic",
    blurb: "ICS × booster",
  },
  {
    id: "r-plavix-prilosec",
    title: "The PPI that blunted the stent",
    setting: "clinic",
    stem: "Clopidogrel after a stent. Omeprazole for reflux. Platelet testing looks like a 2C19 poor metabolizer. Nobody is a PM.",
    ask: "Activation or clearance — and which PPI is the quieter switch?",
    teach: "Clopidogrel is a 2C19 prodrug. Omeprazole and esomeprazole inhibit 2C19 and blunt activation — loss of antiplatelet effect, not bleeding. Put clopidogrel + omeprazole on the desk; you want lost activation, not a 3A4 row. Pantoprazole is the usual switch. Ticagrelor is not a prodrug.",
    drugIds: ["clopidogrel", "omeprazole"],
    lane: "clinic",
    blurb: "2C19 prodrug",
  },
  {
    id: "r-lithium-nsaid",
    title: "The ibuprofen that raised the lithium",
    setting: "clinic",
    stem: "Stable lithium 0.7 for years. A week of OTC ibuprofen for a sprain. Tremor, nausea, a trough of 1.6. Creatinine ticked up. Nobody added a cytochrome inhibitor.",
    ask: "Where is the perpetrator if there is no CYP row?",
    teach: "Lithium is renally cleared. NSAIDs drop GFR and raise the trough. ACEI and thiazides do the same. Put lithium + ibuprofen on the desk, flip CKD if you want the host to light up, and read the Levels tab — 0.6–1.2, toxic >1.5. Not a 2C9 story.",
    drugIds: ["lithium", "ibuprofen"],
    lane: "clinic",
    blurb: "TDM · NSAID retains lithium",
  },
  {
    id: "r-methadone-qt",
    title: "Seroquel for sleep on the window",
    setting: "mat",
    stem: "Methadone 110 mg. Quetiapine 200 at night for 'sleep'. Ondansetron for the nausea. A loop diuretic. The ECG is 510 ms. Potassium is 3.1.",
    ask: "Which of these is the known-risk QT drug — and what did the potassium do?",
    teach: "Methadone is known-risk and dose-related. Quetiapine and ondansetron are possible-risk. The loop diuretic is the amplifier. Put methadone + quetiapine on the desk and open the QT board. This is not Bazett — it is a stack map. Drop the antiemetic, replete K/Mg, ECG.",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
    blurb: "QT stack on the OTP",
  },
  {
    id: "r-valproate-liver",
    title: "The mood stabilizer that failed the liver",
    setting: "ward",
    stem: "Young woman, new valproate for mania. Week three: nausea, a rising ALT, ammonia up with a near-normal bilirubin. Nobody checked a LiverTox category.",
    ask: "Is this a UGT story with lamotrigine, or a hepatotoxin?",
    teach: "Both can be true, but this stem is the hepatotoxin. Valproate is LiverTox category A — boxed, worse under 2 years and in mitochondrial disease. Put valproate on the desk, open LiverTox and Levels (50–100 µg/mL). Hyperammonemia can sit inside the range. Not first-line if she can become pregnant.",
    drugIds: ["valproate"],
    lane: "clinic",
    blurb: "LiverTox A",
  },
  {
    id: "r-clozapine-tdm",
    title: "He quit smoking and seized",
    setting: "ward",
    stem: "Clozapine 400 mg, trough 380, no seizures for a year. Admitted, no cigarettes for five days. He seizes. The trough is 980. Nobody changed the milligrams.",
    ask: "Which enzyme moved — and which way?",
    teach: "CYP1A2. Daily smoke induces it; quitting removes the induction and parent climbs. Put clozapine on the desk, flip smoke off, and read Levels (350–600, toxic >1000) plus the 1A2 row. Fluvoxamine is the drug version of the same trap. Not a dose protocol — a TDM story.",
    drugIds: ["clozapine"],
    lane: "smoke",
    smoking: true,
    blurb: "1A2 quit rebound",
  },
  {
    id: "r-pheno-codeine",
    title: "The genotype that lied",
    setting: "clinic",
    stem: "CYP2D6 *1/*1, reported NM. Codeine for a dental extraction. She also takes paroxetine. No analgesia, then a day of jitter and a high parent codeine. Someone says 'the PGx test failed.'",
    ask: "Did the genotype change?",
    teach: "No. Paroxetine is a strong 2D6 inhibitor. A normal metabolizer on paroxetine is a phenotypic PM — phenoconversion. Codeine needs 2D6 to become morphine, so analgesia fails and parent stacks. Put paroxetine + codeine on the desk. The Pheno tab should read NM genotype → PM-like. CPIC still lists the lab.",
    drugIds: ["paroxetine", "codeine"],
    lane: "phenotype",
    blurb: "2D6 phenoconversion",
  },
  {
    id: "r-hunter",
    title: "Clonus, not a plus-table",
    setting: "ward",
    stem: "SSRI for years. Recreational MDMA. ED: inducible clonus, diaphoresis, tremor, reflexes that scare the intern. No lead-pipe rigidity. Someone wants dantrolene for NMS.",
    ask: "Hunter or NMS?",
    teach: "Hunter. Serotonergic agent + inducible clonus + diaphoresis is enough. Hyperreflexia and clonus are serotonin; NMS is bradyreflexia and lead-pipe rigidity on a dopamine blocker, slower onset. Put MDMA + sertraline on the desk and open Hunter. Cyproheptadine is adjunct. This is not Sternbach.",
    drugIds: ["mdma", "sertraline"],
    lane: "entactogen",
    blurb: "Hunter criteria",
  },
  {
    id: "r-uds-methadone",
    title: "The cup that stayed negative",
    setting: "mat",
    stem: "Methadone 110 mg, supervised. The opiate immunoassay is negative. A counselor says they dunked the bottle. EDDP was never ordered. The fentanyl strip is also negative.",
    ask: "Is a negative morphine-class cup proof they skipped the dose?",
    teach: "Methadone is not morphine. The opiate EIA should stay negative on a take-home. EDDP is the metabolite that proves they swallowed it. Fentanyl is a different strip; nitazenes often miss that too. Put methadone on the desk and open UDS. Saitman 2014 is the false-positive review — this stem is a miss, not a false-positive.",
    drugIds: ["methadone"],
    lane: "mat",
    blurb: "UDS · opiate EIA miss",
  },
  {
    id: "r-uds-seroquel",
    title: "The TCA that was not a TCA",
    setting: "mat",
    stem: "Methadone window. Seroquel 50 at night for sleep. A TCA immunoassay lights. Someone charts a TCA overdose and holds the bottle.",
    ask: "Is this a tricyclic, or the antibody?",
    teach: "Quetiapine cross-reacts on many TCA cups. Confirm with LC-MS/MS. The methadone opiate cup should still be negative — two immunoassay rows, neither of which is a dunked bottle. Put methadone + quetiapine on the desk and open UDS.",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
    blurb: "UDS · TCA false-positive",
  },
  {
    id: "r-cows-fent",
    title: "COWS 14 and they still precipitated",
    setting: "mat",
    stem: "Office-based start. Last fentanyl fold was yesterday afternoon. COWS is 14. Two milligrams of buprenorphine and they are yawning, puking, and begging to leave. Staff says the COWS was high enough.",
    ask: "Did the integer fail, or did occupancy?",
    teach: "COWS is a score, not a receptor. Fentanyl in adipose can still occupy μ when the patient looks sick enough to start. Put buprenorphine + fentanyl on the desk. The finding is precipitated withdrawal. Open Bedside for the Wesson & Ling items. This desk is not an induction protocol.",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
    blurb: "COWS · occupancy",
  },
  {
    id: "r-lact-methadone",
    title: "They told her to stop the bottle to breastfeed",
    setting: "mat",
    stem: "Stable methadone 80 mg. Newborn in NAS protocol. A night nurse tells her to pump-and-dump and come off methadone so she can feed. She is in tears at the window.",
    ask: "Is methadone in milk a reason to stop OTP?",
    teach: "LactMed lists methadone as usually compatible. Relative infant dose is about 1–3% on a stable bottle. Neonatal opioid withdrawal is from in-utero exposure, not from usual milk doses. Put methadone on the desk, flip Lactating, open LactMed. Jones MOTHER is NAS after pregnancy, not a pump-and-dump card. Do not stop OTP to breastfeed.",
    drugIds: ["methadone"],
    lane: "mat",
    blurb: "LactMed · OTP",
  },
  {
    id: "r-nalmefene",
    title: "The antagonist that lasted too long",
    setting: "mat",
    stem: "Overdose in the lot. Staff used Opvee because Narcan was on the other cart. Two hours later they look over-reversed and still sick. Someone wants a methadone rescue dose.",
    ask: "Is this a stolen bottle, or the occupancy of nalmefene?",
    teach: "Nalmefene occupies μ longer than naloxone. After a fentanyl fold they can re-narcotize as it wears — or look over-reversed for hours. Put nalmefene + fentanyl on the desk. Reversal tab: Opvee is not Narcan. This desk is not a field protocol and not a rescue-dose card.",
    drugIds: ["nalmefene", "fentanyl"],
    lane: "mat",
    blurb: "Opvee occupancy",
  },
  {
    id: "r-otp-precip",
    title: "The COWS that lied",
    setting: "mat",
    stem: "Office start. Last pressed 30 yesterday. COWS 13. First film, then yawning and puke. Staff says the score was high enough.",
    ask: "Did the scale fail, or did occupancy?",
    teach: "Open the OTP tab. Set last agonist to fentanyl, hours to 24, COWS to 13. Occupancy can outlast a moderate score. ASAM 2020 / TIP 63 discuss timing; this desk does not time a film. Put buprenorphine + fentanyl on the desk.",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
    blurb: "OTP · occupancy",
  },
  {
    id: "r-vivitrol-early",
    title: "The shot that was not a rescue",
    setting: "mat",
    stem: "Missed methadone Friday. Monday someone wants Vivitrol so he does not leave in withdrawal. Last bottle was 72 hours ago.",
    ask: "Is three days enough after methadone?",
    teach: "Open OTP → naltrexone washout. Methadone occupancy is days. Labels discuss ~10–14 days after long-acting agonists. A shot is not a missed-bottle rescue. Put naltrexone + methadone on the desk.",
    drugIds: ["naltrexone", "methadone"],
    lane: "mat",
    blurb: "Vivitrol washout",
  },
  {
    id: "r-anc-clozapine",
    title: "The ANC that was not a WBC",
    setting: "ward",
    stem: "Clozapine 400. The lab prints WBC 3.2. Pharmacy holds the fill. ANC is 1600. He has not missed a tablet.",
    ask: "Is this a REMS interrupt?",
    teach: "Open ANC. 1600 general population is green (≥1500). WBC is not ANC. Smoke and fluvoxamine still move the level on TDM. Alvir 1993 is agranulocytosis. This desk is not the REMS portal.",
    drugIds: ["clozapine"],
    lane: "clinic",
    blurb: "Clozapine REMS",
  },
  {
    id: "r-inr-amio",
    title: "The INR that climbed in week three",
    setting: "clinic",
    stem: "Warfarin 5 mg, INR 2.3 for a year. Amiodarone started for AF. Week one INR 2.4. Week three 4.8. Nobody changed the milligrams.",
    ask: "Why the delay?",
    teach: "Amiodarone inhibits 2C9 over weeks, not overnight. Put warfarin + amiodarone on the desk and open INR. This desk does not pick a warfarin milligram.",
    drugIds: ["warfarin", "amiodarone"],
    lane: "clinic",
    blurb: "INR · amiodarone",
  },
  {
    id: "r-cyp-rifampin-stop",
    title: "The course that finished too well",
    setting: "clinic",
    stem: "Oral midazolam for a procedure. He finished rifampin for latent TB ten days ago. The anesthesiologist gives the usual milligram. He does not wake on time. Someone says the rifampin is gone.",
    ask: "Is a finished course a clear?",
    teach: "No. Induction dissipates over ~1–2 weeks. Victim levels rebound — sometimes past baseline if a dose was raised while induced. Put rifampin + midazolam on the desk and open CYP → Stop clock. Backman 1996 dumped oral midazolam 96% on rifampin; Backman 1998 still had only 13% of baseline AUC four days after stop. Niemi 2003: remember the stop. This desk is not a milligram.",
    drugIds: ["rifampin", "midazolam"],
    lane: "clinic",
    blurb: "CYP · de-induce",
  },
  {
    id: "r-cyp-clarith-linger",
    title: "The Z-Pak that was not a Z-Pak",
    setting: "ward",
    stem: "Biaxin finished yesterday. Oral Versed this morning for cardioversion. He is still down at hour four. Pharmacy says the macrolide is off the MAR.",
    ask: "Occupancy or destroyed enzyme?",
    teach: "Clarithromycin is mechanism-based 3A4 inactivation. New enzyme has to be made — gut 24–72 h, liver longer. Put clarithromycin + midazolam on the desk. CYP tab should read TDI. A last tablet yesterday is not a free victim day. Open the PI. This desk is not a hold.",
    drugIds: ["clarithromycin", "midazolam"],
    lane: "clinic",
    blurb: "CYP · TDI linger",
  },
  {
    id: "r-cyp-prozac-five-weeks",
    title: "The Prozac that still owned 2D6",
    setting: "clinic",
    stem: "Codeine after a dental extraction. She stopped fluoxetine two weeks ago 'so the painkiller would work.' No analgesia, then jitter and a high parent. Someone wants a 2D6 genotype.",
    ask: "Two weeks — is 2D6 back?",
    teach: "Norfluoxetine keeps 2D6 blocked ~5 weeks. Put fluoxetine + codeine on the desk. CYP stop clock and Pheno both fire. A genotype is not the enzyme she has today. Huang grades the inhibitor; the washout is the clock. This desk does not order a test.",
    drugIds: ["fluoxetine", "codeine"],
    lane: "clinic",
    blurb: "CYP · 5-week 2D6",
  },
  {
    id: "r-ward-mero-vpa",
    title: "The meropenem that stole Depakote",
    setting: "ward",
    stem: "Seizure-free on valproate for a year. Empiric meropenem for hospital-acquired pneumonia. Day two the valproate level is a third of baseline. Someone wants to raise the Depakote.",
    ask: "Is this stacked seizure-lowering, or a different map?",
    teach: "UGT / glucuronide recycling — not CYP, not two seizure-lowering flags. Put meropenem + valproate on the desk. Wards should read contraindicated. Do not 'give a bit more Depakote.' Switch the antibiotic or the AED. Spriet 2007. This desk does not pick a milligram.",
    drugIds: ["meropenem", "valproate"],
    lane: "clinic",
    blurb: "Wards · carbapenem–VPA",
  },
  {
    id: "r-ward-vanco-zosyn",
    title: "The Zosyn piggyback",
    setting: "ward",
    stem: "ICU MRSA coverage: vancomycin plus piperacillin–tazobactam because 'it covers everything.' Creatinine climbs on day four. Pharmacy asks why not cefepime.",
    ask: "Is this boxed, or observational — and does oral vancomycin count?",
    teach: "Observational AKI excess vs vancomycin plus cefepime or a carbapenem. Not a boxed contraindication. Oral vancomycin is a different exposure. Put the pair on the desk. Wards should read major. Luther 2018. Volume, trough, and a narrower beta-lactam — this desk is not a dose.",
    drugIds: ["vancomycin", "piperacillin-tazobactam"],
    lane: "clinic",
    blurb: "Wards · vanco–Zosyn",
  },
  {
    id: "r-ward-entresto",
    title: "The ACEI that stayed on the MAR",
    setting: "ward",
    stem: "HFrEF. Entresto written at discharge. Lisinopril is still on the home list. Pharmacy catches it in the lobby. Someone says 'it's just an ARB combo.'",
    ask: "Washout or potassium?",
    teach: "ARNI × ACE inhibitor is labeled contraindicated — angioedema, 36-hour washout. Not a potassium footnote and not an ARB swap. Put Entresto + lisinopril on the desk. Wards should light. This desk does not time the first tablet.",
    drugIds: ["sacubitril-valsartan", "lisinopril"],
    lane: "clinic",
    blurb: "Wards · ARNI–ACEI",
  },
  {
    id: "r-ward-cape-inr",
    title: "The INR that climbed on Xeloda",
    setting: "clinic",
    stem: "Warfarin 4 mg, INR 2.4 for years. Capecitabine for rectal cancer. Week two INR 5.1. Nobody touched the warfarin milligrams. 2C9 looks quiet on the CYP map.",
    ask: "Why did the INR move if 2C9 did not?",
    teach: "Fluoropyrimidines raise INR on warfarin by a labeled path this desk does not map as 2C9 inhibition. Put capecitabine + warfarin on the desk. Wards and INR both fire. Recheck. This desk does not pick a warfarin milligram.",
    drugIds: ["capecitabine", "warfarin"],
    lane: "clinic",
    blurb: "Wards · Xeloda–warfarin",
  },
  {
    id: "r-ward-glp-aspart",
    title: "The NovoLog that met Ozempic",
    setting: "clinic",
    stem: "Type 2 on insulin aspart. Semaglutide started last month. Fasting glucoses are 50s. Metformin was left alone and nobody cut the bolus.",
    ask: "Is metformin the problem?",
    teach: "GLP-1 agonists rarely cause hypoglycemia alone. Next to insulin they do. Metformin on this desk stays quieter. Put semaglutide + insulin aspart on the desk. Wards should name the pair. This desk does not cut the insulin.",
    drugIds: ["semaglutide", "insulin-aspart"],
    lane: "clinic",
    blurb: "Wards · GLP–insulin",
  },
  {
    id: "r-dose-simva-amio",
    title: "The 40 that should have been 20",
    setting: "clinic",
    stem: "Simvastatin 40 mg for years. Amiodarone started for AF. CK is normal. Pharmacy pages: the label caps simvastatin at 20 next to amiodarone. Someone says the CYP map already fired.",
    ask: "Is a collision the same as a milligram cap?",
    teach: "No. The pair is allowed — the milligram is not. Put simvastatin + amiodarone on the desk, type 40 on Dose. The rail should cross the 20 mg cap. Zocor PI, not a CYP fold-change. This desk checked the milligram you typed. It does not pick 20 for you.",
    drugIds: ["simvastatin", "amiodarone"],
    lane: "clinic",
    blurb: "Dose · simva 20 mg cap",
    doses: { simvastatin: "40" },
  },
  {
    id: "r-dose-mtx-weekly",
    title: "The methotrexate that was not daily",
    setting: "clinic",
    stem: "RA. Methotrexate 15 mg. The SIG says daily. Folate is on the list. The ISMP alert is the weekly trap, not a CYP row.",
    ask: "What is the usual rail?",
    teach: "RA/psoriasis is once weekly, 7.5–25 mg. Daily methotrexate is oncology or a wrong fill. Put methotrexate on the desk and open Dose. Type 15 — in-range only if the schedule is weekly. This desk does not rewrite the SIG.",
    drugIds: ["methotrexate"],
    lane: "clinic",
    blurb: "Dose · weekly MTX",
    doses: { methotrexate: "15" },
  },
  {
    id: "r-safety-epclusa-amio",
    title: "The DAA that stopped the heart",
    setting: "clinic",
    stem: "AF on amiodarone. New pan-genotypic HCV regimen — Epclusa. Week two: syncope, HR 32. Pharmacy asks why sofosbuvir is on the same MAR as Cordarone.",
    ask: "Is this stacked nodal PD, or a boxed pair this desk was missing?",
    teach: "Sofosbuvir plus amiodarone is labeled for serious symptomatic bradycardia. Epclusa is not bradycardic on the PD map — the generic brady row would have been the wrong mechanism. Put Epclusa + amiodarone on the desk. Wards should read contraindicated. FDA 2015. This desk does not time the first tablet.",
    drugIds: ["epclusa", "amiodarone"],
    lane: "clinic",
    blurb: "Wards · sofosbuvir–amio",
  },
  {
    id: "r-safety-clozapine-ativan",
    title: "The Ativan that was not a free extra",
    setting: "ward",
    stem: "Clozapine 300 mg. Night lorazepam for agitation. The patient is found unresponsive, breathing slowly. Someone says 'two sedatives.' ANC is fine.",
    ask: "Generic CNS, or the boxed respiratory-collapse row?",
    teach: "Clozapine labels warn of respiratory arrest with benzodiazepines, including deaths. Not stacked GABA. Put clozapine + lorazepam on the desk. Wards should read contraindicated, not moderate CNS. Zolpidem is a different GABA-A row. This desk is not a hold clock.",
    drugIds: ["clozapine", "lorazepam"],
    lane: "clinic",
    blurb: "Wards · clozapine–benzo",
  },
  {
    id: "r-safety-asa-ibu",
    title: "The Advil that stole the aspirin",
    setting: "clinic",
    stem: "81 mg aspirin for a stent. Ibuprofen 400 mg three times a day for a knee. No bleed. Someone calls it two NSAIDs.",
    ask: "Bleed, or lost cardioprotection?",
    teach: "Ibuprofen occupies COX-1 and can block aspirin's irreversible acetylation. Lost antiplatelet effect — Catella-Lawson 2001 — plus GI bleed as a separate row. Put aspirin + ibuprofen on the desk. Wards should name attenuation. Acetaminophen does not do this. This desk does not time the tablets.",
    drugIds: ["aspirin", "ibuprofen"],
    lane: "clinic",
    blurb: "Wards · ASA–ibuprofen",
  },
  {
    id: "r-safety-lamo-vpa",
    title: "The starter kit that was not 25",
    setting: "clinic",
    stem: "Bipolar on valproate. Lamotrigine 25 mg daily started 'the usual way.' Week two: a spreading rash. Someone wants to push through.",
    ask: "Stacked GABA, or UGT?",
    teach: "Valproate inhibits UGT and roughly doubles lamotrigine. The starter kit is slower for a reason — SJS/TEN, not stacked sedation. Put lamotrigine + valproate on the desk. Wards should name the pair. This desk does not pick the milligram. Yuen 1992.",
    drugIds: ["lamotrigine", "valproate"],
    lane: "clinic",
    blurb: "Wards · Lamictal–Depakote",
  },
  {
    id: "r-safety-cipro-pred",
    title: "The Achilles that met Cipro",
    setting: "clinic",
    stem: "COPD flare: prednisone 40 mg. UTI: ciprofloxacin. Day five the Achilles pops. Prednisone has no PD flags on the map. Someone says the desk missed it.",
    ask: "Why was prednisone empty — and what should fire?",
    teach: "Empty PD is on purpose. The fluoroquinolone boxed tendon row is named, not stacked GABA. Risk climbs with concomitant corticosteroids. Put cipro + prednisone on the desk. Wards should read major. Stop the FQ at the first tendon pain. This desk does not pick the replacement antibiotic.",
    drugIds: ["ciprofloxacin", "prednisone"],
    lane: "clinic",
    blurb: "Wards · FQ–steroid",
  },
  {
    id: "r-safety-dual-raas",
    title: "The ARB that stayed with the ACEI",
    setting: "clinic",
    stem: "Lisinopril 20. Someone adds losartan 'for the proteinuria.' K 5.8, Cr up 0.4. They say Entresto needs a 36-hour washout so this must be fine.",
    ask: "Is dual ACEI+ARB the Entresto row?",
    teach: "No. Entresto plus an ACE inhibitor is angioedema / 36 hours. Dual ACEI+ARB is ONTARGET / VA NEPHRON-D — more hyperK, hypotension, AKI without outcome gain. Put lisinopril + losartan on the desk. Wards should read contraindicated. This desk does not pick which agent stays.",
    drugIds: ["lisinopril", "losartan"],
    lane: "clinic",
    blurb: "Wards · dual RAAS",
  },
  {
    id: "r-safety-ocp-rifampin",
    title: "The pill that met rifampin",
    setting: "clinic",
    stem: "Latent TB. Rifampin for four months. Combined OCP for years. She asks if she should 'just take two pills.'",
    ask: "Quieter pill, or a different method?",
    teach: "Strong inducers dump ethinyl estradiol. The CYP map already fires 3A4 induction; Wards names the counseling — backup or a non-CYP method, not a quieter pill. Put ethinyl estradiol + rifampin on the desk. Niemi 2003. This desk does not pick a method.",
    drugIds: ["ethinyl-estradiol", "rifampin"],
    lane: "clinic",
    blurb: "Wards · OCP–rifampin",
  },
  {
    id: "r-safety-tamoxifen-paxil",
    title: "The Paxil that stole endoxifen",
    setting: "clinic",
    stem: "ER+ breast cancer on tamoxifen. Hot flashes: paroxetine. Two years later a recurrence. Someone wants a 2D6 genotype.",
    ask: "Is the SSRI a phenocopy of a 2D6 PM?",
    teach: "Yes. Tamoxifen needs 2D6 to make endoxifen. Paroxetine is a strong 2D6 inhibitor — the CYP map fires activation block; Wards names the oncology call. Switch the SSRI. Do not give more tamoxifen. CPIC. This desk does not order a test.",
    drugIds: ["tamoxifen", "paroxetine"],
    lane: "clinic",
    blurb: "Wards · tamoxifen–2D6",
  },
  {
    id: "r-hr-tranq",
    title: "Naloxone did half the job",
    setting: "street",
    stem: "Pressed 30. Two naloxone doses bring some breaths back. They stay down, bradycardic, skin cold. The fold later tests fentanyl and xylazine.",
    ask: "What did naloxone reverse, and what is the rest?",
    teach: "μ-agonist apnea reversed. α2 residual did not. Put fentanyl + xylazine on the desk. HR tab: extra Narcan is not extra xylazine reversal. Airway, stay, recovery position. This desk is not a field protocol.",
    drugIds: ["fentanyl", "xylazine"],
    lane: "street",
    blurb: "HR · α2 residual",
  },
  {
    id: "r-hr-mdma-water",
    title: "The water that was not enough — and then too much",
    setting: "street",
    stem: "Festival. Hot. A pressed Mitsubishi. Hour two they redose because 'nothing happened.' Hour four they are rigid, then they chug water. Seizure.",
    ask: "Heat, PMA, or hyponatremia — which desk rows fire?",
    teach: "All three are the teaching. Put MDMA on the desk. HR names delayed-onset PMA/PMMA, sip-don't-chug, and 'you cannot take less.' Marquis is a class clue, not a milligram. This desk does not pick one.",
    drugIds: ["mdma"],
    lane: "street",
    blurb: "HR · MDMA heat / water",
  },
  {
    id: "r-hr-ghb",
    title: "The extra capful",
    setting: "street",
    stem: "Sodium oxybate at a party. A second capful because the first felt light. Alcohol on the table. They are unresponsive in ten minutes.",
    ask: "Is there a reversal, and how do they not aspirate?",
    teach: "No naloxone for GHB. Put sodium oxybate + ethanol on the desk — labeled contraindicated. HR: steep curve, recovery position, stay. PsychonautWiki GHB. This desk does not pick a milliliter.",
    drugIds: ["sodium-oxybate", "ethanol"],
    lane: "gaba",
    blurb: "HR · GHB steep curve",
  },
  {
    id: "r-hr-ketamine-swim",
    title: "Do not swim",
    setting: "street",
    stem: "After a K-hole they 'feel fine' and walk toward the lake. A beer from earlier is still on board. Someone asks if the CYP tab matters.",
    ask: "What does PsychonautWiki name that this desk should not miss?",
    teach: "Do not swim. Alcohol × ketamine is a TripSit dangerous pair — vomiting plus a lost airway, not a 3A4 row. Put ketamine + ethanol on the desk. HR: recovery position, sitter, wiki monograph. This desk does not pick a milligram.",
    drugIds: ["ketamine", "ethanol"],
    lane: "nmda",
    blurb: "HR · dissociative × alcohol",
  },
  {
    id: "r-hr-mdma-maoi",
    title: "The Nardil they did not mention",
    setting: "clinic",
    stem: "Festival. MDMA. They take phenelzine for depression and did not think it counted. Rigid, febrile, clonus.",
    ask: "Is this a CYP story or a wiki deadly cell?",
    teach: "TripSit / PsychonautWiki: MDMA × MAOI is deadly — serotonin toxicity. Put MDMA + phenelzine on the desk. Hunter tab. HR names the combo. This desk does not pick a milligram and does not treat the syndrome.",
    drugIds: ["mdma", "phenelzine"],
    lane: "entactogen",
    blurb: "HR · MDMA × MAOI",
  },
  {
    id: "r-ux-semaglutide-delay",
    title: "The weekly shot that slowed the pill",
    setting: "clinic",
    stem: "New weekly semaglutide. Two weeks later their oral contraceptive timing feels off and a once-daily thyroid tablet seems less predictable. Someone asks if the CYP map will light up.",
    ask: "Is this a CYP story or a gut-emptying story?",
    teach: "GLP-1 agonists slow gastric emptying. Put semaglutide on the desk with ethinyl estradiol if you want the counseling frame — many findings here are timing and absorption, not a classic 3A4 row. This desk does not pick a milligram or a method.",
    drugIds: ["semaglutide", "ethinyl-estradiol"],
    lane: "clinic",
    blurb: "GLP-1 · emptying vs CYP",
  },
  {
    id: "r-ux-tramadol-prozac",
    title: "The pain pill that stacked serotonin",
    setting: "ward",
    stem: "Post-op tramadol. Home fluoxetine continued. Day two they are sweaty, restless, and hyperreflexic. No fever yet.",
    ask: "Is this 2D6 parent stack, serotonergic PD, or both?",
    teach: "Both. Tramadol is a 2D6 activation story and a serotonergic agent; fluoxetine is a strong 2D6 inhibitor and an SSRI. Put tramadol + fluoxetine on the desk and read PK and PD together. This desk does not treat the syndrome.",
    drugIds: ["tramadol", "fluoxetine"],
    lane: "clinic",
    blurb: "Tramadol × SSRI",
  },
  {
    id: "r-ux-simvastatin-itraconazole",
    title: "The statin that met the azole",
    setting: "clinic",
    stem: "Stable simvastatin. New itraconazole for onychomycosis. Week two: dark urine and aching thighs.",
    ask: "Which enzyme makes this a labeled avoid, not a dose nudge?",
    teach: "Strong CYP3A4 inhibition plus a sensitive 3A4 statin. Put simvastatin + itraconazole on the desk — the map should name the pair and the counseling frame. This desk does not pick an alternative statin.",
    drugIds: ["simvastatin", "itraconazole"],
    lane: "clinic",
    blurb: "3A4 statin × azole",
  },
  {
    id: "r-ux-clopidogrel-omeprazole",
    title: "The PPI that quieted the prodrug",
    setting: "ward",
    stem: "Post-stent clopidogrel. Omeprazole for reflux. Someone asks if any PPI is fine.",
    ask: "Activation block or just acid?",
    teach: "Clopidogrel needs CYP2C19 to become active. Omeprazole is a 2C19 inhibitor — a phenocopy of a reduced metabolizer. Put clopidogrel + omeprazole on the desk. This desk does not pick a PPI.",
    drugIds: ["clopidogrel", "omeprazole"],
    lane: "clinic",
    blurb: "2C19 activation block",
  },
];
