import type { AlcoholPattern, CannabisRoute, KetamineRoute, PhenotypeMap } from "./types";

export type SampleLane = "nmda" | "entactogen" | "gaba" | "phenotype" | "smoke" | "mat" | "food" | "street" | "clinic";

export function sampleNeedsPro(s: SampleRegimen) {
  // Ketamine route (oral / IN) is free so oral × grapefruit teaching works without a key.
  // Phenotype, smoke, alcohol, and cannabis route stay licensed.
  return Boolean(s.phenotypes || s.smoking || s.alcohol || s.cannabisRoute);
}

export interface SampleRegimen {
  id: string;
  title: string;
  blurb: string;
  drugIds: string[];
  lane: SampleLane;
  phenotypes?: Partial<PhenotypeMap>;
  smoking?: boolean;
  ketamineRoute?: KetamineRoute;
  cannabisRoute?: CannabisRoute;
  alcohol?: AlcoholPattern;
  doses?: Record<string, string>;
}

export const SAMPLE_LANES: { id: SampleLane | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "nmda", label: "Ketamine & related" },
  { id: "entactogen", label: "MDMA & stimulants" },
  { id: "gaba", label: "Sedatives & alcohol" },
  { id: "phenotype", label: "Metabolizer status" },
  { id: "smoke", label: "Smoking effects" },
  { id: "mat", label: "Opioid treatment (MAT)" },
  { id: "food", label: "Food & herbs" },
  { id: "street", label: "Street supply" },
  { id: "clinic", label: "Clinic staples" },
];

/** Window-first order when the MAT / OTP board is open. */
export const WINDOW_PIN = [
  "methadone-fentanyl",
  "uds-methadone",
  "methadone-paxlovid",
  "bup-paxlovid",
  "fentanyl-paxlovid",
  "methadone-fluvoxamine",
  "methadone-phenytoin",
  "methadone-carbamazepine",
  "methadone-rifampin",
  "methadone-azithromycin",
  "methadone-phenergan",
  "methadone-hydroxyzine",
  "methadone-clonazepam",
  "bup-fentanyl",
  "nalmefene-fent",
  "methadone-fent-xylazine",
  "methadone-epclusa",
  "methadone-cobicistat",
  "naltrexone-fentanyl",
  "methadone-ciprofloxacin",
  "uds-seroquel",
  "cows-lofexidine",
  "otp-induction",
  "vivitrol-methadone",
];

export function samplesInLane(lane: SampleLane | "all") {
  const rows = SAMPLE_REGIMENS.filter((s) => lane === "all" || s.lane === lane);
  if (lane !== "mat") return rows;
  const rank = new Map(WINDOW_PIN.map((id, i) => [id, i]));
  return [...rows].sort((a, b) => (rank.get(a.id) ?? 500) - (rank.get(b.id) ?? 500));
}

export const SAMPLE_REGIMENS: SampleRegimen[] = [
  {
    id: "ketamine-3a4",
    title: "Oral ketamine + clarithromycin",
    blurb: "Swallowed ketamine meets a gut enzyme; often stronger interaction than IV",
    drugIds: ["ketamine", "clarithromycin"],
    lane: "nmda",
    ketamineRoute: "oral",
  },
  {
    id: "ketamine-benzo",
    title: "Ketamine + alprazolam",
    blurb: "NMDA + GABA — airway risk, blunted antidepressant effect",
    drugIds: ["ketamine", "alprazolam"],
    lane: "nmda",
  },
  {
    id: "esketamine-rifampin",
    title: "Esketamine + rifampin",
    blurb: "Strong 2B6/3A4 induction, loss of esketamine exposure",
    drugIds: ["esketamine", "rifampin"],
    lane: "nmda",
    ketamineRoute: "in",
  },
  {
    id: "mdma-maoi",
    title: "MDMA + phenelzine",
    blurb: "Entactogen × irreversible MAOI — contraindicated",
    drugIds: ["mdma", "phenelzine"],
    lane: "entactogen",
  },
  {
    id: "mdma-2d6",
    title: "MDMA + paroxetine",
    blurb: "2D6 blockade plus stacked serotonin",
    drugIds: ["mdma", "paroxetine"],
    lane: "entactogen",
  },
  {
    id: "dxm-ssri",
    title: "DXM + sertraline",
    blurb: "Sensitive 2D6 substrate meets an SSRI",
    drugIds: ["dextromethorphan", "sertraline"],
    lane: "nmda",
  },
  {
    id: "dxm-quinidine",
    title: "DXM + quinidine",
    blurb: "Nuedexta pair — strong 2D6 inhibition of DXM",
    drugIds: ["dextromethorphan", "quinidine"],
    lane: "nmda",
  },
  {
    id: "alcohol-opioid-benzo",
    title: "Alcohol + opioid + benzo",
    blurb: "Three-drug CNS stack — respiratory depression",
    drugIds: ["ethanol", "oxycodone", "alprazolam"],
    lane: "gaba",
  },
  {
    id: "cbd-clobazam",
    title: "CBD + clobazam",
    blurb: "Strong CYP2C19 inhibition of a sensitive benzo",
    drugIds: ["cannabidiol", "clobazam"],
    lane: "gaba",
  },
  {
    id: "cocaine-alcohol",
    title: "Cocaine + ethanol",
    blurb: "Cocaethylene — longer-lived cardiotoxin",
    drugIds: ["cocaine", "ethanol"],
    lane: "street",
  },
  {
    id: "lithium-psilocybin",
    title: "Lithium + psilocybin",
    blurb: "Classic psychedelic × lithium seizure signal",
    drugIds: ["lithium", "psilocybin"],
    lane: "entactogen",
  },
  {
    id: "naltrexone-opioid",
    title: "Naltrexone + oxycodone",
    blurb: "Antagonist precipitates withdrawal, blocks analgesia",
    drugIds: ["naltrexone", "oxycodone"],
    lane: "mat",
  },
  {
    id: "ghb-alcohol",
    title: "Sodium oxybate + alcohol",
    blurb: "Labeled contraindication — coma / apnea",
    drugIds: ["sodium-oxybate", "ethanol"],
    lane: "gaba",
  },
  {
    id: "dxm-2d6pm",
    title: "DXM in a 2D6 PM",
    blurb: "Poor metabolizer = stacked parent without a perpetrator drug",
    drugIds: ["dextromethorphan"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "PM" },
  },
  {
    id: "ketamine-2b6pm",
    title: "Ketamine in a 2B6 PM",
    blurb: "Slow norketamine formation, higher parent NMDA load",
    drugIds: ["ketamine"],
    lane: "phenotype",
    phenotypes: { CYP2B6: "PM" },
  },
  {
    id: "codeine-2d6um",
    title: "Codeine in a 2D6 UM",
    blurb: "Ultrarapid activation to morphine — labeled risk",
    drugIds: ["codeine"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "UM" },
  },
  {
    id: "smoke-clozapine",
    title: "Clozapine + daily smoke",
    blurb: "PAHs induce 1A2 — clozapine levels fall, rebound on quit",
    drugIds: ["clozapine"],
    lane: "smoke",
    smoking: true,
  },
  {
    id: "ibogaine-methadone",
    title: "Ibogaine + methadone",
    blurb: "2D6 victim plus stacked QT — a documented fatality pattern",
    drugIds: ["ibogaine", "methadone"],
    lane: "nmda",
  },
  {
    id: "gf-oral-ketamine",
    title: "Grapefruit + oral ketamine",
    blurb: "Intestinal 3A4 knockout — IV barely moves, oral does",
    drugIds: ["grapefruit", "ketamine"],
    lane: "food",
    ketamineRoute: "oral",
  },
  {
    id: "gf-buspirone",
    title: "Grapefruit + buspirone",
    blurb: "Classic furanocoumarin × sensitive 3A4 anxiolytic",
    drugIds: ["grapefruit", "buspirone"],
    lane: "food",
  },
  {
    id: "tacrolimus-gf",
    title: "Tacrolimus + grapefruit",
    blurb: "NTI 3A4 victim × intestinal knockout — F rises, t½ does not",
    drugIds: ["tacrolimus", "grapefruit"],
    lane: "food",
  },
  {
    id: "tyramine-maoi",
    title: "Tyramine foods + phenelzine",
    blurb: "Aged cheese / tap beer × irreversible MAOI",
    drugIds: ["tyramine-foods", "phenelzine"],
    lane: "food",
  },
  {
    id: "dairy-cipro",
    title: "Milk + ciprofloxacin",
    blurb: "Dietary calcium — the course never arrives",
    drugIds: ["dairy", "ciprofloxacin"],
    lane: "food",
  },
  {
    id: "kale-warfarin",
    title: "Kale + warfarin",
    blurb: "Phylloquinone smoothie — INR falls, not 2C9",
    drugIds: ["leafy-greens", "warfarin"],
    lane: "food",
  },
  {
    id: "oj-allegra",
    title: "Apple juice + fexofenadine",
    blurb: "OATP, not CYP — Allegra never arrives",
    drugIds: ["oatp-juice", "fexofenadine"],
    lane: "food",
  },
  {
    id: "coffee-synthroid",
    title: "Coffee + levothyroxine",
    blurb: "Benvenga — espresso with the morning dose empties TSH",
    drugIds: ["coffee", "levothyroxine"],
    lane: "food",
  },
  {
    id: "protein-sinemet",
    title: "Protein meal + levodopa",
    blurb: "LAT1 competition — lost 'on' time, not CYP",
    drugIds: ["protein-meal", "levodopa"],
    lane: "food",
  },
  {
    id: "gf-felodipine",
    title: "Grapefruit + felodipine",
    blurb: "Bailey 1991 — the paper that put juice on the CYP map",
    drugIds: ["grapefruit", "felodipine"],
    lane: "food",
  },
  {
    id: "sjw-sertraline",
    title: "St. John's wort + sertraline",
    blurb: "3A4 induction plus stacked serotonin",
    drugIds: ["st-johns-wort", "sertraline"],
    lane: "food",
  },
  {
    id: "fat-dronabinol",
    title: "High-fat meal + THC",
    blurb: "Fed-state jump in oral cannabinoid AUC",
    drugIds: ["high-fat-meal", "dronabinol"],
    lane: "food",
  },
  {
    id: "lithium-low-salt",
    title: "Lithium + low salt",
    blurb: "Sodium restriction retains lithium",
    drugIds: ["lithium", "low-salt"],
    lane: "food",
  },
  {
    id: "lithium-ibuprofen",
    title: "Lithium + ibuprofen",
    blurb: "NSAID retains lithium — TDM, not CYP",
    drugIds: ["lithium", "ibuprofen"],
    lane: "clinic",
  },
  {
    id: "kratom-benzo",
    title: "Kratom + alprazolam",
    blurb: "Atypical opioid × benzo — airway stack",
    drugIds: ["kratom", "alprazolam"],
    lane: "mat",
  },
  {
    id: "phenibut-alcohol",
    title: "Phenibut + alcohol",
    blurb: "GABA-B analogue plus ethanol — stacked sedation",
    drugIds: ["phenibut", "ethanol"],
    lane: "gaba",
  },
  {
    id: "chronic-apap",
    title: "Acetaminophen + chronic alcohol",
    blurb: "Induced 2E1 → NAPQI; glutathione already low",
    drugIds: ["acetaminophen"],
    lane: "smoke",
    alcohol: "chronic",
  },
  {
    id: "edible-thc-2c9",
    title: "Edible THC + fluconazole",
    blurb: "11-OH-THC first-pass meets strong CYP2C9 inhibition",
    drugIds: ["dronabinol", "fluconazole"],
    lane: "food",
    cannabisRoute: "oral",
  },
  {
    id: "xylazine-fentanyl",
    title: "Xylazine + fentanyl",
    blurb: "α2 sedation naloxone will not reverse",
    drugIds: ["xylazine", "fentanyl"],
    lane: "street",
  },
  {
    id: "gbl-alcohol",
    title: "GBL + alcohol",
    blurb: "GHB prodrug × ethanol — labeled apnea",
    drugIds: ["gbl", "ethanol"],
    lane: "street",
  },
  {
    id: "mephedrone-maoi",
    title: "Mephedrone + phenelzine",
    blurb: "Cathinone × irreversible MAOI",
    drugIds: ["mephedrone", "phenelzine"],
    lane: "street",
  },
  {
    id: "bromazolam-oxy",
    title: "Bromazolam + oxycodone",
    blurb: "Designer benzo × opioid — boxed airway warning",
    drugIds: ["bromazolam", "oxycodone"],
    lane: "street",
  },
  {
    id: "npe-benzo",
    title: "N-Pyrrolidino etonitazene + bromazolam",
    blurb: "Hot nitazene × designer benzo — airway stack naloxone only partly covers",
    drugIds: ["n-pyrrolidino-etonitazene", "bromazolam"],
    lane: "street",
  },
  {
    id: "brorphine-xylazine",
    title: "Brorphine + xylazine",
    blurb: "Pressed-tablet opioid × α2 — naloxone will not reverse the xylazine",
    drugIds: ["brorphine", "xylazine"],
    lane: "street",
  },
  {
    id: "eutylone-maoi",
    title: "Eutylone + phenelzine",
    blurb: "Molly adulterant cathinone × irreversible MAOI",
    drugIds: ["eutylone", "phenelzine"],
    lane: "street",
  },
  {
    id: "flubromazepam-oxy",
    title: "Flubromazepam + oxycodone",
    blurb: "Long RC benzo × opioid — delayed blackout and airway risk",
    drugIds: ["flubromazepam", "oxycodone"],
    lane: "street",
  },
  {
    id: "u47700-alprazolam",
    title: "U-47700 + alprazolam",
    blurb: "RC opioid × benzo airway stack",
    drugIds: ["u-47700", "alprazolam"],
    lane: "street",
  },
  {
    id: "cariprazine-clarithro",
    title: "Cariprazine + clarithromycin",
    blurb: "Vraylar meets a strong 3A4 macrolide",
    drugIds: ["cariprazine", "clarithromycin"],
    lane: "clinic",
  },
  {
    id: "daridorexant-ritonavir",
    title: "Daridorexant + ritonavir",
    blurb: "Orexin sleep drug meets a strong 3A4 booster",
    drugIds: ["daridorexant", "ritonavir"],
    lane: "clinic",
  },
  {
    id: "letermovir-tacrolimus",
    title: "Letermovir + tacrolimus",
    blurb: "CMV prophylaxis raises calcineurin exposure — TDM story",
    drugIds: ["letermovir", "tacrolimus"],
    lane: "clinic",
  },
  {
    id: "zuranolone-oxy",
    title: "Zuranolone + oxycodone",
    blurb: "Neurosteroid GABA PAM × opioid CNS depression",
    drugIds: ["zuranolone", "oxycodone"],
    lane: "clinic",
  },
  {
    id: "lenacapavir-midazolam",
    title: "Lenacapavir + oral midazolam",
    blurb: "Long-acting capsid inhibitor as a moderate 3A4 perpetrator",
    drugIds: ["lenacapavir", "midazolam"],
    lane: "clinic",
  },
  {
    id: "loperamide-quinidine",
    title: "Loperamide + quinidine",
    blurb: "P-gp knockout turns Imodium into a central opioid",
    drugIds: ["loperamide", "quinidine"],
    lane: "street",
  },
  {
    id: "twofdck-gf",
    title: "2-FDCK + grapefruit",
    blurb: "Oral arylcyclohexylamine meets intestinal 3A4 knockout",
    drugIds: ["two-fdck", "grapefruit"],
    lane: "street",
    ketamineRoute: "oral",
  },
  {
    id: "poppers-sildenafil",
    title: "Poppers + sildenafil",
    blurb: "Nitrate × PDE5 — labeled collapse",
    drugIds: ["poppers", "sildenafil"],
    lane: "street",
  },
  {
    id: "mxe-alprazolam",
    title: "MXE + alprazolam",
    blurb: "Long NMDA dissociative × benzo airway stack",
    drugIds: ["mxe", "alprazolam"],
    lane: "nmda",
  },
  {
    id: "dck-gf",
    title: "DCK + grapefruit",
    blurb: "Oral deschloroketamine meets intestinal 3A4 knockout",
    drugIds: ["dck", "grapefruit"],
    lane: "nmda",
    ketamineRoute: "oral",
  },
  {
    id: "three-meo-benzo",
    title: "3-MeO-PCP + alprazolam",
    blurb: "Long arylcyclohexylamine × benzo airway stack",
    drugIds: ["three-meo-pcp", "alprazolam"],
    lane: "nmda",
  },
  {
    id: "mda-maoi",
    title: "MDA + phenelzine",
    blurb: "MDMA cousin × irreversible MAOI",
    drugIds: ["mda", "phenelzine"],
    lane: "entactogen",
  },
  {
    id: "methylone-2d6",
    title: "Methylone + paroxetine",
    blurb: "Cathinone 2D6 victim plus stacked serotonin",
    drugIds: ["methylone", "paroxetine"],
    lane: "entactogen",
  },
  {
    id: "nbome-lithium",
    title: "25I-NBOMe + lithium",
    blurb: "Street blotter × lithium seizure signal",
    drugIds: ["twentyfive-i", "lithium"],
    lane: "street",
  },
  {
    id: "clonazolam-fent",
    title: "Clonazolam + fentanyl",
    blurb: "High-potency RC benzo × opioid — boxed airway",
    drugIds: ["clonazolam", "fentanyl"],
    lane: "street",
  },
  {
    id: "apvp-maoi",
    title: "α-PVP + phenelzine",
    blurb: "Pyrovalerone stimulant × irreversible MAOI",
    drugIds: ["a-pvp", "phenelzine"],
    lane: "street",
  },
  {
    id: "scopolamine-dph",
    title: "Scopolamine + diphenhydramine",
    blurb: "Tropane × antihistamine — stacked delirium",
    drugIds: ["scopolamine", "diphenhydramine"],
    lane: "street",
  },
  {
    id: "meperidine-maoi",
    title: "Meperidine + phenelzine",
    blurb: "Labeled MAOI contraindication — serotonin + seizures",
    drugIds: ["meperidine", "phenelzine"],
    lane: "clinic",
  },
  {
    id: "cimetidine-tizanidine",
    title: "Cimetidine + tizanidine",
    blurb: "OTC 1A2 bully × sensitive 1A2 muscle relaxant",
    drugIds: ["cimetidine", "tizanidine"],
    lane: "clinic",
  },
  {
    id: "pheno-ocp",
    title: "Phenobarbital + OCP",
    blurb: "Pan-CYP induction — contraceptive failure",
    drugIds: ["phenobarbital", "ethinyl-estradiol"],
    lane: "clinic",
  },
  {
    id: "efavirenz-methadone",
    title: "Efavirenz + methadone",
    blurb: "2B6/3A4 induction precipitates opioid withdrawal",
    drugIds: ["efavirenz", "methadone"],
    lane: "clinic",
  },
  {
    id: "pimozide-clarith",
    title: "Pimozide + clarithromycin",
    blurb: "Sensitive 3A4 QT drug × strong 3A4 inhibitor",
    drugIds: ["pimozide", "clarithromycin"],
    lane: "clinic",
  },
  {
    id: "thioridazine-fluox",
    title: "Thioridazine + fluoxetine",
    blurb: "2D6 PM-like blockade of a boxed QT drug",
    drugIds: ["thioridazine", "fluoxetine"],
    lane: "clinic",
  },
  {
    id: "tapentadol-ssri",
    title: "Tapentadol + sertraline",
    blurb: "μ-agonist plus NRI meets an SSRI",
    drugIds: ["tapentadol", "sertraline"],
    lane: "clinic",
  },
  {
    id: "disulfiram-etoh",
    title: "Disulfiram + alcohol",
    blurb: "ALDH block — the acetaldehyde reaction",
    drugIds: ["disulfiram", "ethanol"],
    lane: "clinic",
  },
  {
    id: "warfarin-2c9pm",
    title: "Warfarin in a 2C9 PM",
    blurb: "Sensitive 2C9 substrate without a perpetrator drug",
    drugIds: ["warfarin"],
    lane: "phenotype",
    phenotypes: { CYP2C9: "PM" },
  },
  {
    id: "carisoprodol-2c19pm",
    title: "Carisoprodol in a 2C19 PM",
    blurb: "Meprobamate activation plus stacked parent",
    drugIds: ["carisoprodol"],
    lane: "phenotype",
    phenotypes: { CYP2C19: "PM" },
  },
  {
    id: "piperine-ketamine",
    title: "Piperine + oral ketamine",
    blurb: "Black-pepper 3A4/P-gp block on a first-pass victim",
    drugIds: ["piperine", "ketamine"],
    lane: "food",
    ketamineRoute: "oral",
  },
  {
    id: "licorice-sotalol",
    title: "Licorice + sotalol",
    blurb: "Glycyrrhizin hypokalemia plus a known QT drug",
    drugIds: ["licorice", "sotalol"],
    lane: "food",
  },
  {
    id: "starfruit-simva",
    title: "Star fruit + simvastatin",
    blurb: "Furanocoumarin-adjacent 3A4 hit on a sensitive statin",
    drugIds: ["starfruit", "simvastatin"],
    lane: "food",
  },
  {
    id: "ginkgo-warfarin",
    title: "Ginkgo + warfarin",
    blurb: "Herbal antiplatelet on a narrow-index anticoagulant",
    drugIds: ["ginkgo", "warfarin"],
    lane: "food",
  },
  {
    id: "clonidine-oxy",
    title: "Clonidine + oxycodone",
    blurb: "Clinical α2 agonist — naloxone will not fully reverse",
    drugIds: ["clonidine", "oxycodone"],
    lane: "mat",
  },
  {
    id: "dexmed-fent",
    title: "Dexmedetomidine + fentanyl",
    blurb: "Precedex α2 × opioid — naloxone will not reverse the α2",
    drugIds: ["dexmedetomidine", "fentanyl"],
    lane: "clinic",
  },
  {
    id: "propofol-midaz",
    title: "Propofol + midazolam",
    blurb: "IV anesthetic plus 3A4 benzo — stacked apnea",
    drugIds: ["propofol", "midazolam"],
    lane: "clinic",
  },
  {
    id: "prazosin-etoh",
    title: "Prazosin + alcohol",
    blurb: "α1 blockade plus ethanol — orthostatic syncope",
    drugIds: ["prazosin", "ethanol"],
    lane: "clinic",
  },
  {
    id: "sevenoh-benzo",
    title: "7-OH + alprazolam",
    blurb: "Hot kratom μ-agonist × benzo airway stack",
    drugIds: ["seven-oh", "alprazolam"],
    lane: "street",
  },
  {
    id: "primidone-ocp",
    title: "Primidone + OCP",
    blurb: "Barbiturate prodrug — contraceptive failure",
    drugIds: ["primidone", "ethinyl-estradiol"],
    lane: "clinic",
  },
  {
    id: "famotidine-tizanidine",
    title: "Famotidine + tizanidine",
    blurb: "The H2 that is not cimetidine — CYP row should stay quiet",
    drugIds: ["famotidine", "tizanidine"],
    lane: "clinic",
  },
  {
    id: "etonitazene-xylazine",
    title: "Etonitazene + xylazine",
    blurb: "Nitazene plus α2 — naloxone will not finish the job",
    drugIds: ["etonitazene", "xylazine"],
    lane: "street",
  },
  {
    id: "guanfacine-ritonavir",
    title: "Guanfacine + ritonavir",
    blurb: "ADHD α2 meets a strong 3A4 inhibitor",
    drugIds: ["guanfacine", "ritonavir"],
    lane: "clinic",
  },
  {
    id: "aprepitant-ketamine",
    title: "Aprepitant + oral ketamine",
    blurb: "NK1 antiemetic as a 3A4 perpetrator on a first-pass victim",
    drugIds: ["aprepitant", "ketamine"],
    lane: "clinic",
    ketamineRoute: "oral",
  },
  {
    id: "speedball-fent",
    title: "Speedball — cocaine + fentanyl",
    blurb: "Stimulant masks apnea; the opioid still stops the breathing",
    drugIds: ["cocaine", "fentanyl"],
    lane: "street",
  },
  {
    id: "percocet-alcohol",
    title: "Percocet + chronic alcohol",
    blurb: "Oxycodone + APAP on induced 2E1 — airway plus NAPQI",
    drugIds: ["oxycodone", "acetaminophen"],
    lane: "street",
    alcohol: "chronic",
  },
  {
    id: "dirty-30",
    title: "Dirty 30s (pressed M30 + xylazine)",
    blurb: "The stamp is oxycodone. The contents are not.",
    drugIds: ["dirty-30", "xylazine"],
    lane: "street",
  },
  {
    id: "perc-vs-pressed",
    title: "Perc 30 vs pressed 30",
    blurb: "Pharmaceutical oxycodone next to illicit fentanyl + tranq",
    drugIds: ["oxycodone", "fentanyl", "xylazine"],
    lane: "street",
  },
  {
    id: "speedball-heroin",
    title: "Classic speedball — cocaine + heroin",
    blurb: "The original mixer. Stimulant wears off first.",
    drugIds: ["cocaine", "heroin"],
    lane: "street",
  },
  {
    id: "bup-fentanyl",
    title: "Buprenorphine + fentanyl",
    blurb: "Partial agonist on a fentanyl load — precipitated withdrawal, not stacked mg",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
  },
  {
    id: "methadone-benzo",
    title: "Methadone + alprazolam",
    blurb: "OTP boxed warning — street benzo on a long μ agonist",
    drugIds: ["methadone", "alprazolam"],
    lane: "mat",
  },
  {
    id: "methadone-quetiapine",
    title: "Methadone + quetiapine",
    blurb: "Seroquel-for-sleep on a known-QT opioid",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
  },
  {
    id: "methadone-rifampin",
    title: "Methadone + rifampin",
    blurb: "3A4/2B6 induction looks like a stolen dose",
    drugIds: ["methadone", "rifampin"],
    lane: "mat",
  },
  {
    id: "bup-ritonavir",
    title: "Buprenorphine + ritonavir",
    blurb: "HIV booster raises a 3A4 partial agonist",
    drugIds: ["buprenorphine", "ritonavir"],
    lane: "mat",
  },
  {
    id: "methadone-gabapentin",
    title: "Methadone + gabapentin",
    blurb: "The 'nerve pain' that still hits the airway",
    drugIds: ["methadone", "gabapentin"],
    lane: "mat",
  },
  {
    id: "methadone-cocaine",
    title: "Methadone + cocaine",
    blurb: "OTP speedball — QT plus masked apnea",
    drugIds: ["methadone", "cocaine"],
    lane: "mat",
  },
  {
    id: "bup-bromazolam",
    title: "Buprenorphine + bromazolam",
    blurb: "Street benzo on a Suboxone desk — boxed airway",
    drugIds: ["buprenorphine", "bromazolam"],
    lane: "mat",
  },
  {
    id: "lofexidine-fent",
    title: "Lofexidine + fentanyl",
    blurb: "Lucemyra is α2 — naloxone will not finish withdrawal sedation",
    drugIds: ["lofexidine", "fentanyl"],
    lane: "mat",
  },
  {
    id: "acamprosate-naltrexone",
    title: "Acamprosate + naltrexone",
    blurb: "Alcohol MAT pair — the CYP/PD rows should stay quiet",
    drugIds: ["acamprosate", "naltrexone"],
    lane: "mat",
  },
  {
    id: "methadone-citalopram",
    title: "Methadone + citalopram",
    blurb: "Two known-QT drugs on an OTP board",
    drugIds: ["methadone", "citalopram"],
    lane: "mat",
  },
  {
    id: "methadone-fluconazole",
    title: "Methadone + fluconazole",
    blurb: "Azole 3A4 block — they nod, and the QT climbs",
    drugIds: ["methadone", "fluconazole"],
    lane: "mat",
  },
  {
    id: "methadone-hydroxyzine",
    title: "Methadone + hydroxyzine",
    blurb: "Vistaril is not a free benzo-alternative on a known-QT opioid",
    drugIds: ["methadone", "hydroxyzine"],
    lane: "mat",
  },
  {
    id: "methadone-ondansetron",
    title: "Methadone + ondansetron",
    blurb: "Zofran at the window — two known-QT drugs",
    drugIds: ["methadone", "ondansetron"],
    lane: "mat",
  },
  {
    id: "methadone-xylazine",
    title: "Methadone + xylazine",
    blurb: "Today's supply on a take-home — α2 naloxone will not reverse",
    drugIds: ["methadone", "xylazine"],
    lane: "mat",
  },
  {
    id: "naltrexone-fentanyl",
    title: "Naltrexone + fentanyl",
    blurb: "Leftover agonist after the Vivitrol shot",
    drugIds: ["naltrexone", "fentanyl"],
    lane: "mat",
  },
  {
    id: "bup-methadone",
    title: "Buprenorphine + methadone",
    blurb: "Transfer day — partial on a full agonist is precipitated withdrawal",
    drugIds: ["buprenorphine", "methadone"],
    lane: "mat",
  },
  {
    id: "bup-sevenoh",
    title: "Buprenorphine + 7-OH",
    blurb: "Smoke-shop μ-agonist on a Suboxone film — occupancy conflict",
    drugIds: ["buprenorphine", "seven-oh"],
    lane: "mat",
  },
  {
    id: "lofexidine-paroxetine",
    title: "Lofexidine + paroxetine",
    blurb: "Lucemyra is a 2D6 victim — the SSRI raises bradycardia",
    drugIds: ["lofexidine", "paroxetine"],
    lane: "mat",
  },
  {
    id: "methadone-epclusa",
    title: "Methadone + Epclusa",
    blurb: "HCV on the OTP — this pair should stay quiet; rifampin should not",
    drugIds: ["methadone", "epclusa"],
    lane: "mat",
  },
  {
    id: "naltrexone-loperamide",
    title: "Naltrexone + loperamide",
    blurb: "Imodium while waiting for Vivitrol — the μ is blocked, the QT is not",
    drugIds: ["naltrexone", "loperamide"],
    lane: "mat",
  },
  {
    id: "methadone-fentanyl",
    title: "Methadone + fentanyl",
    blurb: "Take-home plus today's supply — stacked μ, one airway",
    drugIds: ["methadone", "fentanyl"],
    lane: "mat",
  },
  {
    id: "methadone-fent-xylazine",
    title: "Methadone + fentanyl + xylazine",
    blurb: "The 2026 take-home triad — naloxone will not finish the α2",
    drugIds: ["methadone", "fentanyl", "xylazine"],
    lane: "mat",
  },
  {
    id: "methadone-paxlovid",
    title: "Methadone + Paxlovid",
    blurb: "Five-day ritonavir — methadone falls, watch withdrawal not nod",
    drugIds: ["methadone", "paxlovid"],
    lane: "mat",
  },
  {
    id: "fentanyl-paxlovid",
    title: "Fentanyl + Paxlovid",
    blurb: "Opposite arrow — 3A4 boost raises parent, airway risk climbs",
    drugIds: ["fentanyl", "paxlovid"],
    lane: "mat",
  },
  {
    id: "methadone-fluvoxamine",
    title: "Methadone + fluvoxamine",
    blurb: "The OTP Luvox bump — parent and QT climb; stopping looks stolen",
    drugIds: ["methadone", "fluvoxamine"],
    lane: "mat",
  },
  {
    id: "methadone-phenytoin",
    title: "Methadone + phenytoin",
    blurb: "Tong 1981 — Dilantin looks like a stolen take-home in days",
    drugIds: ["methadone", "phenytoin"],
    lane: "mat",
  },
  {
    id: "methadone-clonazepam",
    title: "Methadone + clonazepam",
    blurb: "The prescribed Klonopin — boxed airway, not a street benzo",
    drugIds: ["methadone", "clonazepam"],
    lane: "mat",
  },
  {
    id: "methadone-flexeril",
    title: "Methadone + cyclobenzaprine",
    blurb: "The 'back spasm' that still hits the airway",
    drugIds: ["methadone", "cyclobenzaprine"],
    lane: "mat",
  },
  {
    id: "methadone-phenergan",
    title: "Methadone + promethazine",
    blurb: "Window antiemetic — sedation plus a possible QT drug",
    drugIds: ["methadone", "promethazine"],
    lane: "mat",
  },
  {
    id: "methadone-trazodone",
    title: "Methadone + trazodone",
    blurb: "Sleep at the OTP — 3A4 victim plus a possible QT stack",
    drugIds: ["methadone", "trazodone"],
    lane: "mat",
  },
  {
    id: "methadone-cbd",
    title: "Methadone + CBD",
    blurb: "Epidiolex-dose 3A4/2C19 block on a known-QT opioid",
    drugIds: ["methadone", "cannabidiol"],
    lane: "mat",
  },
  {
    id: "fentanyl-medetomidine",
    title: "Fentanyl + medetomidine",
    blurb: "The newer α2 in the supply — naloxone will not reverse it",
    drugIds: ["fentanyl", "medetomidine"],
    lane: "mat",
  },
  {
    id: "methadone-meth",
    title: "Methadone + methamphetamine",
    blurb: "OTP goofball — stimulant masks apnea; QT is still there",
    drugIds: ["methadone", "methamphetamine"],
    lane: "mat",
  },
  {
    id: "fentanyl-fluconazole",
    title: "Fentanyl + fluconazole",
    blurb: "Azole 3A4 block on a sensitive μ-agonist — parent and airway",
    drugIds: ["fentanyl", "fluconazole"],
    lane: "mat",
  },
  {
    id: "methadone-nevirapine",
    title: "Methadone + nevirapine",
    blurb: "NNRTI stolen dose — same map as efavirenz, different rash",
    drugIds: ["methadone", "nevirapine"],
    lane: "mat",
  },
  {
    id: "methadone-naltrexone",
    title: "Methadone + naltrexone",
    blurb: "Vivitrol on a full agonist — precipitated withdrawal",
    drugIds: ["methadone", "naltrexone"],
    lane: "mat",
  },
  {
    id: "methadone-pregabalin",
    title: "Methadone + pregabalin",
    blurb: "Lyrica is the other gabapentinoid — still an airway warning",
    drugIds: ["methadone", "pregabalin"],
    lane: "mat",
  },
  {
    id: "methadone-ethanol",
    title: "Methadone + ethanol",
    blurb: "A drink on a take-home — boxed airway, not a CYP row",
    drugIds: ["methadone", "ethanol"],
    lane: "mat",
  },
  {
    id: "methadone-clarithromycin",
    title: "Methadone + clarithromycin",
    blurb: "Biaxin raises parent via 3A4 and stacks QT — not a Z-Pak",
    drugIds: ["methadone", "clarithromycin"],
    lane: "mat",
  },
  {
    id: "methadone-azithromycin",
    title: "Methadone + azithromycin",
    blurb: "Z-Pak is the quieter macrolide on CYP — it still stacks QT",
    drugIds: ["methadone", "azithromycin"],
    lane: "mat",
  },
  {
    id: "methadone-grapefruit",
    title: "Methadone + grapefruit",
    blurb: "Gut 3A4 knockout on a known-QT opioid — nod, not stolen",
    drugIds: ["methadone", "grapefruit"],
    lane: "mat",
  },
  {
    id: "bup-gabapentin",
    title: "Buprenorphine + gabapentin",
    blurb: "Office-based MAT — the nerve-pain extra still hits the airway",
    drugIds: ["buprenorphine", "gabapentin"],
    lane: "mat",
  },
  {
    id: "methadone-fluoxetine",
    title: "Methadone + fluoxetine",
    blurb: "Not the Luvox map — 2D6, not the OTP bump",
    drugIds: ["methadone", "fluoxetine"],
    lane: "mat",
  },
  {
    id: "methadone-carbamazepine",
    title: "Methadone + carbamazepine",
    blurb: "Tegretol stolen dose — 3A4/2B6 induction in 7–10 days",
    drugIds: ["methadone", "carbamazepine"],
    lane: "mat",
  },
  {
    id: "methadone-st-johns-wort",
    title: "Methadone + St. John's wort",
    blurb: "The tea that looks like rifampin-lite on a take-home",
    drugIds: ["methadone", "st-johns-wort"],
    lane: "mat",
  },
  {
    id: "methadone-ciprofloxacin",
    title: "Methadone + ciprofloxacin",
    blurb: "Herrlin 2000 — Cipro is not a free UTI pill on a known-QT opioid",
    drugIds: ["methadone", "ciprofloxacin"],
    lane: "mat",
  },
  {
    id: "bup-paxlovid",
    title: "Buprenorphine + Paxlovid",
    blurb: "Opposite of methadone — 3A4 raise, usually no cut in the tolerant",
    drugIds: ["buprenorphine", "paxlovid"],
    lane: "mat",
  },
  {
    id: "methadone-cimetidine",
    title: "Methadone + cimetidine",
    blurb: "Tagamet is the H2 that still bullies 3A4 — famotidine is the switch",
    drugIds: ["methadone", "cimetidine"],
    lane: "mat",
  },
  {
    id: "methadone-amiodarone",
    title: "Methadone + amiodarone",
    blurb: "Weeks of 3A4 block plus two known-QT drugs",
    drugIds: ["methadone", "amiodarone"],
    lane: "mat",
  },
  {
    id: "methadone-sertraline",
    title: "Methadone + sertraline",
    blurb: "Zoloft is not Luvox — 2D6, still serotonin",
    drugIds: ["methadone", "sertraline"],
    lane: "mat",
  },
  {
    id: "methadone-cobicistat",
    title: "Methadone + cobicistat",
    blurb: "Tybost is not Norvir — 3A4 raise, no 2B6 dump",
    drugIds: ["methadone", "cobicistat"],
    lane: "mat",
  },
  {
    id: "bup-naltrexone",
    title: "Buprenorphine + naltrexone",
    blurb: "Vivitrol on a film — occupancy conflict, not a failed shot",
    drugIds: ["buprenorphine", "naltrexone"],
    lane: "mat",
  },
  {
    id: "methadone-phenobarbital",
    title: "Methadone + phenobarbital",
    blurb: "Barbiturate stolen dose plus stacked apnea",
    drugIds: ["methadone", "phenobarbital"],
    lane: "mat",
  },
  {
    id: "aza-allopurinol",
    title: "Azathioprine + allopurinol",
    blurb: "XO block of 6-MP — pancytopenia, not a gout footnote",
    drugIds: ["azathioprine", "allopurinol"],
    lane: "clinic",
  },
  {
    id: "imdur-viagra",
    title: "Isosorbide + sildenafil",
    blurb: "Daily nitrate × PDE5 — the labeled hypotension",
    drugIds: ["isosorbide-mononitrate", "sildenafil"],
    lane: "clinic",
  },
  {
    id: "plavix-prilosec",
    title: "Clopidogrel + omeprazole",
    blurb: "2C19 activation of a prodrug — the PPI that blunts Plavix",
    drugIds: ["clopidogrel", "omeprazole"],
    lane: "clinic",
  },
  {
    id: "relpax-clarith",
    title: "Eletriptan + clarithromycin",
    blurb: "The CYP triptan × strong 3A4 — labeled 72-hour hold",
    drugIds: ["eletriptan", "clarithromycin"],
    lane: "clinic",
  },
  {
    id: "entocort-keto",
    title: "Oral budesonide + ketoconazole",
    blurb: "Gut 3A4 first-pass — a 'local' steroid goes systemic",
    drugIds: ["budesonide", "ketoconazole"],
    lane: "clinic",
  },
  {
    id: "eplerenone-clarith",
    title: "Eplerenone + clarithromycin",
    blurb: "Sensitive 3A4 K-sparing — labeled with strong inhibitors",
    drugIds: ["eplerenone", "clarithromycin"],
    lane: "clinic",
  },
  {
    id: "lamisil-metoprolol",
    title: "Terbinafine + metoprolol",
    blurb: "Nail-fungus 2D6 block on a beta blocker",
    drugIds: ["terbinafine", "metoprolol"],
    lane: "clinic",
  },
  {
    id: "actos-lopid",
    title: "Pioglitazone + gemfibrozil",
    blurb: "Sensitive 2C8 × the strong 2C8 fibrate",
    drugIds: ["pioglitazone", "gemfibrozil"],
    lane: "clinic",
  },
  {
    id: "flonase-ritonavir",
    title: "Fluticasone + ritonavir",
    blurb: "The spray that becomes Cushing next to a booster",
    drugIds: ["fluticasone", "ritonavir"],
    lane: "clinic",
  },
  {
    id: "ozempic-amaryl",
    title: "Semaglutide + glimepiride",
    blurb: "GLP-1 plus a sulfonylurea — stacked hypoglycemia",
    drugIds: ["semaglutide", "glimepiride"],
    lane: "clinic",
  },
  {
    id: "fenofibrate-simva",
    title: "Fenofibrate + simvastatin",
    blurb: "Statin × fibrate — major, not the gemfibrozil contraindication",
    drugIds: ["fenofibrate", "simvastatin"],
    lane: "clinic",
  },
  {
    id: "6mp-febuxostat",
    title: "6-MP + febuxostat",
    blurb: "Same XO enzyme as allopurinol — still marrow",
    drugIds: ["mercaptopurine", "febuxostat"],
    lane: "clinic",
  },
  {
    id: "ryr-gemfibrozil",
    title: "Red yeast rice + gemfibrozil",
    blurb: "Monacolin K is lovastatin — this is the labeled statin–fibrate hold",
    drugIds: ["red-yeast-rice", "gemfibrozil"],
    lane: "food",
  },
  {
    id: "vitk-warfarin",
    title: "Vitamin K + warfarin",
    blurb: "The antidote in a gummy — INR falls, not a 2C9 story",
    drugIds: ["vitamin-k", "warfarin"],
    lane: "food",
  },
  {
    id: "fishoil-warfarin",
    title: "Fish oil + warfarin",
    blurb: "High-dose EPA/DHA on a VKA — bleed, not CYP",
    drugIds: ["fish-oil", "warfarin"],
    lane: "food",
  },
  {
    id: "same-sertraline",
    title: "SAM-e + sertraline",
    blurb: "Methyl donor meets an SSRI — stacked serotonin",
    drugIds: ["sam-e", "sertraline"],
    lane: "food",
  },
  {
    id: "calcium-synthroid",
    title: "Calcium + levothyroxine",
    blurb: "Gut chelation — the morning Tums empties the TSH",
    drugIds: ["calcium", "levothyroxine"],
    lane: "food",
  },
  {
    id: "iron-cipro",
    title: "Iron + ciprofloxacin",
    blurb: "Divalent cation — the course can fail",
    drugIds: ["iron", "ciprofloxacin"],
    lane: "food",
  },
  {
    id: "yohimbine-maoi",
    title: "Yohimbine + phenelzine",
    blurb: "α2 block plus irreversible MAOI — pressor crisis",
    drugIds: ["yohimbine", "phenelzine"],
    lane: "food",
  },
  {
    id: "niacin-simva",
    title: "Niacin + simvastatin",
    blurb: "Gram-dose B3 on a 3A4 statin — muscle",
    drugIds: ["niacin", "simvastatin"],
    lane: "food",
  },
  {
    id: "arginine-viagra",
    title: "L-arginine + sildenafil",
    blurb: "Pre-workout NO plus PDE5 — stacked hypotension",
    drugIds: ["arginine", "sildenafil"],
    lane: "food",
  },
  {
    id: "quercetin-simva",
    title: "Quercetin + simvastatin",
    blurb: "Flavonol 3A4/P-gp block on a sensitive statin",
    drugIds: ["quercetin", "simvastatin"],
    lane: "food",
  },
  {
    id: "potassium-lisinopril",
    title: "Potassium + lisinopril",
    blurb: "Salt-substitute K plus an ACEI — hyperkalemia",
    drugIds: ["potassium", "lisinopril"],
    lane: "food",
  },
  {
    id: "senna-sotalol",
    title: "Senna + sotalol",
    blurb: "Stimulant laxative hypokalemia plus a known QT drug",
    drugIds: ["senna", "sotalol"],
    lane: "food",
  },
  {
    id: "berberine-simva",
    title: "Berberine + simvastatin",
    blurb: "The glucose capsule is a 3A4/P-gp bully — not goldenseal tea",
    drugIds: ["berberine", "simvastatin"],
    lane: "food",
  },
  {
    id: "berberine-glipizide",
    title: "Berberine + glipizide",
    blurb: "Metformin-like herb plus a sulfonylurea — stacked hypoglycemia",
    drugIds: ["berberine", "glipizide"],
    lane: "food",
  },
  {
    id: "echinacea-tizanidine",
    title: "Echinacea + tizanidine",
    blurb: "Cold-and-flu 1A2 block on a sensitive muscle relaxant",
    drugIds: ["echinacea", "tizanidine"],
    lane: "food",
  },
  {
    id: "bitter-orange-maoi",
    title: "Bitter orange + phenelzine",
    blurb: "Synephrine fat-burner plus irreversible MAOI — pressor",
    drugIds: ["bitter-orange", "phenelzine"],
    lane: "food",
  },
  {
    id: "charcoal-synthroid",
    title: "Activated charcoal + levothyroxine",
    blurb: "The binder — the dose never arrives",
    drugIds: ["charcoal", "levothyroxine"],
    lane: "food",
  },
  {
    id: "ala-glipizide",
    title: "Alpha-lipoic acid + glipizide",
    blurb: "Neuropathy bottle plus a sulfonylurea — hypoglycemia",
    drugIds: ["ala", "glipizide"],
    lane: "food",
  },
  {
    id: "resveratrol-simva",
    title: "Resveratrol + simvastatin",
    blurb: "Gram stilbene 3A4 block on a sensitive statin",
    drugIds: ["resveratrol", "simvastatin"],
    lane: "food",
  },
  {
    id: "nattokinase-warfarin",
    title: "Nattokinase + warfarin",
    blurb: "The 'clot buster' bottle next to a vitamin-K antagonist",
    drugIds: ["nattokinase", "warfarin"],
    lane: "food",
  },
  {
    id: "psyllium-synthroid",
    title: "Psyllium + levothyroxine",
    blurb: "Metamucil with the morning dose — empty TSH",
    drugIds: ["psyllium", "levothyroxine"],
    lane: "food",
  },
  {
    id: "citrulline-viagra",
    title: "L-citrulline + sildenafil",
    blurb: "Pre-workout NO plus PDE5 — stacked hypotension",
    drugIds: ["citrulline", "sildenafil"],
    lane: "food",
  },
  {
    id: "chromium-glipizide",
    title: "Chromium + glipizide",
    blurb: "Blood-sugar bottle plus a sulfonylurea — hypoglycemia",
    drugIds: ["chromium", "glipizide"],
    lane: "food",
  },
  {
    id: "icariin-nitro",
    title: "Horny goat weed + nitroglycerin",
    blurb: "Herbal PDE5 next to a nitrate — not labeled like Viagra",
    drugIds: ["icariin", "nitroglycerin"],
    lane: "food",
  },
  {
    id: "dairy-tetracycline",
    title: "Milk + tetracycline",
    blurb: "The original dairy trap — worse than doxycycline",
    drugIds: ["dairy", "tetracycline"],
    lane: "food",
  },
  {
    id: "oj-atenolol",
    title: "Orange juice + atenolol",
    blurb: "OATP2B1 — Tenormin AUC falls",
    drugIds: ["oatp-juice", "atenolol"],
    lane: "food",
  },
  {
    id: "egcg-nadolol",
    title: "Green tea + nadolol",
    blurb: "Misaka — catechins dump Corgard via OATP",
    drugIds: ["green-tea", "nadolol"],
    lane: "food",
  },
  {
    id: "soy-synthroid",
    title: "Soy milk + levothyroxine",
    blurb: "Formula and protein shakes bind T4",
    drugIds: ["soy", "levothyroxine"],
    lane: "food",
  },
  {
    id: "banana-lisinopril",
    title: "Salt substitute + lisinopril",
    blurb: "Dietary potassium plus an ACEI — hyperK without Slow-K",
    drugIds: ["high-k-foods", "lisinopril"],
    lane: "food",
  },
  {
    id: "tuna-inh",
    title: "Tuna + isoniazid",
    blurb: "Diamine oxidase — scombroid on a TB pill",
    drugIds: ["histamine-fish", "isoniazid"],
    lane: "food",
  },
  {
    id: "ng-dilantin",
    title: "Tube feed + phenytoin",
    blurb: "Bauer 1982 — continuous feeds bind Dilantin",
    drugIds: ["enteral-feed", "phenytoin"],
    lane: "food",
  },
  {
    id: "fat-lurasidone",
    title: "High-fat meal + lurasidone",
    blurb: "Latuda is labeled with ~350 kcal — F collapses fasted",
    drugIds: ["high-fat-meal", "lurasidone"],
    lane: "food",
  },
  {
    id: "fat-geodon",
    title: "High-fat meal + ziprasidone",
    blurb: "Geodon wants ~500 kcal or AUC falls by half",
    drugIds: ["high-fat-meal", "ziprasidone"],
    lane: "food",
  },
  {
    id: "meal-fosamax",
    title: "A meal + alendronate",
    blurb: "Anything in the stomach kills Fosamax F",
    drugIds: ["high-fat-meal", "alendronate"],
    lane: "food",
  },
  {
    id: "oj-aliskiren",
    title: "Apple juice + aliskiren",
    blurb: "OATP2B1 — Tekturna never arrives",
    drugIds: ["oatp-juice", "aliskiren"],
    lane: "food",
  },
  {
    id: "caffeine-lithium",
    title: "Caffeine + lithium",
    blurb: "Caffeine dumps lithium; stopping it retains it",
    drugIds: ["caffeine", "lithium"],
    lane: "food",
  },
  {
    id: "pheno-codeine",
    title: "Paroxetine + codeine",
    blurb: "2D6 phenoconversion — NM on paper, PM on the enzyme",
    drugIds: ["paroxetine", "codeine"],
    lane: "phenotype",
  },
  {
    id: "pheno-dxm",
    title: "Bupropion + DXM",
    blurb: "Wellbutrin locks 2D6; dextromethorphan accumulates",
    drugIds: ["bupropion", "dextromethorphan"],
    lane: "phenotype",
  },
  {
    id: "mme-stack",
    title: "Methadone + oxycodone",
    blurb: "MME is not two prescriptions. One airway, banded methadone factor",
    drugIds: ["methadone", "oxycodone"],
    lane: "mat",
  },
  {
    id: "hunter-mdma",
    title: "MDMA + sertraline",
    blurb: "Hunter screen — clonus, not a Sternbach plus-table",
    drugIds: ["mdma", "sertraline"],
    lane: "entactogen",
  },
  {
    id: "reversal-apap",
    title: "Acetaminophen + NAC",
    blurb: "The antidote on the desk. Rumack is the nomogram",
    drugIds: ["acetaminophen", "nac"],
    lane: "clinic",
  },
  {
    id: "uds-methadone",
    title: "Methadone cup",
    blurb: "Opiate EIA stays negative on a take-home. That's the assay. Ask EDDP.",
    drugIds: ["methadone"],
    lane: "mat",
  },
  {
    id: "uds-seroquel",
    title: "Seroquel vs the TCA cup",
    blurb: "Window sleep med lights TCA. Methadone does not light opiates.",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
  },
  {
    id: "uds-wellbutrin",
    title: "Wellbutrin vs the amphetamine cup",
    blurb: "Bupropion is the classic amphetamine EIA false-positive",
    drugIds: ["bupropion"],
    lane: "clinic",
  },
  {
    id: "uds-zoloft",
    title: "Zoloft vs the benzo cup",
    blurb: "Sertraline can light a benzodiazepine immunoassay",
    drugIds: ["sertraline"],
    lane: "clinic",
  },
  {
    id: "uds-dxm",
    title: "DXM vs the PCP cup",
    blurb: "Dextromethorphan fools many PCP EIAs. 2D6 is the other board.",
    drugIds: ["dextromethorphan"],
    lane: "clinic",
  },
  {
    id: "cows-lofexidine",
    title: "Lofexidine on the COWS",
    blurb: "α2 for withdrawal. Naloxone will not reverse it.",
    drugIds: ["lofexidine", "buprenorphine"],
    lane: "mat",
  },
  {
    id: "nalmefene-fent",
    title: "Opvee after a fold",
    blurb: "Nalmefene occupies μ longer than naloxone — re-narcotize vs over-reverse",
    drugIds: ["nalmefene", "fentanyl"],
    lane: "mat",
  },
  {
    id: "lact-methadone",
    title: "Methadone + breastfeeding",
    blurb: "LactMed compatible. RID ~1–3%. Do not stop OTP to feed.",
    drugIds: ["methadone"],
    lane: "mat",
  },
  {
    id: "otp-induction",
    title: "Buprenorphine after fentanyl",
    blurb: "OTP tab — occupancy vs COWS. The integer is not the receptor.",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
  },
  {
    id: "vivitrol-methadone",
    title: "Vivitrol after methadone",
    blurb: "Washout clock. Labels discuss ~10–14 days after a long agonist.",
    drugIds: ["naltrexone", "methadone"],
    lane: "mat",
  },
  {
    id: "clozapine-anc",
    title: "Clozapine ANC",
    blurb: "REMS green / yellow / interrupt. Smoke is the other board.",
    drugIds: ["clozapine"],
    lane: "clinic",
  },
  {
    id: "warfarin-amio",
    title: "Warfarin + amiodarone",
    blurb: "INR tab — 2C9 block over weeks, not overnight.",
    drugIds: ["warfarin", "amiodarone"],
    lane: "clinic",
  },
  {
    id: "cyp-clarith-midazolam",
    title: "Clarithromycin + midazolam",
    blurb: "CYP tab — TDI 3A4. Stopping yesterday does not restore Versed.",
    drugIds: ["clarithromycin", "midazolam"],
    lane: "clinic",
  },
  {
    id: "cyp-rifampin-midazolam",
    title: "Rifampin + midazolam",
    blurb: "CYP tab — 96% AUC dump. Stop is rebound, not a completed course.",
    drugIds: ["rifampin", "midazolam"],
    lane: "clinic",
  },
  {
    id: "cyp-cipro-tizanidine",
    title: "Cipro + tizanidine",
    blurb: "Labeled 1A2 knockout. Sensitive index substrate. Start is hypotension.",
    drugIds: ["ciprofloxacin", "tizanidine"],
    lane: "clinic",
  },
  {
    id: "cyp-fluoxetine-codeine",
    title: "Fluoxetine + codeine",
    blurb: "5-week 2D6 TDI clock. Stopping Prozac yesterday is not a clear.",
    drugIds: ["fluoxetine", "codeine"],
    lane: "clinic",
  },
  {
    id: "cyp-itraconazole-simva",
    title: "Itraconazole + simvastatin",
    blurb: "Strong 3A4 + P-gp. Dual-hit first-pass. Labeled hold.",
    drugIds: ["itraconazole", "simvastatin"],
    lane: "clinic",
  },
  {
    id: "ward-mero-vpa",
    title: "Meropenem + valproate",
    blurb: "Wards tab — carbapenem crashes valproate. UGT, not stacked seizure-lowering.",
    drugIds: ["meropenem", "valproate"],
    lane: "clinic",
  },
  {
    id: "ward-vanco-zosyn",
    title: "Vancomycin + Zosyn",
    blurb: "Wards tab — observational AKI vs vanco + cefepime. Oral vanco is different.",
    drugIds: ["vancomycin", "piperacillin-tazobactam"],
    lane: "clinic",
  },
  {
    id: "ward-entresto-acei",
    title: "Entresto + lisinopril",
    blurb: "Wards tab — ARNI × ACEI. 36-hour washout. Angioedema, not a potassium footnote.",
    drugIds: ["sacubitril-valsartan", "lisinopril"],
    lane: "clinic",
  },
  {
    id: "ward-cape-warfarin",
    title: "Capecitabine + warfarin",
    blurb: "Wards / INR — fluoropyrimidine raises INR. Recheck. Not a 2C9 bully on this map.",
    drugIds: ["capecitabine", "warfarin"],
    lane: "clinic",
  },
  {
    id: "ward-diclox-warfarin",
    title: "Dicloxacillin + warfarin",
    blurb: "Wards / INR — 3A4 induction steals warfarin. INR falls. Recheck after stop too.",
    drugIds: ["dicloxacillin", "warfarin"],
    lane: "clinic",
  },
  {
    id: "ward-letermovir-tacro",
    title: "Letermovir + tacrolimus",
    blurb: "Wards / TDM — moderate 3A4 × sensitive NTI. CMV prophylaxis is not a free add-on.",
    drugIds: ["letermovir", "tacrolimus"],
    lane: "clinic",
  },
  {
    id: "ward-glp-insulin",
    title: "Semaglutide + insulin aspart",
    blurb: "Wards tab — GLP-1 next to insulin is stacked hypo. Metformin stays quieter.",
    drugIds: ["semaglutide", "insulin-aspart"],
    lane: "clinic",
  },
  {
    id: "dose-simva-amio",
    title: "Simvastatin 40 + amiodarone",
    blurb: "Dose tab — labeled 20 mg cap. Type 40; the PI, not this desk, caps it.",
    drugIds: ["simvastatin", "amiodarone"],
    lane: "clinic",
    doses: { simvastatin: "40" },
  },
  {
    id: "dose-mtx-weekly",
    title: "Methotrexate weekly rail",
    blurb: "Dose tab — 7.5–25 mg once weekly. Daily RA methotrexate is the ISMP trap.",
    drugIds: ["methotrexate"],
    lane: "clinic",
    doses: { methotrexate: "15" },
  },
  {
    id: "safety-epclusa-amio",
    title: "Epclusa + amiodarone",
    blurb: "Wards — boxed sofosbuvir bradycardia. Not additive nodal PD.",
    drugIds: ["epclusa", "amiodarone"],
    lane: "clinic",
  },
  {
    id: "safety-clozapine-lorazepam",
    title: "Clozapine + lorazepam",
    blurb: "Wards — boxed respiratory collapse. Not generic CNS.",
    drugIds: ["clozapine", "lorazepam"],
    lane: "clinic",
  },
  {
    id: "safety-asa-ibu",
    title: "Aspirin + ibuprofen",
    blurb: "Wards — ibuprofen attenuates ASA. Lost cardioprotection, not two NSAIDs.",
    drugIds: ["aspirin", "ibuprofen"],
    lane: "clinic",
  },
  {
    id: "safety-lamo-vpa",
    title: "Lamotrigine + valproate",
    blurb: "Wards — UGT blockade, SJS. Labeled starter kit. Not stacked GABA.",
    drugIds: ["lamotrigine", "valproate"],
    lane: "clinic",
  },
  {
    id: "safety-lamo-ee",
    title: "Lamotrigine + OCP",
    blurb: "Wards — EE induces UGT. Lamotrigine falls. Stop of the pill can spike.",
    drugIds: ["lamotrigine", "ethinyl-estradiol"],
    lane: "clinic",
  },
  {
    id: "safety-tamoxifen-paroxetine",
    title: "Tamoxifen + paroxetine",
    blurb: "Wards / CYP — lost endoxifen. Switch the SSRI. CPIC, not more tamoxifen.",
    drugIds: ["tamoxifen", "paroxetine"],
    lane: "clinic",
  },
  {
    id: "safety-ocp-rifampin",
    title: "OCP + rifampin",
    blurb: "Wards — contraceptive failure. Backup, not a quieter pill.",
    drugIds: ["ethinyl-estradiol", "rifampin"],
    lane: "clinic",
  },
  {
    id: "safety-isotret-doxy",
    title: "Isotretinoin + doxycycline",
    blurb: "Wards — pseudotumor cerebri. iPLEDGE still applies.",
    drugIds: ["isotretinoin", "doxycycline"],
    lane: "clinic",
  },
  {
    id: "safety-cipro-pred",
    title: "Ciprofloxacin + prednisone",
    blurb: "Wards — FQ boxed tendon. Prednisone is empty PD on purpose.",
    drugIds: ["ciprofloxacin", "prednisone"],
    lane: "clinic",
  },
  {
    id: "safety-lisinopril-losartan",
    title: "Lisinopril + losartan",
    blurb: "Wards — dual RAAS. Not the Entresto 36-hour ACEI washout.",
    drugIds: ["lisinopril", "losartan"],
    lane: "clinic",
  },
  {
    id: "safety-ppi-rilpivirine",
    title: "Omeprazole + rilpivirine",
    blurb: "Wards — PPI contraindicated. Gastric pH, not CYP3A4.",
    drugIds: ["omeprazole", "rilpivirine"],
    lane: "clinic",
  },
  {
    id: "safety-sglt2-loop",
    title: "Empagliflozin + furosemide",
    blurb: "Wards — volume / euglycemic DKA. A normal fingerstick does not clear ketones.",
    drugIds: ["empagliflozin", "furosemide"],
    lane: "clinic",
  },
  {
    id: "hr-fent-xylazine",
    title: "Fentanyl + xylazine + naloxone",
    blurb: "HR tab — naloxone reverses μ, not the α2. Stay. Do not use alone.",
    drugIds: ["fentanyl", "xylazine"],
    lane: "street",
  },
  {
    id: "hr-mdma-heat",
    title: "MDMA on a hot night",
    blurb: "HR tab — sip, don't chug. Test the pill. PMA delayed onset is the deadly redose.",
    drugIds: ["mdma"],
    lane: "street",
  },
  {
    id: "hr-ghb-stack",
    title: "GHB + alcohol",
    blurb: "HR tab — steep curve, no reversal. Recovery position. Labeled contraindicated.",
    drugIds: ["sodium-oxybate", "ethanol"],
    lane: "gaba",
  },
  {
    id: "hr-nbome-lsd",
    title: "25I-NBOMe sold as LSD",
    blurb: "HR tab — Ehrlich often quiet on NBOMe. Vasoconstriction, not a gentle blotter.",
    drugIds: ["twentyfive-i", "lsd"],
    lane: "street",
  },
  {
    id: "hr-ketamine-etoh",
    title: "Ketamine + alcohol",
    blurb: "HR tab — TripSit dangerous. Do not swim. Airway, not a k-hole milligram.",
    drugIds: ["ketamine", "ethanol"],
    lane: "nmda",
  },
  {
    id: "hr-mdma-maoi",
    title: "MDMA × Nardil — wiki deadly",
    blurb: "HR tab — TripSit deadly. Serotonin toxicity, not a blunted roll.",
    drugIds: ["mdma", "phenelzine"],
    lane: "entactogen",
  },
];
