import type { AlcoholPattern, CannabisRoute, KetamineRoute, PhenotypeMap } from "./types";

export type SampleLane = "nmda" | "entactogen" | "gaba" | "phenotype" | "smoke" | "mat" | "food" | "street" | "clinic";

export function sampleNeedsPro(s: SampleRegimen) {
  return Boolean(
    s.phenotypes ||
      s.smoking ||
      s.alcohol ||
      s.cannabisRoute ||
      (s.ketamineRoute && s.ketamineRoute !== "iv"),
  );
}

export interface SampleRegimen {
  id: string;
  title: string;
  blurb: string;
  drugIds: string[];
  lane: SampleLane;
  phenotypes?: Partial<PhenotypeMap>;
  smoking?: boolean;
  ketamineRoute?: KetamineRoute;
  cannabisRoute?: CannabisRoute;
  alcohol?: AlcoholPattern;
}

export const SAMPLE_LANES: { id: SampleLane | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "nmda", label: "NMDA" },
  { id: "entactogen", label: "Entactogen" },
  { id: "gaba", label: "GABA" },
  { id: "phenotype", label: "Phenotype" },
  { id: "smoke", label: "Smoke" },
  { id: "mat", label: "MAT" },
  { id: "food", label: "Food" },
  { id: "street", label: "Street" },
  { id: "clinic", label: "Clinic" },
];

export const SAMPLE_REGIMENS: SampleRegimen[] = [
  {
    id: "ketamine-3a4",
    title: "Oral ketamine + clarithromycin",
    blurb: "First-pass 3A4 trap — much hotter than IV",
    drugIds: ["ketamine", "clarithromycin"],
    lane: "nmda",
    ketamineRoute: "oral",
  },
  {
    id: "ketamine-benzo",
    title: "Ketamine + alprazolam",
    blurb: "NMDA + GABA — airway risk, blunted antidepressant effect",
    drugIds: ["ketamine", "alprazolam"],
    lane: "nmda",
  },
  {
    id: "esketamine-rifampin",
    title: "Esketamine + rifampin",
    blurb: "Strong 2B6/3A4 induction, loss of esketamine exposure",
    drugIds: ["esketamine", "rifampin"],
    lane: "nmda",
    ketamineRoute: "in",
  },
  {
    id: "mdma-maoi",
    title: "MDMA + phenelzine",
    blurb: "Entactogen × irreversible MAOI — contraindicated",
    drugIds: ["mdma", "phenelzine"],
    lane: "entactogen",
  },
  {
    id: "mdma-2d6",
    title: "MDMA + paroxetine",
    blurb: "2D6 blockade plus stacked serotonin",
    drugIds: ["mdma", "paroxetine"],
    lane: "entactogen",
  },
  {
    id: "dxm-ssri",
    title: "DXM + sertraline",
    blurb: "Sensitive 2D6 substrate meets an SSRI",
    drugIds: ["dextromethorphan", "sertraline"],
    lane: "nmda",
  },
  {
    id: "dxm-quinidine",
    title: "DXM + quinidine",
    blurb: "Nuedexta pair — strong 2D6 inhibition of DXM",
    drugIds: ["dextromethorphan", "quinidine"],
    lane: "nmda",
  },
  {
    id: "alcohol-opioid-benzo",
    title: "Alcohol + opioid + benzo",
    blurb: "Three-drug CNS stack — respiratory depression",
    drugIds: ["ethanol", "oxycodone", "alprazolam"],
    lane: "gaba",
  },
  {
    id: "cbd-clobazam",
    title: "CBD + clobazam",
    blurb: "Strong CYP2C19 inhibition of a sensitive benzo",
    drugIds: ["cannabidiol", "clobazam"],
    lane: "gaba",
  },
  {
    id: "cocaine-alcohol",
    title: "Cocaine + ethanol",
    blurb: "Cocaethylene — longer-lived cardiotoxin",
    drugIds: ["cocaine", "ethanol"],
    lane: "street",
  },
  {
    id: "lithium-psilocybin",
    title: "Lithium + psilocybin",
    blurb: "Classic psychedelic × lithium seizure signal",
    drugIds: ["lithium", "psilocybin"],
    lane: "entactogen",
  },
  {
    id: "naltrexone-opioid",
    title: "Naltrexone + oxycodone",
    blurb: "Antagonist precipitates withdrawal, blocks analgesia",
    drugIds: ["naltrexone", "oxycodone"],
    lane: "mat",
  },
  {
    id: "ghb-alcohol",
    title: "Sodium oxybate + alcohol",
    blurb: "Labeled contraindication — coma / apnea",
    drugIds: ["sodium-oxybate", "ethanol"],
    lane: "gaba",
  },
  {
    id: "dxm-2d6pm",
    title: "DXM in a 2D6 PM",
    blurb: "Poor metabolizer = stacked parent without a perpetrator drug",
    drugIds: ["dextromethorphan"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "PM" },
  },
  {
    id: "ketamine-2b6pm",
    title: "Ketamine in a 2B6 PM",
    blurb: "Slow norketamine formation, higher parent NMDA load",
    drugIds: ["ketamine"],
    lane: "phenotype",
    phenotypes: { CYP2B6: "PM" },
  },
  {
    id: "codeine-2d6um",
    title: "Codeine in a 2D6 UM",
    blurb: "Ultrarapid activation to morphine — labeled risk",
    drugIds: ["codeine"],
    lane: "phenotype",
    phenotypes: { CYP2D6: "UM" },
  },
  {
    id: "smoke-clozapine",
    title: "Clozapine + daily smoke",
    blurb: "PAHs induce 1A2 — clozapine levels fall, rebound on quit",
    drugIds: ["clozapine"],
    lane: "smoke",
    smoking: true,
  },
  {
    id: "ibogaine-methadone",
    title: "Ibogaine + methadone",
    blurb: "2D6 victim plus stacked QT — a documented fatality pattern",
    drugIds: ["ibogaine", "methadone"],
    lane: "nmda",
  },
  {
    id: "gf-oral-ketamine",
    title: "Grapefruit + oral ketamine",
    blurb: "Intestinal 3A4 knockout — IV barely moves, oral does",
    drugIds: ["grapefruit", "ketamine"],
    lane: "food",
    ketamineRoute: "oral",
  },
  {
    id: "gf-buspirone",
    title: "Grapefruit + buspirone",
    blurb: "Classic furanocoumarin × sensitive 3A4 anxiolytic",
    drugIds: ["grapefruit", "buspirone"],
    lane: "food",
  },
  {
    id: "tacrolimus-gf",
    title: "Tacrolimus + grapefruit",
    blurb: "NTI 3A4 victim × intestinal knockout — F rises, t½ does not",
    drugIds: ["tacrolimus", "grapefruit"],
    lane: "food",
  },
  {
    id: "tyramine-maoi",
    title: "Tyramine foods + phenelzine",
    blurb: "Aged cheese / tap beer × irreversible MAOI",
    drugIds: ["tyramine-foods", "phenelzine"],
    lane: "food",
  },
  {
    id: "sjw-sertraline",
    title: "St. John's wort + sertraline",
    blurb: "3A4 induction plus stacked serotonin",
    drugIds: ["st-johns-wort", "sertraline"],
    lane: "food",
  },
  {
    id: "fat-dronabinol",
    title: "High-fat meal + THC",
    blurb: "Fed-state jump in oral cannabinoid AUC",
    drugIds: ["high-fat-meal", "dronabinol"],
    lane: "food",
  },
  {
    id: "lithium-low-salt",
    title: "Lithium + low salt",
    blurb: "Sodium restriction retains lithium",
    drugIds: ["lithium", "low-salt"],
    lane: "food",
  },
  {
    id: "kratom-benzo",
    title: "Kratom + alprazolam",
    blurb: "Atypical opioid × benzo — airway stack",
    drugIds: ["kratom", "alprazolam"],
    lane: "mat",
  },
  {
    id: "phenibut-alcohol",
    title: "Phenibut + alcohol",
    blurb: "GABA-B analogue plus ethanol — stacked sedation",
    drugIds: ["phenibut", "ethanol"],
    lane: "gaba",
  },
  {
    id: "chronic-apap",
    title: "Acetaminophen + chronic alcohol",
    blurb: "Induced 2E1 → NAPQI; glutathione already low",
    drugIds: ["acetaminophen"],
    lane: "smoke",
    alcohol: "chronic",
  },
  {
    id: "edible-thc-2c9",
    title: "Edible THC + fluconazole",
    blurb: "11-OH-THC first-pass meets strong CYP2C9 inhibition",
    drugIds: ["dronabinol", "fluconazole"],
    lane: "food",
    cannabisRoute: "oral",
  },
  {
    id: "xylazine-fentanyl",
    title: "Xylazine + fentanyl",
    blurb: "α2 sedation naloxone will not reverse",
    drugIds: ["xylazine", "fentanyl"],
    lane: "street",
  },
  {
    id: "gbl-alcohol",
    title: "GBL + alcohol",
    blurb: "GHB prodrug × ethanol — labeled apnea",
    drugIds: ["gbl", "ethanol"],
    lane: "street",
  },
  {
    id: "mephedrone-maoi",
    title: "Mephedrone + phenelzine",
    blurb: "Cathinone × irreversible MAOI",
    drugIds: ["mephedrone", "phenelzine"],
    lane: "street",
  },
  {
    id: "bromazolam-oxy",
    title: "Bromazolam + oxycodone",
    blurb: "Designer benzo × opioid — boxed airway warning",
    drugIds: ["bromazolam", "oxycodone"],
    lane: "street",
  },
  {
    id: "loperamide-quinidine",
    title: "Loperamide + quinidine",
    blurb: "P-gp knockout turns Imodium into a central opioid",
    drugIds: ["loperamide", "quinidine"],
    lane: "street",
  },
  {
    id: "twofdck-gf",
    title: "2-FDCK + grapefruit",
    blurb: "Oral arylcyclohexylamine meets intestinal 3A4 knockout",
    drugIds: ["two-fdck", "grapefruit"],
    lane: "street",
    ketamineRoute: "oral",
  },
  {
    id: "poppers-sildenafil",
    title: "Poppers + sildenafil",
    blurb: "Nitrate × PDE5 — labeled collapse",
    drugIds: ["poppers", "sildenafil"],
    lane: "street",
  },
  {
    id: "mxe-alprazolam",
    title: "MXE + alprazolam",
    blurb: "Long NMDA dissociative × benzo airway stack",
    drugIds: ["mxe", "alprazolam"],
    lane: "nmda",
  },
  {
    id: "dck-gf",
    title: "DCK + grapefruit",
    blurb: "Oral deschloroketamine meets intestinal 3A4 knockout",
    drugIds: ["dck", "grapefruit"],
    lane: "nmda",
    ketamineRoute: "oral",
  },
  {
    id: "three-meo-benzo",
    title: "3-MeO-PCP + alprazolam",
    blurb: "Long arylcyclohexylamine × benzo airway stack",
    drugIds: ["three-meo-pcp", "alprazolam"],
    lane: "nmda",
  },
  {
    id: "mda-maoi",
    title: "MDA + phenelzine",
    blurb: "MDMA cousin × irreversible MAOI",
    drugIds: ["mda", "phenelzine"],
    lane: "entactogen",
  },
  {
    id: "methylone-2d6",
    title: "Methylone + paroxetine",
    blurb: "Cathinone 2D6 victim plus stacked serotonin",
    drugIds: ["methylone", "paroxetine"],
    lane: "entactogen",
  },
  {
    id: "nbome-lithium",
    title: "25I-NBOMe + lithium",
    blurb: "Street blotter × lithium seizure signal",
    drugIds: ["twentyfive-i", "lithium"],
    lane: "street",
  },
  {
    id: "clonazolam-fent",
    title: "Clonazolam + fentanyl",
    blurb: "High-potency RC benzo × opioid — boxed airway",
    drugIds: ["clonazolam", "fentanyl"],
    lane: "street",
  },
  {
    id: "apvp-maoi",
    title: "α-PVP + phenelzine",
    blurb: "Pyrovalerone stimulant × irreversible MAOI",
    drugIds: ["a-pvp", "phenelzine"],
    lane: "street",
  },
  {
    id: "scopolamine-dph",
    title: "Scopolamine + diphenhydramine",
    blurb: "Tropane × antihistamine — stacked delirium",
    drugIds: ["scopolamine", "diphenhydramine"],
    lane: "street",
  },
  {
    id: "meperidine-maoi",
    title: "Meperidine + phenelzine",
    blurb: "Labeled MAOI contraindication — serotonin + seizures",
    drugIds: ["meperidine", "phenelzine"],
    lane: "clinic",
  },
  {
    id: "cimetidine-tizanidine",
    title: "Cimetidine + tizanidine",
    blurb: "OTC 1A2 bully × sensitive 1A2 muscle relaxant",
    drugIds: ["cimetidine", "tizanidine"],
    lane: "clinic",
  },
  {
    id: "pheno-ocp",
    title: "Phenobarbital + OCP",
    blurb: "Pan-CYP induction — contraceptive failure",
    drugIds: ["phenobarbital", "ethinyl-estradiol"],
    lane: "clinic",
  },
  {
    id: "efavirenz-methadone",
    title: "Efavirenz + methadone",
    blurb: "2B6/3A4 induction precipitates opioid withdrawal",
    drugIds: ["efavirenz", "methadone"],
    lane: "clinic",
  },
  {
    id: "pimozide-clarith",
    title: "Pimozide + clarithromycin",
    blurb: "Sensitive 3A4 QT drug × strong 3A4 inhibitor",
    drugIds: ["pimozide", "clarithromycin"],
    lane: "clinic",
  },
  {
    id: "thioridazine-fluox",
    title: "Thioridazine + fluoxetine",
    blurb: "2D6 PM-like blockade of a boxed QT drug",
    drugIds: ["thioridazine", "fluoxetine"],
    lane: "clinic",
  },
  {
    id: "tapentadol-ssri",
    title: "Tapentadol + sertraline",
    blurb: "μ-agonist plus NRI meets an SSRI",
    drugIds: ["tapentadol", "sertraline"],
    lane: "clinic",
  },
  {
    id: "disulfiram-etoh",
    title: "Disulfiram + alcohol",
    blurb: "ALDH block — the acetaldehyde reaction",
    drugIds: ["disulfiram", "ethanol"],
    lane: "clinic",
  },
  {
    id: "warfarin-2c9pm",
    title: "Warfarin in a 2C9 PM",
    blurb: "Sensitive 2C9 substrate without a perpetrator drug",
    drugIds: ["warfarin"],
    lane: "phenotype",
    phenotypes: { CYP2C9: "PM" },
  },
  {
    id: "carisoprodol-2c19pm",
    title: "Carisoprodol in a 2C19 PM",
    blurb: "Meprobamate activation plus stacked parent",
    drugIds: ["carisoprodol"],
    lane: "phenotype",
    phenotypes: { CYP2C19: "PM" },
  },
  {
    id: "piperine-ketamine",
    title: "Piperine + oral ketamine",
    blurb: "Black-pepper 3A4/P-gp block on a first-pass victim",
    drugIds: ["piperine", "ketamine"],
    lane: "food",
    ketamineRoute: "oral",
  },
  {
    id: "licorice-sotalol",
    title: "Licorice + sotalol",
    blurb: "Glycyrrhizin hypokalemia plus a known QT drug",
    drugIds: ["licorice", "sotalol"],
    lane: "food",
  },
  {
    id: "starfruit-simva",
    title: "Star fruit + simvastatin",
    blurb: "Furanocoumarin-adjacent 3A4 hit on a sensitive statin",
    drugIds: ["starfruit", "simvastatin"],
    lane: "food",
  },
  {
    id: "ginkgo-warfarin",
    title: "Ginkgo + warfarin",
    blurb: "Herbal antiplatelet on a narrow-index anticoagulant",
    drugIds: ["ginkgo", "warfarin"],
    lane: "food",
  },
  {
    id: "clonidine-oxy",
    title: "Clonidine + oxycodone",
    blurb: "Clinical α2 agonist — naloxone will not fully reverse",
    drugIds: ["clonidine", "oxycodone"],
    lane: "mat",
  },
  {
    id: "dexmed-fent",
    title: "Dexmedetomidine + fentanyl",
    blurb: "Precedex α2 × opioid — naloxone will not reverse the α2",
    drugIds: ["dexmedetomidine", "fentanyl"],
    lane: "clinic",
  },
  {
    id: "propofol-midaz",
    title: "Propofol + midazolam",
    blurb: "IV anesthetic plus 3A4 benzo — stacked apnea",
    drugIds: ["propofol", "midazolam"],
    lane: "clinic",
  },
  {
    id: "prazosin-etoh",
    title: "Prazosin + alcohol",
    blurb: "α1 blockade plus ethanol — orthostatic syncope",
    drugIds: ["prazosin", "ethanol"],
    lane: "clinic",
  },
  {
    id: "sevenoh-benzo",
    title: "7-OH + alprazolam",
    blurb: "Hot kratom μ-agonist × benzo airway stack",
    drugIds: ["seven-oh", "alprazolam"],
    lane: "street",
  },
  {
    id: "primidone-ocp",
    title: "Primidone + OCP",
    blurb: "Barbiturate prodrug — contraceptive failure",
    drugIds: ["primidone", "ethinyl-estradiol"],
    lane: "clinic",
  },
  {
    id: "famotidine-tizanidine",
    title: "Famotidine + tizanidine",
    blurb: "The H2 that is not cimetidine — CYP row should stay quiet",
    drugIds: ["famotidine", "tizanidine"],
    lane: "clinic",
  },
  {
    id: "etonitazene-xylazine",
    title: "Etonitazene + xylazine",
    blurb: "Nitazene plus α2 — naloxone will not finish the job",
    drugIds: ["etonitazene", "xylazine"],
    lane: "street",
  },
  {
    id: "guanfacine-ritonavir",
    title: "Guanfacine + ritonavir",
    blurb: "ADHD α2 meets a strong 3A4 inhibitor",
    drugIds: ["guanfacine", "ritonavir"],
    lane: "clinic",
  },
  {
    id: "aprepitant-ketamine",
    title: "Aprepitant + oral ketamine",
    blurb: "NK1 antiemetic as a 3A4 perpetrator on a first-pass victim",
    drugIds: ["aprepitant", "ketamine"],
    lane: "clinic",
    ketamineRoute: "oral",
  },
  {
    id: "speedball-fent",
    title: "Speedball — cocaine + fentanyl",
    blurb: "Stimulant masks apnea; the opioid still stops the breathing",
    drugIds: ["cocaine", "fentanyl"],
    lane: "street",
  },
  {
    id: "percocet-alcohol",
    title: "Percocet + chronic alcohol",
    blurb: "Oxycodone + APAP on induced 2E1 — airway plus NAPQI",
    drugIds: ["oxycodone", "acetaminophen"],
    lane: "street",
    alcohol: "chronic",
  },
  {
    id: "dirty-30",
    title: "Dirty 30s (pressed M30 + xylazine)",
    blurb: "The stamp is oxycodone. The contents are not.",
    drugIds: ["dirty-30", "xylazine"],
    lane: "street",
  },
  {
    id: "perc-vs-pressed",
    title: "Perc 30 vs pressed 30",
    blurb: "Pharmaceutical oxycodone next to illicit fentanyl + tranq",
    drugIds: ["oxycodone", "fentanyl", "xylazine"],
    lane: "street",
  },
  {
    id: "speedball-heroin",
    title: "Classic speedball — cocaine + heroin",
    blurb: "The original mixer. Stimulant wears off first.",
    drugIds: ["cocaine", "heroin"],
    lane: "street",
  },
  {
    id: "bup-fentanyl",
    title: "Buprenorphine + fentanyl",
    blurb: "Partial agonist on a fentanyl load — precipitated withdrawal, not stacked mg",
    drugIds: ["buprenorphine", "fentanyl"],
    lane: "mat",
  },
  {
    id: "methadone-benzo",
    title: "Methadone + alprazolam",
    blurb: "OTP boxed warning — street benzo on a long μ agonist",
    drugIds: ["methadone", "alprazolam"],
    lane: "mat",
  },
  {
    id: "methadone-quetiapine",
    title: "Methadone + quetiapine",
    blurb: "Seroquel-for-sleep on a known-QT opioid",
    drugIds: ["methadone", "quetiapine"],
    lane: "mat",
  },
  {
    id: "methadone-rifampin",
    title: "Methadone + rifampin",
    blurb: "3A4/2B6 induction looks like a stolen dose",
    drugIds: ["methadone", "rifampin"],
    lane: "mat",
  },
  {
    id: "bup-ritonavir",
    title: "Buprenorphine + ritonavir",
    blurb: "HIV booster raises a 3A4 partial agonist",
    drugIds: ["buprenorphine", "ritonavir"],
    lane: "mat",
  },
  {
    id: "methadone-gabapentin",
    title: "Methadone + gabapentin",
    blurb: "The 'nerve pain' that still hits the airway",
    drugIds: ["methadone", "gabapentin"],
    lane: "mat",
  },
  {
    id: "methadone-cocaine",
    title: "Methadone + cocaine",
    blurb: "OTP speedball — QT plus masked apnea",
    drugIds: ["methadone", "cocaine"],
    lane: "mat",
  },
  {
    id: "bup-bromazolam",
    title: "Buprenorphine + bromazolam",
    blurb: "Street benzo on a Suboxone desk — boxed airway",
    drugIds: ["buprenorphine", "bromazolam"],
    lane: "mat",
  },
  {
    id: "lofexidine-fent",
    title: "Lofexidine + fentanyl",
    blurb: "Lucemyra is α2 — naloxone will not finish withdrawal sedation",
    drugIds: ["lofexidine", "fentanyl"],
    lane: "mat",
  },
  {
    id: "acamprosate-naltrexone",
    title: "Acamprosate + naltrexone",
    blurb: "Alcohol MAT pair — the CYP/PD rows should stay quiet",
    drugIds: ["acamprosate", "naltrexone"],
    lane: "mat",
  },
  {
    id: "methadone-citalopram",
    title: "Methadone + citalopram",
    blurb: "Two known-QT drugs on an OTP board",
    drugIds: ["methadone", "citalopram"],
    lane: "mat",
  },
];
